math.randomseed(os.time())

require('events/catholic_relief_act')
--require('events/cholera_spreads_events')
--require('events/dysentery_spread_events')
require('events/gevhdl_001')
require('events/gevhdl_002')
require('events/gevhdl_003')
require('events/gevhdl_004')
--require('events/panama_canal')
require('events/kalmar_union')
require('events/minas_gerais_crash')
require('events/test_event')
require('events/taza_concession')
require('events/unify_germany')

--invalid_shit()

set_date(1825, 0, 0)
print("********************************************************************************")
print("Industrial era mod")
print("Date: ", get_year(), "/", get_month(), "/", get_day())
print("********************************************************************************")
