-- Provinces
require('provinces/africa/northern')

require('provinces/americas/alaska')
require('provinces/americas/argentina')
require('provinces/americas/brazil_and_pantanal')
require('provinces/americas/canada')
require('provinces/americas/caribbean')
require('provinces/americas/central_america')
require('provinces/americas/chile')
require('provinces/americas/guianas')
require('provinces/americas/mexico')
require('provinces/americas/south_america')
require('provinces/americas/united_states')

require('provinces/asia/anatolia')

require('provinces/europe/austria')
require('provinces/europe/balkans')
require('provinces/europe/baltics')
require('provinces/europe/bohemia')
require('provinces/europe/britain')
require('provinces/europe/denmark')
require('provinces/europe/germany')
require('provinces/europe/italy')
require('provinces/europe/netherlands')
require('provinces/europe/france')
require('provinces/europe/greece')
require('provinces/europe/portugal')
require('provinces/europe/russia')
require('provinces/europe/scandinavia')
require('provinces/europe/spain')

require('provinces/oceania/hawaii')

require('provinces/unknown')