--------------------------------------------------------------
-- Continent: America
-- Subcontinent: South America
-- Country: Brazil

local province = Province:create{ ref_name = "ceara", color = 0x00FFFF }
province.name = _("Ceará")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "rio_grande_do_norte", color = 0xFF006E }
province.name = _("Rio Grande do Norte")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "paraiba", color = 0x4CFF00 }
province.name = _("Paraíba")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "pernambuco", color = 0x7F7F }
province.name = _("Pernambuco")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "alagoas", color = 0xB6FF00 }
province.name = _("Alagoas")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "sergipe", color = 0xFF6A00 }
province.name = _("Sergipe")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "bahia", color = 0xA0A0A0 }
province.name = _("Bahia")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "sao_francisco", color = 0xB200FF }
province.name = _("São Francisco")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "piaui", color = 0x49B0FF }
province.name = _("Piauí")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "maranhao", color = 0xC289FF }
province.name = _("Maranhão")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "grao_para", color = 0xFF6DDD }
province.name = _("Grão-Pará")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "oiapoque", color = 0x2ed500 }
province.name = _("Oiapoque")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "maraca", color = 0x939120 }
province.name = _("Maracá")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "roraima", color = 0xFFFD8E }
province.name = _("Roraima")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "mato_grosso", color = 0x9DFF35 }
province.name = _("Mato Grosso")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "goias", color = 0x49FF62 }
province.name = _("Goiás")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "minas_gerais", color = 0x9E0049 }
province.name = _("Minas Gerais")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "espirito_santo", color = 0x67639e }
province.name = _("Espirito Santo")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "sao_paulo", color = 0x7FFF8E }
province.name = _("São Paulo")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "rio_de_janeiro", color = 0x87639e }
province.name = _("Rio de Janeiro")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)
Nation:set_capital(brazil, province)

province = Province:create{ ref_name = "santa_catarina", color = 0xec1881 }
province.name = _("Santa Catarina")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "parana", color = 0xd1cc40 }
province.name = _("Paraná")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "oeste_catarinense", color = 0xFF26A4 }
province.name = _("Oeste Catarinense")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "porto_alegre", color = 0x96FFF8 }
province.name = _("Porto Alegre")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "bage", color = 0xD089FF }
province.name = _("Bagé")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "sao_borja", color = 0x6fa280 }
province.name = _("São Borja")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, brazilian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, brazilian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, brazilian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, brazilian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, brazilian, catholic, 500, 0.9)
Province:add_pop(province, slave, brazilian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:give_to(province, brazil)

province = Province:create{ ref_name = "cisplatina", color = 0xFFEA84 }
province.name = _("Cisplatina")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, cisplatinian, catholic, 5000, 0.7)
Province:add_pop(province, farmer, cisplatinian, catholic, 5000, 0.1)
Province:add_pop(province, soldier, cisplatinian, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, cisplatinian, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, cisplatinian, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, cisplatinian, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, cisplatinian, catholic, 5000, 0.3)
Province:add_pop(province, laborer, cisplatinian, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, cisplatinian, catholic, 500, 0.9)
Province:add_pop(province, slave, cisplatinian, catholic, 500, 0.5)
Province:add_nucleus(province, brazil)
Province:add_nucleus(province, argentina)
Province:give_to(province, brazil)

--------------------------------------------------------------
-- Continent: Americas
-- Subcontinent: South America
-- Country: Paraguay

province = Province:create{ ref_name = "asuncion", color = 0x00C7FF }
province.name = _("Asunción")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, paraguayan, catholic, 5000, 0.7)
Province:add_pop(province, farmer, paraguayan, catholic, 5000, 0.1)
Province:add_pop(province, soldier, paraguayan, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, paraguayan, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, paraguayan, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, paraguayan, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, paraguayan, catholic, 5000, 0.3)
Province:add_pop(province, laborer, paraguayan, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, paraguayan, catholic, 500, 0.9)
Province:add_pop(province, slave, paraguayan, catholic, 500, 0.5)
Province:add_nucleus(province, paraguay)
Province:give_to(province, paraguay)
Nation:set_capital(paraguay, province)

province = Province:create{ ref_name = "vila_sacaron", color = 0xB71CFF }
province.name = _("Vila Sacarón")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, paraguayan, catholic, 5000, 0.7)
Province:add_pop(province, farmer, paraguayan, catholic, 5000, 0.1)
Province:add_pop(province, soldier, paraguayan, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, paraguayan, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, paraguayan, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, paraguayan, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, paraguayan, catholic, 5000, 0.3)
Province:add_pop(province, laborer, paraguayan, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, paraguayan, catholic, 500, 0.9)
Province:add_pop(province, slave, paraguayan, catholic, 500, 0.5)
Province:add_nucleus(province, paraguay)
Province:give_to(province, paraguay)

province = Province:create{ ref_name = "nioaque", color = 0x5174FF }
province.name = _("Nioaque")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, paraguayan, catholic, 5000, 0.7)
Province:add_pop(province, farmer, paraguayan, catholic, 5000, 0.1)
Province:add_pop(province, soldier, paraguayan, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, paraguayan, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, paraguayan, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, paraguayan, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, paraguayan, catholic, 5000, 0.3)
Province:add_pop(province, laborer, paraguayan, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, paraguayan, catholic, 500, 0.9)
Province:add_pop(province, slave, paraguayan, catholic, 500, 0.5)
Province:add_nucleus(province, paraguay)
Province:give_to(province, paraguay)

--------------------------------------------------------------
-- Continent: Americas
-- Subcontinent: South America
-- Country: Bolivia + Chaco

province = Province:create{ ref_name = "pando", color = 0x47FBFF }
province.name = _("Pando")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, catholic, 5000, 0.7)
Province:add_pop(province, farmer, german, catholic, 5000, 0.1)
Province:add_pop(province, soldier, german, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, german, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, german, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, german, catholic, 5000, 0.3)
Province:add_pop(province, laborer, german, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, catholic, 500, 0.9)
Province:add_pop(province, slave, german, catholic, 500, 0.5)
Province:add_nucleus(province, bolivia)
Province:give_to(province, bolivia)

province = Province:create{ ref_name = "santa_cruz", color = 0xFFC4EE }
province.name = _("Santa Cruz")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, catholic, 5000, 0.7)
Province:add_pop(province, farmer, german, catholic, 5000, 0.1)
Province:add_pop(province, soldier, german, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, german, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, german, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, german, catholic, 5000, 0.3)
Province:add_pop(province, laborer, german, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, catholic, 500, 0.9)
Province:add_pop(province, slave, german, catholic, 500, 0.5)
Province:add_nucleus(province, bolivia)
Province:give_to(province, bolivia)
Nation:set_capital(bolivia, province)

province = Province:create{ ref_name = "carvoal", color = 0xFF8168 }
province.name = _("Carvoal")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, catholic, 5000, 0.7)
Province:add_pop(province, farmer, german, catholic, 5000, 0.1)
Province:add_pop(province, soldier, german, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, german, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, german, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, german, catholic, 5000, 0.3)
Province:add_pop(province, laborer, german, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, catholic, 500, 0.9)
Province:add_pop(province, slave, german, catholic, 500, 0.5)
Province:add_nucleus(province, bolivia)
Province:give_to(province, bolivia)

province = Province:create{ ref_name = "corumba", color = 0x8CFBFF }
province.name = _("Corumbá")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, catholic, 5000, 0.7)
Province:add_pop(province, farmer, german, catholic, 5000, 0.1)
Province:add_pop(province, soldier, german, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, german, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, german, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, german, catholic, 5000, 0.3)
Province:add_pop(province, laborer, german, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, catholic, 500, 0.9)
Province:add_pop(province, slave, german, catholic, 500, 0.5)
Province:add_nucleus(province, bolivia)
Province:give_to(province, bolivia)

province = Province:create{ ref_name = "santissima_trinidade", color = 0x5E1EFF }
province.name = _("Santíssima Trinidade")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, catholic, 5000, 0.7)
Province:add_pop(province, farmer, german, catholic, 5000, 0.1)
Province:add_pop(province, soldier, german, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, german, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, german, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, german, catholic, 5000, 0.3)
Province:add_pop(province, laborer, german, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, catholic, 500, 0.9)
Province:add_pop(province, slave, german, catholic, 500, 0.5)
Province:add_nucleus(province, bolivia)
Province:give_to(province, bolivia)

province = Province:create{ ref_name = "fuerte_olimpo", color = 0x6f6071 }
province.name = _("Fuerte Olimpo")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, catholic, 5000, 0.7)
Province:add_pop(province, farmer, german, catholic, 5000, 0.1)
Province:add_pop(province, soldier, german, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, german, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, german, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, german, catholic, 5000, 0.3)
Province:add_pop(province, laborer, german, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, catholic, 500, 0.9)
Province:add_pop(province, slave, german, catholic, 500, 0.5)
Province:add_nucleus(province, bolivia)

province = Province:create{ ref_name = "nueva_burdeos", color = 0xFFD149 }
province.name = _("Nueva Burdeos")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, catholic, 5000, 0.7)
Province:add_pop(province, farmer, german, catholic, 5000, 0.1)
Province:add_pop(province, soldier, german, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, german, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, german, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, german, catholic, 5000, 0.3)
Province:add_pop(province, laborer, german, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, catholic, 500, 0.9)
Province:add_pop(province, slave, german, catholic, 500, 0.5)
Province:add_nucleus(province, bolivia)
Province:add_nucleus(province, paraguay)

province = Province:create{ ref_name = "la_paz", color = 0xFF2158 }
province.name = _("La Paz")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, catholic, 5000, 0.7)
Province:add_pop(province, farmer, german, catholic, 5000, 0.1)
Province:add_pop(province, soldier, german, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, german, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, german, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, german, catholic, 5000, 0.3)
Province:add_pop(province, laborer, german, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, catholic, 500, 0.9)
Province:add_pop(province, slave, german, catholic, 500, 0.5)
Province:add_nucleus(province, bolivia)
Province:give_to(province, bolivia)

province = Province:create{ ref_name = "cochabamba", color = 0xCB3FFF }
province.name = _("Cochabamba")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, catholic, 5000, 0.7)
Province:add_pop(province, farmer, german, catholic, 5000, 0.1)
Province:add_pop(province, soldier, german, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, german, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, german, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, german, catholic, 5000, 0.3)
Province:add_pop(province, laborer, german, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, catholic, 500, 0.9)
Province:add_pop(province, slave, german, catholic, 500, 0.5)
Province:add_nucleus(province, bolivia)
Province:give_to(province, bolivia)

province = Province:create{ ref_name = "oruro", color = 0x75FFCC }
province.name = _("Oruro")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, catholic, 5000, 0.7)
Province:add_pop(province, farmer, german, catholic, 5000, 0.1)
Province:add_pop(province, soldier, german, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, german, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, german, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, german, catholic, 5000, 0.3)
Province:add_pop(province, laborer, german, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, catholic, 500, 0.9)
Province:add_pop(province, slave, german, catholic, 500, 0.5)
Province:add_nucleus(province, bolivia)
Province:give_to(province, bolivia)

province = Province:create{ ref_name = "potosi", color = 0xFC63FF }
province.name = _("Potosí")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, catholic, 5000, 0.7)
Province:add_pop(province, farmer, german, catholic, 5000, 0.1)
Province:add_pop(province, soldier, german, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, german, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, german, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, german, catholic, 5000, 0.3)
Province:add_pop(province, laborer, german, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, catholic, 500, 0.9)
Province:add_pop(province, slave, german, catholic, 500, 0.5)
Province:add_nucleus(province, bolivia)
Province:give_to(province, bolivia)

province = Province:create{ ref_name = "chuquisaca", color = 0x4FA7FF }
province.name = _("Chuquisaca")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, catholic, 5000, 0.7)
Province:add_pop(province, farmer, german, catholic, 5000, 0.1)
Province:add_pop(province, soldier, german, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, german, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, german, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, german, catholic, 5000, 0.3)
Province:add_pop(province, laborer, german, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, catholic, 500, 0.9)
Province:add_pop(province, slave, german, catholic, 500, 0.5)
Province:add_nucleus(province, bolivia)
Province:give_to(province, bolivia)

province = Province:create{ ref_name = "tarija", color = 0x907CFF }
province.name = _("Tarija")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, catholic, 5000, 0.7)
Province:add_pop(province, farmer, german, catholic, 5000, 0.1)
Province:add_pop(province, soldier, german, catholic, 5000, 0.2)
Province:add_pop(province, craftsmen, german, catholic, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, catholic, 5000, 0.7)
Province:add_pop(province, aristocrat, german, catholic, 5000, 0.2)
Province:add_pop(province, clergymen, german, catholic, 5000, 0.3)
Province:add_pop(province, laborer, german, catholic, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, catholic, 500, 0.9)
Province:add_pop(province, slave, german, catholic, 500, 0.5)
Province:add_nucleus(province, bolivia)
Province:give_to(province, bolivia)
