--------------------------------------------------------------
-- Continent: Americas
-- Subcontinent: North America
-- Country: The British Empire (Canada + bermuda)
province = Province:create{ ref_name = "inner_baffin", color = rgb(236, 153, 255) }
province.name = _("Inner Baffin")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)

province = Province:create{ ref_name = "outer_baffin", color = rgb(175, 255, 219) }
province.name = _("Outer Baffin")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)
Province:give_to(province, united_kingdom)

province = Province:create{ ref_name = "arctic_islands", color = rgb(214, 206, 255) }
province.name = _("Arctic Islands")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)

province = Province:create{ ref_name = "north_yukon", color = rgb(255, 66, 198) }
province.name = _("North Yukon")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)

province = Province:create{ ref_name = "south_yukon", color = rgb(86, 246, 255) }
province.name = _("South Yukon")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)

province = Province:create{ ref_name = "fort_resolution", color = rgb(255, 253, 181) }
province.name = _("Fort Resolution")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)

province = Province:create{ ref_name = "southern_arctic", color = rgb(255, 84, 137) }
province.name = _("Southern Arctic")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)

province = Province:create{ ref_name = "rankin_inlet", color = rgb(142, 176, 255) }
province.name = _("Rankin Inlet")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)

province = Province:create{ ref_name = "eastern_northwestern_territories", color = rgb(255, 162, 155) }
province.name = _("Eastern Northwestern Territories")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)

province = Province:create{ ref_name = "hudson_bay_islands", color = rgb(255, 71, 255) }
province.name = _("Hudson Bay Islands")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)

province = Province:create{ ref_name = "north_quebec", color = rgb(188, 112, 255) }
province.name = _("North Quebec")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)

province = Province:create{ ref_name = "south_quebec", color = rgb(255, 95, 84) }
province.name = _("South Quebec")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)
Province:give_to(province, united_kingdom)

province = Province:create{ ref_name = "labrador", color = rgb(168, 237, 255) }
province.name = _("Labrador")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)
Province:give_to(province, united_kingdom)

province = Province:create{ ref_name = "newfoundland", color = rgb(91, 255, 148) }
province.name = _("Newfoundland")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)
Province:give_to(province, united_kingdom)

province = Province:create{ ref_name = "prince_edward_island", color = rgb(104, 174, 255) }
province.name = _("Prince Edward Island")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)
Province:give_to(province, united_kingdom)

province = Province:create{ ref_name = "nova_scotia", color = rgb(196, 255, 225) }
province.name = _("Nova Scotia")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)
Province:give_to(province, united_kingdom)

province = Province:create{ ref_name = "new_brunswick", color = rgb(153, 99, 255) }
province.name = _("New Brunswick")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)
Province:give_to(province, united_kingdom)

province = Province:create{ ref_name = "temiscouata", color = rgb(255, 126, 119) }
province.name = _("Temiscouata")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)
Province:give_to(province, united_kingdom)

province = Province:create{ ref_name = "madawaska", color = rgb(204, 255, 228) }
province.name = _("Madawaska")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)
Province:give_to(province, united_kingdom)

province = Province:create{ ref_name = "ontario", color = rgb(255, 124, 153) }
province.name = _("Ontario")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)
Province:give_to(province, united_kingdom)

province = Province:create{ ref_name = "north_ontario", color = rgb(142, 182, 255) }
province.name = _("North Ontario")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)

province = Province:create{ ref_name = "thunder_bay", color = rgb(211, 255, 240) }
province.name = _("Thunder Bay")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)
Province:give_to(province, united_kingdom)

province = Province:create{ ref_name = "kenora", color = rgb(255, 99, 231) }
province.name = _("Kenora")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)
Province:give_to(province, united_kingdom)

province = Province:create{ ref_name = "port_nelson", color = rgb(114, 255, 252) }
province.name = _("Port Nelson")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)

province = Province:create{ ref_name = "winnipeg", color = rgb(255, 138, 130) }
province.name = _("Winnipeg")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)

province = Province:create{ ref_name = "athabasca", color = rgb(255, 252, 130) }
province.name = _("Athabasca")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)

-- Change name to Saskatchewan after 1905
province = Province:create{ ref_name = "eastern_prairies", color = rgb(142, 204, 255) }
province.name = _("Eastern Prairies")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)

province = Province:create{ ref_name = "western_prairies", color = rgb(177, 114, 255) }
province.name = _("Western Prairies")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)

province = Province:create{ ref_name = "boreal_plains", color = rgb(255, 66, 85) }
province.name = _("Boreal Plains")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)

province = Province:create{ ref_name = "northern_canadian_rockies", color = rgb(102, 203, 255) }
province.name = _("Northern Canadian Rockies")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)

province = Province:create{ ref_name = "southern_canadian_rockies", color = rgb(255, 94, 230) }
province.name = _("Southern Canadian Rockies")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)
Province:give_to(province, united_kingdom)

province = Province:create{ ref_name = "north_vancouver", color = rgb(137, 233, 255) }
province.name = _("North Vancouver")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)
Province:give_to(province, united_kingdom)

province = Province:create{ ref_name = "south_vancouver", color = 0xffb5a0 }
province.name = _("South Vancouver")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)
Province:give_to(province, united_kingdom)

province = Province:create{ ref_name = "queen_charlotte_islands", color = rgb(255, 168, 253) }
province.name = _("Queen Charlotte Islands")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)
Province:give_to(province, united_kingdom)

province = Province:create{ ref_name = "bermuda", color = rgb(232, 61, 255) }
province.name = _("Bermuda")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, british, protestant, 300, 0.7)
Province:add_pop(province, farmer, british, protestant, 2700, 0.6)
Province:add_pop(province, soldier, british, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, british, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, british, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, british, protestant, 200, 0.9)
Province:add_pop(province, clergymen, british, protestant, 500, 0.9)
Province:add_pop(province, laborer, british, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, british, protestant, 100, 0.9)
Province:add_pop(province, artisan, yankee, protestant, 300, 0.7)
Province:add_pop(province, farmer, yankee, protestant, 2700, 0.6)
Province:add_pop(province, soldier, yankee, protestant, 800, 0.8)
Province:add_pop(province, craftsmen, yankee, protestant, 700, 0.5)
Province:add_pop(province, bureaucrat, yankee, protestant, 200, 0.7)
Province:add_pop(province, aristocrat, yankee, protestant, 200, 0.9)
Province:add_pop(province, clergymen, yankee, protestant, 500, 0.9)
Province:add_pop(province, laborer, yankee, protestant, 2700, 0.8)
Province:add_pop(province, entrepreneur, yankee, protestant, 100, 0.9)
Province:add_nucleus(province, united_kingdom)
Province:give_to(province, united_kingdom)