--------------------------------------------------------------
-- Continent: Americas
-- Subcontinent: Central America
-- Country: USCA

province = Province:new{ ref_name = "bocas_del_toro", color = 0xB7CAFF }
province.name = _("Bocas del Toro")
Province:register(province)
Province:add_industry(province, gold_mine, andes_transport)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, protestant, 5000, 0.7)
Province:add_pop(province, farmer, german, protestant, 5000, 0.1)
Province:add_pop(province, soldier, german, protestant, 5000, 0.2)
Province:add_pop(province, craftsmen, german, protestant, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, protestant, 5000, 0.7)
Province:add_pop(province, aristocrat, german, protestant, 5000, 0.2)
Province:add_pop(province, clergymen, german, protestant, 5000, 0.3)
Province:add_pop(province, laborer, german, protestant, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, protestant, 500, 0.9)
Province:add_pop(province, slave, german, protestant, 500, 0.5)
Province:add_nucleus(province, federated_republic_central_america)
Province:give_to(province, federated_republic_central_america)

province = Province:new{ ref_name = "cabagra", color = 0xFF87D5 }
province.name = _("Cabagra")
Province:register(province)
Province:add_industry(province, gold_mine, andes_transport)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, protestant, 5000, 0.7)
Province:add_pop(province, farmer, german, protestant, 5000, 0.1)
Province:add_pop(province, soldier, german, protestant, 5000, 0.2)
Province:add_pop(province, craftsmen, german, protestant, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, protestant, 5000, 0.7)
Province:add_pop(province, aristocrat, german, protestant, 5000, 0.2)
Province:add_pop(province, clergymen, german, protestant, 5000, 0.3)
Province:add_pop(province, laborer, german, protestant, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, protestant, 500, 0.9)
Province:add_pop(province, slave, german, protestant, 500, 0.5)
Province:add_nucleus(province, federated_republic_central_america)
Province:give_to(province, federated_republic_central_america)

province = Province:new{ ref_name = "san_jose", color = 0x9EFFFF }
province.name = _("San José")
Province:register(province)
Province:add_industry(province, sulfur_mine, andes_transport)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, protestant, 5000, 0.7)
Province:add_pop(province, farmer, german, protestant, 5000, 0.1)
Province:add_pop(province, soldier, german, protestant, 5000, 0.2)
Province:add_pop(province, craftsmen, german, protestant, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, protestant, 5000, 0.7)
Province:add_pop(province, aristocrat, german, protestant, 5000, 0.2)
Province:add_pop(province, clergymen, german, protestant, 5000, 0.3)
Province:add_pop(province, laborer, german, protestant, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, protestant, 500, 0.9)
Province:add_pop(province, slave, german, protestant, 500, 0.5)
Province:add_nucleus(province, federated_republic_central_america)
Province:give_to(province, federated_republic_central_america)

province = Province:new{ ref_name = "liberia", color = 0x7C7AFF }
province.name = _("Libéria")
Province:register(province)
Province:add_industry(province, sulfur_mine, andes_transport)
Province:add_industry(province, sulfur_mine, andes_transport)
Province:add_industry(province, sulfur_mine, andes_transport)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, protestant, 5000, 0.7)
Province:add_pop(province, farmer, german, protestant, 5000, 0.1)
Province:add_pop(province, soldier, german, protestant, 5000, 0.2)
Province:add_pop(province, craftsmen, german, protestant, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, protestant, 5000, 0.7)
Province:add_pop(province, aristocrat, german, protestant, 5000, 0.2)
Province:add_pop(province, clergymen, german, protestant, 5000, 0.3)
Province:add_pop(province, laborer, german, protestant, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, protestant, 500, 0.9)
Province:add_pop(province, slave, german, protestant, 500, 0.5)
Province:add_nucleus(province, federated_republic_central_america)
Province:give_to(province, federated_republic_central_america)

province = Province:new{ ref_name = "nicoya", color = 0xFF7CC0 }
province.name = _("Nicoya")
Province:register(province)
Province:add_industry(province, sulfur_mine, andes_transport)
Province:add_industry(province, sulfur_mine, andes_transport)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, protestant, 5000, 0.7)
Province:add_pop(province, farmer, german, protestant, 5000, 0.1)
Province:add_pop(province, soldier, german, protestant, 5000, 0.2)
Province:add_pop(province, craftsmen, german, protestant, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, protestant, 5000, 0.7)
Province:add_pop(province, aristocrat, german, protestant, 5000, 0.2)
Province:add_pop(province, clergymen, german, protestant, 5000, 0.3)
Province:add_pop(province, laborer, german, protestant, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, protestant, 500, 0.9)
Province:add_pop(province, slave, german, protestant, 500, 0.5)
Province:add_nucleus(province, federated_republic_central_america)
Province:give_to(province, federated_republic_central_america)

province = Province:new{ ref_name = "mosquito_coast", color = 0x5199FF }
province.name = _("Mosquito Coast")
Province:register(province)
Province:add_industry(province, sulfur_mine, andes_transport)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, protestant, 5000, 0.7)
Province:add_pop(province, farmer, german, protestant, 5000, 0.1)
Province:add_pop(province, soldier, german, protestant, 5000, 0.2)
Province:add_pop(province, craftsmen, german, protestant, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, protestant, 5000, 0.7)
Province:add_pop(province, aristocrat, german, protestant, 5000, 0.2)
Province:add_pop(province, clergymen, german, protestant, 5000, 0.3)
Province:add_pop(province, laborer, german, protestant, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, protestant, 500, 0.9)
Province:add_pop(province, slave, german, protestant, 500, 0.5)
Province:add_nucleus(province, federated_republic_central_america)
Province:give_to(province, federated_republic_central_america)

province = Province:new{ ref_name = "nicaragua", color = 0xFFCEAD }
province.name = _("Nicarágua")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, protestant, 5000, 0.7)
Province:add_pop(province, farmer, german, protestant, 5000, 0.1)
Province:add_pop(province, soldier, german, protestant, 5000, 0.2)
Province:add_pop(province, craftsmen, german, protestant, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, protestant, 5000, 0.7)
Province:add_pop(province, aristocrat, german, protestant, 5000, 0.2)
Province:add_pop(province, clergymen, german, protestant, 5000, 0.3)
Province:add_pop(province, laborer, german, protestant, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, protestant, 500, 0.9)
Province:add_pop(province, slave, german, protestant, 500, 0.5)
Province:add_nucleus(province, federated_republic_central_america)
Province:give_to(province, federated_republic_central_america)

province = Province:new{ ref_name = "puerto_lempira", color = 0xCD9BFF }
province.name = _("Puerto Lempira")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, protestant, 5000, 0.7)
Province:add_pop(province, farmer, german, protestant, 5000, 0.1)
Province:add_pop(province, soldier, german, protestant, 5000, 0.2)
Province:add_pop(province, craftsmen, german, protestant, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, protestant, 5000, 0.7)
Province:add_pop(province, aristocrat, german, protestant, 5000, 0.2)
Province:add_pop(province, clergymen, german, protestant, 5000, 0.3)
Province:add_pop(province, laborer, german, protestant, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, protestant, 500, 0.9)
Province:add_pop(province, slave, german, protestant, 500, 0.5)
Province:add_nucleus(province, federated_republic_central_america)
Province:give_to(province, federated_republic_central_america)

province = Province:new{ ref_name = "honduras", color = 0xFF89B8 }
province.name = _("Honduras")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, protestant, 5000, 0.7)
Province:add_pop(province, farmer, german, protestant, 5000, 0.1)
Province:add_pop(province, soldier, german, protestant, 5000, 0.2)
Province:add_pop(province, craftsmen, german, protestant, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, protestant, 5000, 0.7)
Province:add_pop(province, aristocrat, german, protestant, 5000, 0.2)
Province:add_pop(province, clergymen, german, protestant, 5000, 0.3)
Province:add_pop(province, laborer, german, protestant, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, protestant, 500, 0.9)
Province:add_pop(province, slave, german, protestant, 500, 0.5)
Province:add_nucleus(province, federated_republic_central_america)
Province:give_to(province, federated_republic_central_america)

province = Province:new{ ref_name = "el_salvador", color = 0xB599FF }
province.name = _("El Salvador")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, protestant, 5000, 0.7)
Province:add_pop(province, farmer, german, protestant, 5000, 0.1)
Province:add_pop(province, soldier, german, protestant, 5000, 0.2)
Province:add_pop(province, craftsmen, german, protestant, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, protestant, 5000, 0.7)
Province:add_pop(province, aristocrat, german, protestant, 5000, 0.2)
Province:add_pop(province, clergymen, german, protestant, 5000, 0.3)
Province:add_pop(province, laborer, german, protestant, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, protestant, 500, 0.9)
Province:add_pop(province, slave, german, protestant, 500, 0.5)
Province:add_nucleus(province, federated_republic_central_america)
Province:give_to(province, federated_republic_central_america)
Nation:set_capital(federated_republic_central_america, province)

province = Province:new{ ref_name = "ahuachapan", color = 0xF572FF }
province.name = _("Ahuachapán")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, protestant, 5000, 0.7)
Province:add_pop(province, farmer, german, protestant, 5000, 0.1)
Province:add_pop(province, soldier, german, protestant, 5000, 0.2)
Province:add_pop(province, craftsmen, german, protestant, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, protestant, 5000, 0.7)
Province:add_pop(province, aristocrat, german, protestant, 5000, 0.2)
Province:add_pop(province, clergymen, german, protestant, 5000, 0.3)
Province:add_pop(province, laborer, german, protestant, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, protestant, 500, 0.9)
Province:add_pop(province, slave, german, protestant, 500, 0.5)
Province:add_nucleus(province, federated_republic_central_america)
Province:give_to(province, federated_republic_central_america)

province = Province:new{ ref_name = "sonsonate", color = 0xA47AFF }
province.name = _("Sonsonate")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, protestant, 5000, 0.7)
Province:add_pop(province, farmer, german, protestant, 5000, 0.1)
Province:add_pop(province, soldier, german, protestant, 5000, 0.2)
Province:add_pop(province, craftsmen, german, protestant, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, protestant, 5000, 0.7)
Province:add_pop(province, aristocrat, german, protestant, 5000, 0.2)
Province:add_pop(province, clergymen, german, protestant, 5000, 0.3)
Province:add_pop(province, laborer, german, protestant, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, protestant, 500, 0.9)
Province:add_pop(province, slave, german, protestant, 500, 0.5)
Province:add_nucleus(province, federated_republic_central_america)
Province:give_to(province, federated_republic_central_america)

province = Province:new{ ref_name = "guatemala", color = 0xFFDD82 }
province.name = _("Guatemala")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, protestant, 5000, 0.7)
Province:add_pop(province, farmer, german, protestant, 5000, 0.1)
Province:add_pop(province, soldier, german, protestant, 5000, 0.2)
Province:add_pop(province, craftsmen, german, protestant, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, protestant, 5000, 0.7)
Province:add_pop(province, aristocrat, german, protestant, 5000, 0.2)
Province:add_pop(province, clergymen, german, protestant, 5000, 0.3)
Province:add_pop(province, laborer, german, protestant, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, protestant, 500, 0.9)
Province:add_pop(province, slave, german, protestant, 500, 0.5)
Province:add_nucleus(province, federated_republic_central_america)
Province:give_to(province, federated_republic_central_america)

province = Province:new{ ref_name = "alacranes", color = 0xFF0019 }
province.name = _("Alacranes")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, protestant, 5000, 0.7)
Province:add_pop(province, farmer, german, protestant, 5000, 0.1)
Province:add_pop(province, soldier, german, protestant, 5000, 0.2)
Province:add_pop(province, craftsmen, german, protestant, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, protestant, 5000, 0.7)
Province:add_pop(province, aristocrat, german, protestant, 5000, 0.2)
Province:add_pop(province, clergymen, german, protestant, 5000, 0.3)
Province:add_pop(province, laborer, german, protestant, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, protestant, 500, 0.9)
Province:add_pop(province, slave, german, protestant, 500, 0.5)
Province:add_nucleus(province, federated_republic_central_america)
Province:give_to(province, federated_republic_central_america)

province = Province:new{ ref_name = "calakmul", color = 0xFF66FF }
province.name = _("Calakmul")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, protestant, 5000, 0.7)
Province:add_pop(province, farmer, german, protestant, 5000, 0.1)
Province:add_pop(province, soldier, german, protestant, 5000, 0.2)
Province:add_pop(province, craftsmen, german, protestant, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, protestant, 5000, 0.7)
Province:add_pop(province, aristocrat, german, protestant, 5000, 0.2)
Province:add_pop(province, clergymen, german, protestant, 5000, 0.3)
Province:add_pop(province, laborer, german, protestant, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, protestant, 500, 0.9)
Province:add_pop(province, slave, german, protestant, 500, 0.5)
Province:add_nucleus(province, federated_republic_central_america)
Province:give_to(province, federated_republic_central_america)

province = Province:new{ ref_name = "el_ceibo", color = 0x54FF79 }
province.name = _("El Ceibo")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, protestant, 5000, 0.7)
Province:add_pop(province, farmer, german, protestant, 5000, 0.1)
Province:add_pop(province, soldier, german, protestant, 5000, 0.2)
Province:add_pop(province, craftsmen, german, protestant, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, protestant, 5000, 0.7)
Province:add_pop(province, aristocrat, german, protestant, 5000, 0.2)
Province:add_pop(province, clergymen, german, protestant, 5000, 0.3)
Province:add_pop(province, laborer, german, protestant, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, protestant, 500, 0.9)
Province:add_pop(province, slave, german, protestant, 500, 0.5)
Province:add_nucleus(province, federated_republic_central_america)
Province:give_to(province, federated_republic_central_america)

province = Province:new{ ref_name = "selva_lancadona", color = 0xFF8A6D }
province.name = _("Selva Lancadona")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, protestant, 5000, 0.7)
Province:add_pop(province, farmer, german, protestant, 5000, 0.1)
Province:add_pop(province, soldier, german, protestant, 5000, 0.2)
Province:add_pop(province, craftsmen, german, protestant, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, protestant, 5000, 0.7)
Province:add_pop(province, aristocrat, german, protestant, 5000, 0.2)
Province:add_pop(province, clergymen, german, protestant, 5000, 0.3)
Province:add_pop(province, laborer, german, protestant, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, protestant, 500, 0.9)
Province:add_pop(province, slave, german, protestant, 500, 0.5)
Province:add_nucleus(province, federated_republic_central_america)
Province:give_to(province, federated_republic_central_america)

province = Province:new{ ref_name = "motozintla", color = 0x77B9FF }
province.name = _("Motozintla")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, protestant, 5000, 0.7)
Province:add_pop(province, farmer, german, protestant, 5000, 0.1)
Province:add_pop(province, soldier, german, protestant, 5000, 0.2)
Province:add_pop(province, craftsmen, german, protestant, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, protestant, 5000, 0.7)
Province:add_pop(province, aristocrat, german, protestant, 5000, 0.2)
Province:add_pop(province, clergymen, german, protestant, 5000, 0.3)
Province:add_pop(province, laborer, german, protestant, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, protestant, 500, 0.9)
Province:add_pop(province, slave, german, protestant, 500, 0.5)
Province:add_nucleus(province, federated_republic_central_america)
Province:give_to(province, federated_republic_central_america)

province = Province:new{ ref_name = "tapachula", color = 0x7C5BFF }
province.name = _("Tapachula")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, protestant, 5000, 0.7)
Province:add_pop(province, farmer, german, protestant, 5000, 0.1)
Province:add_pop(province, soldier, german, protestant, 5000, 0.2)
Province:add_pop(province, craftsmen, german, protestant, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, protestant, 5000, 0.7)
Province:add_pop(province, aristocrat, german, protestant, 5000, 0.2)
Province:add_pop(province, clergymen, german, protestant, 5000, 0.3)
Province:add_pop(province, laborer, german, protestant, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, protestant, 500, 0.9)
Province:add_pop(province, slave, german, protestant, 500, 0.5)
Province:add_nucleus(province, federated_republic_central_america)
Province:give_to(province, federated_republic_central_america)

province = Province:new{ ref_name = "islas_de_la_bahia", color = 0xFF11A8 }
province.name = _("Islas de La Bahía")
Province:register(province)
Province:add_industry(province, wheat_farm, andes_transport)
Province:add_pop(province, artisan, german, protestant, 5000, 0.7)
Province:add_pop(province, farmer, german, protestant, 5000, 0.1)
Province:add_pop(province, soldier, german, protestant, 5000, 0.2)
Province:add_pop(province, craftsmen, german, protestant, 5000, 0.2)
Province:add_pop(province, bureaucrat, german, protestant, 5000, 0.7)
Province:add_pop(province, aristocrat, german, protestant, 5000, 0.2)
Province:add_pop(province, clergymen, german, protestant, 5000, 0.3)
Province:add_pop(province, laborer, german, protestant, 5000, 0.2)
Province:add_pop(province, entrepreneur, german, protestant, 500, 0.9)
Province:add_pop(province, slave, german, protestant, 500, 0.5)
Province:add_nucleus(province, federated_republic_central_america)
Province:give_to(province, federated_republic_central_america)
