--------------------------------------------------------------
-- Continent: Oceania
-- Subcontinent: Polynesia
-- Country: Hawai'i
province = Province:new{ ref_name = "papahānaumokuākea", color = 0xcea3ff }
province.name = _("Papahānaumokuākea")
Province:register(province)
Province:add_pop(province, artisan, polynesian, protestant, 10, 0.6)
Province:add_pop(province, farmer, polynesian, protestant, 8000, 0.4)
Province:add_pop(province, soldier, polynesian, protestant, 10, 0.6)
Province:add_pop(province, craftsmen, polynesian, protestant, 10, 0.4)
Province:add_pop(province, bureaucrat, polynesian, protestant, 10, 0.8)
Province:add_pop(province, aristocrat, polynesian, protestant, 25, 0.5)
Province:add_pop(province, clergymen, polynesian, protestant, 10, 0.6)
Province:add_pop(province, laborer, polynesian, protestant, 1000, 0.5)
Province:add_pop(province, entrepreneur, polynesian, protestant, 5, 0.9)
Province:add_nucleus(province, hawai_i)
Province:give_to(province, hawai_i)

province = Province:new{ ref_name = "kaua_i", color = 0x0f6bff }
province.name = _("Kaua'i")
Province:register(province)
Province:add_pop(province, artisan, polynesian, protestant, 10, 0.6)
Province:add_pop(province, farmer, polynesian, protestant, 8000, 0.4)
Province:add_pop(province, soldier, polynesian, protestant, 10, 0.6)
Province:add_pop(province, craftsmen, polynesian, protestant, 10, 0.4)
Province:add_pop(province, bureaucrat, polynesian, protestant, 10, 0.8)
Province:add_pop(province, aristocrat, polynesian, protestant, 25, 0.5)
Province:add_pop(province, clergymen, polynesian, protestant, 10, 0.6)
Province:add_pop(province, laborer, polynesian, protestant, 1000, 0.5)
Province:add_pop(province, entrepreneur, polynesian, protestant, 5, 0.9)
Province:add_nucleus(province, hawai_i)
Province:give_to(province, hawai_i)

province = Province:new{ ref_name = "o_ahu_maui", color = 0xff7247 }
province.name = _("O'ahu-Maui")
Province:register(province)
Province:add_pop(province, artisan, polynesian, protestant, 10, 0.6)
Province:add_pop(province, farmer, polynesian, protestant, 8000, 0.4)
Province:add_pop(province, soldier, polynesian, protestant, 10, 0.6)
Province:add_pop(province, craftsmen, polynesian, protestant, 10, 0.4)
Province:add_pop(province, bureaucrat, polynesian, protestant, 10, 0.8)
Province:add_pop(province, aristocrat, polynesian, protestant, 25, 0.5)
Province:add_pop(province, clergymen, polynesian, protestant, 10, 0.6)
Province:add_pop(province, laborer, polynesian, protestant, 1000, 0.5)
Province:add_pop(province, entrepreneur, polynesian, protestant, 5, 0.9)
Province:add_nucleus(province, hawai_i)
Province:give_to(province, hawai_i)

-- Whoever did this please fix!!!!
province = Province:new{ ref_name = "hawai_i", color = 0xff54a1 }
province.name = _("Hawai'i")
Province:register(province)
Province:add_pop(province, artisan, polynesian, protestant, 10, 0.6)
Province:add_pop(province, farmer, polynesian, protestant, 8000, 0.4)
Province:add_pop(province, soldier, polynesian, protestant, 10, 0.6)
Province:add_pop(province, craftsmen, polynesian, protestant, 10, 0.4)
Province:add_pop(province, bureaucrat, polynesian, protestant, 10, 0.8)
Province:add_pop(province, aristocrat, polynesian, protestant, 25, 0.5)
Province:add_pop(province, clergymen, polynesian, protestant, 10, 0.6)
Province:add_pop(province, laborer, polynesian, protestant, 1000, 0.5)
Province:add_pop(province, entrepreneur, polynesian, protestant, 5, 0.9)
Province:add_nucleus(province, hawai_i)
Province:give_to(province, hawai_i)
Nation:set_capital(hawai_i, province)