-- AI Control Window
UI_RegisterCallback("ai_settings_window_invoke", function()
    local ai_sett_win = UI_Window:new(0, 0, 512, 256)
    ai_sett_win:set_scroll(false)
    ai_sett_win:text("AI Control")
    ai_sett_win:set_close_btn_func(function(widget)
        UI_CallBuiltin("gs.ai_control.form_packet")
        widget:kill()
    end)

    local cmd_chk = UI_Checkbox:new(0, 0, ai_sett_win.w, ai_sett_win.h)
    cmd_chk:text(_("Command troops"))
    cmd_chk:set_value(UI_CallBuiltin("gs.ai_do_cmd_troops.get"))
    cmd_chk:set_on_click(function(widget)
        UI_CallBuiltin("gs.ai_do_cmd_troops.set", UI_ReinterpretAs(UI_Checkbox, widget):get_value())
    end)
    cmd_chk:set_tooltip("Units will be managed by the AI")
end)
