--------------------------------------------------------------
-- Continent: Americas
-- Subcontinent: North America
-- Country: Russian Empire
-- Change to Western Alaska if taken by the US or UK
province = Province:new{ ref_name = "zapadnaya_alyaska", color = rgb(214, 255, 215) }
province.name = _("Zapadnaya Alyaska")
province:register()
province:add_industry(wheat_farm, royal_russia_transport)
province:add_pop(artisan, russian, orthodox, 300, 0.7)
province:add_pop(farmer, russian, orthodox, 2700, 0.6)
province:add_pop(soldier, russian, orthodox, 800, 0.8)
province:add_pop(craftsmen, russian, orthodox, 700, 0.5)
province:add_pop(bureaucrat, russian, orthodox, 200, 0.7)
province:add_pop(aristocrat, russian, orthodox, 200, 0.9)
province:add_pop(clergymen, russian, orthodox, 500, 0.9)
province:add_pop(laborer, russian, orthodox, 2700, 0.8)
province:add_pop(entrepreneur, russian, orthodox, 100, 0.9)
province:add_nucleus(russia)
province:give_to(russia)

-- Change to Inner Alaska if taken by US or UK
province = Province:new{ ref_name = "vnutrennyaya_alyaska", color = rgb(212, 198, 255) }
province.name = _("Vnutrennyaya Alyaska")
province:register()
province:add_industry(wheat_farm, royal_russia_transport)
province:add_pop(artisan, russian, orthodox, 300, 0.7)
province:add_pop(farmer, russian, orthodox, 2700, 0.6)
province:add_pop(soldier, russian, orthodox, 800, 0.8)
province:add_pop(craftsmen, russian, orthodox, 700, 0.5)
province:add_pop(bureaucrat, russian, orthodox, 200, 0.7)
province:add_pop(aristocrat, russian, orthodox, 200, 0.9)
province:add_pop(clergymen, russian, orthodox, 500, 0.9)
province:add_pop(laborer, russian, orthodox, 2700, 0.8)
province:add_pop(entrepreneur, russian, orthodox, 100, 0.9)
province:add_nucleus(russia)
province:give_to(russia)

-- Change to Sitka if taken by US or UK
province = Province:new{ ref_name = "novoarkhangelsk", color = rgb(181, 232, 255) }
province.name = _("Novoarkhangelsk")
province:register()
province:add_industry(wheat_farm, royal_russia_transport)
province:add_pop(artisan, russian, orthodox, 300, 0.7)
province:add_pop(farmer, russian, orthodox, 2700, 0.6)
province:add_pop(soldier, russian, orthodox, 800, 0.8)
province:add_pop(craftsmen, russian, orthodox, 700, 0.5)
province:add_pop(bureaucrat, russian, orthodox, 200, 0.7)
province:add_pop(aristocrat, russian, orthodox, 200, 0.9)
province:add_pop(clergymen, russian, orthodox, 500, 0.9)
province:add_pop(laborer, russian, orthodox, 2700, 0.8)
province:add_pop(entrepreneur, russian, orthodox, 100, 0.9)
province:add_nucleus(russia)
province:give_to(russia)

-- Change to Kodiak if taken by US or UK
province = Province:new{ ref_name = "kad_yak", color = rgb(255, 173, 176) }
province.name = _("Kad'yak")
province:register()
province:add_industry(wheat_farm, royal_russia_transport)
province:add_pop(artisan, russian, orthodox, 300, 0.7)
province:add_pop(farmer, russian, orthodox, 2700, 0.6)
province:add_pop(soldier, russian, orthodox, 800, 0.8)
province:add_pop(craftsmen, russian, orthodox, 700, 0.5)
province:add_pop(bureaucrat, russian, orthodox, 200, 0.7)
province:add_pop(aristocrat, russian, orthodox, 200, 0.9)
province:add_pop(clergymen, russian, orthodox, 500, 0.9)
province:add_pop(laborer, russian, orthodox, 2700, 0.8)
province:add_pop(entrepreneur, russian, orthodox, 100, 0.9)
province:add_nucleus(russia)
province:give_to(russia)

-- Change to Big Diomede when take by the US or UK
province = Province:new{ ref_name = "bolshoy_diomida", color = rgb(255, 69, 66) }
province.name = _("Bolshoy Diomida")
province:register()
province:add_industry(wheat_farm, royal_russia_transport)
province:add_pop(artisan, russian, orthodox, 300, 0.7)
province:add_pop(farmer, russian, orthodox, 2700, 0.6)
province:add_pop(soldier, russian, orthodox, 800, 0.8)
province:add_pop(craftsmen, russian, orthodox, 700, 0.5)
province:add_pop(bureaucrat, russian, orthodox, 200, 0.7)
province:add_pop(aristocrat, russian, orthodox, 200, 0.9)
province:add_pop(clergymen, russian, orthodox, 500, 0.9)
province:add_pop(laborer, russian, orthodox, 2700, 0.8)
province:add_pop(entrepreneur, russian, orthodox, 100, 0.9)
province:add_nucleus(russia)
province:give_to(russia)

province = Province:new{ ref_name = "unalaska", color = rgb(211, 255, 213) }
province.name = _("Unalaska")
province:register()
province:add_industry(wheat_farm, royal_russia_transport)
province:add_pop(artisan, russian, orthodox, 300, 0.7)
province:add_pop(farmer, russian, orthodox, 2700, 0.6)
province:add_pop(soldier, russian, orthodox, 800, 0.8)
province:add_pop(craftsmen, russian, orthodox, 700, 0.5)
province:add_pop(bureaucrat, russian, orthodox, 200, 0.7)
province:add_pop(aristocrat, russian, orthodox, 200, 0.9)
province:add_pop(clergymen, russian, orthodox, 500, 0.9)
province:add_pop(laborer, russian, orthodox, 2700, 0.8)
province:add_pop(entrepreneur, russian, orthodox, 100, 0.9)
province:add_nucleus(russia)
province:give_to(russia)

-- Change to Little Diomede
province = Province:new{ ref_name = "malenkiy_diomid", color = rgb(137, 122, 255) }
province.name = _("Malenkiy Diomid")
province:register()
province:add_industry(wheat_farm, royal_russia_transport)
province:add_pop(artisan, russian, orthodox, 300, 0.7)
province:add_pop(farmer, russian, orthodox, 2700, 0.6)
province:add_pop(soldier, russian, orthodox, 800, 0.8)
province:add_pop(craftsmen, russian, orthodox, 700, 0.5)
province:add_pop(bureaucrat, russian, orthodox, 200, 0.7)
province:add_pop(aristocrat, russian, orthodox, 200, 0.9)
province:add_pop(clergymen, russian, orthodox, 500, 0.9)
province:add_pop(laborer, russian, orthodox, 2700, 0.8)
province:add_pop(entrepreneur, russian, orthodox, 100, 0.9)
province:add_nucleus(russia)
province:give_to(russia)

-- Change to Nunivak Island when US or UK gets it
province = Province:new{ ref_name = "nunivok", color = rgb(172, 155, 255) }
province.name = _("Nunivok")
province:register()
province:add_industry(wheat_farm, royal_russia_transport)
province:add_pop(artisan, russian, orthodox, 300, 0.7)
province:add_pop(farmer, russian, orthodox, 2700, 0.6)
province:add_pop(soldier, russian, orthodox, 800, 0.8)
province:add_pop(craftsmen, russian, orthodox, 700, 0.5)
province:add_pop(bureaucrat, russian, orthodox, 200, 0.7)
province:add_pop(aristocrat, russian, orthodox, 200, 0.9)
province:add_pop(clergymen, russian, orthodox, 500, 0.9)
province:add_pop(laborer, russian, orthodox, 2700, 0.8)
province:add_pop(entrepreneur, russian, orthodox, 100, 0.9)
province:add_nucleus(russia)
province:give_to(russia)

-- Change to Norton Sound when US or UK gets it
province = Province:new{ ref_name = "zaliv_norton", color = rgb(96, 255, 104) }
province.name = _("Zaliv Norton")
province:register()
province:add_industry(wheat_farm, royal_russia_transport)
province:add_pop(artisan, russian, orthodox, 300, 0.7)
province:add_pop(farmer, russian, orthodox, 2700, 0.6)
province:add_pop(soldier, russian, orthodox, 800, 0.8)
province:add_pop(craftsmen, russian, orthodox, 700, 0.5)
province:add_pop(bureaucrat, russian, orthodox, 200, 0.7)
province:add_pop(aristocrat, russian, orthodox, 200, 0.9)
province:add_pop(clergymen, russian, orthodox, 500, 0.9)
province:add_pop(laborer, russian, orthodox, 2700, 0.8)
province:add_pop(entrepreneur, russian, orthodox, 100, 0.9)
province:add_nucleus(russia)
province:give_to(russia)

province = Province:new{ ref_name = "alexandrovski", color = rgb(155, 211, 255) }
province.name = _("Alexandrovski")
province:register()
province:add_industry(wheat_farm, royal_russia_transport)
province:add_pop(artisan, russian, orthodox, 300, 0.7)
province:add_pop(farmer, russian, orthodox, 2700, 0.6)
province:add_pop(soldier, russian, orthodox, 800, 0.8)
province:add_pop(craftsmen, russian, orthodox, 700, 0.5)
province:add_pop(bureaucrat, russian, orthodox, 200, 0.7)
province:add_pop(aristocrat, russian, orthodox, 200, 0.9)
province:add_pop(clergymen, russian, orthodox, 500, 0.9)
province:add_pop(laborer, russian, orthodox, 2700, 0.8)
province:add_pop(entrepreneur, russian, orthodox, 100, 0.9)
province:add_nucleus(russia)
province:give_to(russia)

province = Province:new{ ref_name = "kenai", color = rgb(119, 248, 255) }
province.name = _("Kenai")
province:register()
province:add_industry(wheat_farm, royal_russia_transport)
province:add_pop(artisan, russian, orthodox, 300, 0.7)
province:add_pop(farmer, russian, orthodox, 2700, 0.6)
province:add_pop(soldier, russian, orthodox, 800, 0.8)
province:add_pop(craftsmen, russian, orthodox, 700, 0.5)
province:add_pop(bureaucrat, russian, orthodox, 200, 0.7)
province:add_pop(aristocrat, russian, orthodox, 200, 0.9)
province:add_pop(clergymen, russian, orthodox, 500, 0.9)
province:add_pop(laborer, russian, orthodox, 2700, 0.8)
province:add_pop(entrepreneur, russian, orthodox, 100, 0.9)
province:add_nucleus(russia)
province:give_to(russia)

-- Change to North Chugach when taken by US or UK
province = Province:new{ ref_name = "severnyy_chugach", color = rgb(255, 99, 174) }
province.name = _("Severnyy Chugach")
province:register()
province:add_industry(wheat_farm, royal_russia_transport)
province:add_pop(artisan, russian, orthodox, 300, 0.7)
province:add_pop(farmer, russian, orthodox, 2700, 0.6)
province:add_pop(soldier, russian, orthodox, 800, 0.8)
province:add_pop(craftsmen, russian, orthodox, 700, 0.5)
province:add_pop(bureaucrat, russian, orthodox, 200, 0.7)
province:add_pop(aristocrat, russian, orthodox, 200, 0.9)
province:add_pop(clergymen, russian, orthodox, 500, 0.9)
province:add_pop(laborer, russian, orthodox, 2700, 0.8)
province:add_pop(entrepreneur, russian, orthodox, 100, 0.9)
province:add_nucleus(russia)
province:give_to(russia)

-- Change to Hichinbrook Island when taken by US or UK
province = Province:new{ ref_name = "ostrov_nuchek", color = rgb(218, 145, 255) }
province.name = _("Ostrov Nuchek")
province:register()
province:add_industry(wheat_farm, royal_russia_transport)
province:add_pop(artisan, russian, orthodox, 300, 0.7)
province:add_pop(farmer, russian, orthodox, 2700, 0.6)
province:add_pop(soldier, russian, orthodox, 800, 0.8)
province:add_pop(craftsmen, russian, orthodox, 700, 0.5)
province:add_pop(bureaucrat, russian, orthodox, 200, 0.7)
province:add_pop(aristocrat, russian, orthodox, 200, 0.9)
province:add_pop(clergymen, russian, orthodox, 500, 0.9)
province:add_pop(laborer, russian, orthodox, 2700, 0.8)
province:add_pop(entrepreneur, russian, orthodox, 100, 0.9)
province:add_nucleus(russia)
province:give_to(russia)

-- Change to Alaska Peninsula when taken by US or UK
province = Province:new{ ref_name = "poluostrov_alyaska", color = rgb(255, 204, 243) }
province.name = _("Poluostrov Alyaska")
province:register()
province:add_industry(wheat_farm, royal_russia_transport)
province:add_pop(artisan, russian, orthodox, 300, 0.7)
province:add_pop(farmer, russian, orthodox, 2700, 0.6)
province:add_pop(soldier, russian, orthodox, 800, 0.8)
province:add_pop(craftsmen, russian, orthodox, 700, 0.5)
province:add_pop(bureaucrat, russian, orthodox, 200, 0.7)
province:add_pop(aristocrat, russian, orthodox, 200, 0.9)
province:add_pop(clergymen, russian, orthodox, 500, 0.9)
province:add_pop(laborer, russian, orthodox, 2700, 0.8)
province:add_pop(entrepreneur, russian, orthodox, 100, 0.9)
province:add_nucleus(russia)
province:give_to(russia)

-- Change to Fort Ross when taken by US
-- California!
province = Province:new{ ref_name = "krepost_ross", color = 0x77ff87 }
province.name = _("Krepostʹ Ross")
province:register()
province:add_industry(wheat_farm, royal_russia_transport)
province:add_pop(artisan, russian, orthodox, 300, 0.7)
province:add_pop(farmer, russian, orthodox, 2700, 0.6)
province:add_pop(soldier, russian, orthodox, 800, 0.8)
province:add_pop(craftsmen, russian, orthodox, 700, 0.5)
province:add_pop(bureaucrat, russian, orthodox, 200, 0.7)
province:add_pop(aristocrat, russian, orthodox, 200, 0.9)
province:add_pop(clergymen, russian, orthodox, 500, 0.9)
province:add_pop(laborer, russian, orthodox, 2700, 0.8)
province:add_pop(entrepreneur, russian, orthodox, 100, 0.9)
province:add_nucleus(russia)
province:give_to(russia)

province = Province:new{ ref_name = "yakutat", color = rgb(187, 168, 255) }
province.name = _("Yakutat")
province:register()
province:add_industry(wheat_farm, royal_russia_transport)
province:add_pop(artisan, russian, orthodox, 300, 0.7)
province:add_pop(farmer, russian, orthodox, 2700, 0.6)
province:add_pop(soldier, russian, orthodox, 800, 0.8)
province:add_pop(craftsmen, russian, orthodox, 700, 0.5)
province:add_pop(bureaucrat, russian, orthodox, 200, 0.7)
province:add_pop(aristocrat, russian, orthodox, 200, 0.9)
province:add_pop(clergymen, russian, orthodox, 500, 0.9)
province:add_pop(laborer, russian, orthodox, 2700, 0.8)
province:add_pop(entrepreneur, russian, orthodox, 100, 0.9)
province:add_nucleus(russia)
province:give_to(russia)
