--------------------------------------------------------------
-- Continent: America
-- Subcontinent: South America
-- Country: Brazil

local province = Province:new{ ref_name = "ceara", color = 0x00FFFF }
province.name = _("Ceará")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_industry(bakery, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "rio_grande_do_norte", color = 0xFF006E }
province.name = _("Rio Grande do Norte")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "paraiba", color = 0x4CFF00 }
province.name = _("Paraíba")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "pernambuco", color = 0x7F7F }
province.name = _("Pernambuco")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "alagoas", color = 0xB6FF00 }
province.name = _("Alagoas")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "sergipe", color = 0xFF6A00 }
province.name = _("Sergipe")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "bahia", color = 0xA0A0A0 }
province.name = _("Bahia")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "sao_francisco", color = 0xB200FF }
province.name = _("São Francisco")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "piaui", color = 0x49B0FF }
province.name = _("Piauí")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "maranhao", color = 0xC289FF }
province.name = _("Maranhão")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "grao_para", color = 0xFF6DDD }
province.name = _("Grão-Pará")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "oiapoque", color = 0x2ed500 }
province.name = _("Oiapoque")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "maraca", color = 0x939120 }
province.name = _("Maracá")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "roraima", color = 0xFFFD8E }
province.name = _("Roraima")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "mato_grosso", color = 0x9DFF35 }
province.name = _("Mato Grosso")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "goias", color = 0x49FF62 }
province.name = _("Goiás")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "minas_gerais", color = 0x9E0049 }
province.name = _("Minas Gerais")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "espirito_santo", color = 0x67639e }
province.name = _("Espirito Santo")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "sao_paulo", color = 0x7FFF8E }
province.name = _("São Paulo")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "rio_de_janeiro", color = 0x87639e }
province.name = _("Rio de Janeiro")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)
brazil:set_capital(province)

province = Province:new{ ref_name = "santa_catarina", color = 0xec1881 }
province.name = _("Santa Catarina")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "parana", color = 0xd1cc40 }
province.name = _("Paraná")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "oeste_catarinense", color = 0xFF26A4 }
province.name = _("Oeste Catarinense")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "porto_alegre", color = 0x96FFF8 }
province.name = _("Porto Alegre")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "bage", color = 0xD089FF }
province.name = _("Bagé")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "sao_borja", color = 0x6fa280 }
province.name = _("São Borja")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, brazilian, catholic, 5000, 0.7)
province:add_pop(farmer, brazilian, catholic, 5000, 0.1)
province:add_pop(soldier, brazilian, catholic, 5000, 0.2)
province:add_pop(craftsmen, brazilian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, brazilian, catholic, 5000, 0.7)
province:add_pop(aristocrat, brazilian, catholic, 5000, 0.2)
province:add_pop(clergymen, brazilian, catholic, 5000, 0.3)
province:add_pop(laborer, brazilian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, brazilian, catholic, 500, 0.9)
province:add_pop(slave, brazilian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:give_to(brazil)

province = Province:new{ ref_name = "cisplatina", color = 0xFFEA84 }
province.name = _("Cisplatina")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, cisplatinian, catholic, 5000, 0.7)
province:add_pop(farmer, cisplatinian, catholic, 5000, 0.1)
province:add_pop(soldier, cisplatinian, catholic, 5000, 0.2)
province:add_pop(craftsmen, cisplatinian, catholic, 5000, 0.2)
province:add_pop(bureaucrat, cisplatinian, catholic, 5000, 0.7)
province:add_pop(aristocrat, cisplatinian, catholic, 5000, 0.2)
province:add_pop(clergymen, cisplatinian, catholic, 5000, 0.3)
province:add_pop(laborer, cisplatinian, catholic, 5000, 0.2)
province:add_pop(entrepreneur, cisplatinian, catholic, 500, 0.9)
province:add_pop(slave, cisplatinian, catholic, 500, 0.5)
province:add_nucleus(brazil)
province:add_nucleus(argentina)
province:give_to(brazil)

--------------------------------------------------------------
-- Continent: Americas
-- Subcontinent: South America
-- Country: Paraguay

province = Province:new{ ref_name = "asuncion", color = 0x00C7FF }
province.name = _("Asunción")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, paraguayan, catholic, 5000, 0.7)
province:add_pop(farmer, paraguayan, catholic, 5000, 0.1)
province:add_pop(soldier, paraguayan, catholic, 5000, 0.2)
province:add_pop(craftsmen, paraguayan, catholic, 5000, 0.2)
province:add_pop(bureaucrat, paraguayan, catholic, 5000, 0.7)
province:add_pop(aristocrat, paraguayan, catholic, 5000, 0.2)
province:add_pop(clergymen, paraguayan, catholic, 5000, 0.3)
province:add_pop(laborer, paraguayan, catholic, 5000, 0.2)
province:add_pop(entrepreneur, paraguayan, catholic, 500, 0.9)
province:add_pop(slave, paraguayan, catholic, 500, 0.5)
province:add_nucleus(paraguay)
province:give_to(paraguay)
paraguay:set_capital(province)

province = Province:new{ ref_name = "vila_sacaron", color = 0xB71CFF }
province.name = _("Vila Sacarón")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, paraguayan, catholic, 5000, 0.7)
province:add_pop(farmer, paraguayan, catholic, 5000, 0.1)
province:add_pop(soldier, paraguayan, catholic, 5000, 0.2)
province:add_pop(craftsmen, paraguayan, catholic, 5000, 0.2)
province:add_pop(bureaucrat, paraguayan, catholic, 5000, 0.7)
province:add_pop(aristocrat, paraguayan, catholic, 5000, 0.2)
province:add_pop(clergymen, paraguayan, catholic, 5000, 0.3)
province:add_pop(laborer, paraguayan, catholic, 5000, 0.2)
province:add_pop(entrepreneur, paraguayan, catholic, 500, 0.9)
province:add_pop(slave, paraguayan, catholic, 500, 0.5)
province:add_nucleus(paraguay)
province:give_to(paraguay)

province = Province:new{ ref_name = "nioaque", color = 0x5174FF }
province.name = _("Nioaque")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, paraguayan, catholic, 5000, 0.7)
province:add_pop(farmer, paraguayan, catholic, 5000, 0.1)
province:add_pop(soldier, paraguayan, catholic, 5000, 0.2)
province:add_pop(craftsmen, paraguayan, catholic, 5000, 0.2)
province:add_pop(bureaucrat, paraguayan, catholic, 5000, 0.7)
province:add_pop(aristocrat, paraguayan, catholic, 5000, 0.2)
province:add_pop(clergymen, paraguayan, catholic, 5000, 0.3)
province:add_pop(laborer, paraguayan, catholic, 5000, 0.2)
province:add_pop(entrepreneur, paraguayan, catholic, 500, 0.9)
province:add_pop(slave, paraguayan, catholic, 500, 0.5)
province:add_nucleus(paraguay)
province:give_to(paraguay)

--------------------------------------------------------------
-- Continent: Americas
-- Subcontinent: South America
-- Country: Bolivia + Chaco

province = Province:new{ ref_name = "pando", color = 0x47FBFF }
province.name = _("Pando")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, german, catholic, 5000, 0.7)
province:add_pop(farmer, german, catholic, 5000, 0.1)
province:add_pop(soldier, german, catholic, 5000, 0.2)
province:add_pop(craftsmen, german, catholic, 5000, 0.2)
province:add_pop(bureaucrat, german, catholic, 5000, 0.7)
province:add_pop(aristocrat, german, catholic, 5000, 0.2)
province:add_pop(clergymen, german, catholic, 5000, 0.3)
province:add_pop(laborer, german, catholic, 5000, 0.2)
province:add_pop(entrepreneur, german, catholic, 500, 0.9)
province:add_pop(slave, german, catholic, 500, 0.5)
province:add_nucleus(bolivia)
province:give_to(bolivia)

province = Province:new{ ref_name = "santa_cruz", color = 0xFFC4EE }
province.name = _("Santa Cruz")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, german, catholic, 5000, 0.7)
province:add_pop(farmer, german, catholic, 5000, 0.1)
province:add_pop(soldier, german, catholic, 5000, 0.2)
province:add_pop(craftsmen, german, catholic, 5000, 0.2)
province:add_pop(bureaucrat, german, catholic, 5000, 0.7)
province:add_pop(aristocrat, german, catholic, 5000, 0.2)
province:add_pop(clergymen, german, catholic, 5000, 0.3)
province:add_pop(laborer, german, catholic, 5000, 0.2)
province:add_pop(entrepreneur, german, catholic, 500, 0.9)
province:add_pop(slave, german, catholic, 500, 0.5)
province:add_nucleus(bolivia)
province:give_to(bolivia)
bolivia:set_capital(province)

province = Province:new{ ref_name = "carvoal", color = 0xFF8168 }
province.name = _("Carvoal")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, german, catholic, 5000, 0.7)
province:add_pop(farmer, german, catholic, 5000, 0.1)
province:add_pop(soldier, german, catholic, 5000, 0.2)
province:add_pop(craftsmen, german, catholic, 5000, 0.2)
province:add_pop(bureaucrat, german, catholic, 5000, 0.7)
province:add_pop(aristocrat, german, catholic, 5000, 0.2)
province:add_pop(clergymen, german, catholic, 5000, 0.3)
province:add_pop(laborer, german, catholic, 5000, 0.2)
province:add_pop(entrepreneur, german, catholic, 500, 0.9)
province:add_pop(slave, german, catholic, 500, 0.5)
province:add_nucleus(bolivia)
province:give_to(bolivia)

province = Province:new{ ref_name = "corumba", color = 0x8CFBFF }
province.name = _("Corumbá")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, german, catholic, 5000, 0.7)
province:add_pop(farmer, german, catholic, 5000, 0.1)
province:add_pop(soldier, german, catholic, 5000, 0.2)
province:add_pop(craftsmen, german, catholic, 5000, 0.2)
province:add_pop(bureaucrat, german, catholic, 5000, 0.7)
province:add_pop(aristocrat, german, catholic, 5000, 0.2)
province:add_pop(clergymen, german, catholic, 5000, 0.3)
province:add_pop(laborer, german, catholic, 5000, 0.2)
province:add_pop(entrepreneur, german, catholic, 500, 0.9)
province:add_pop(slave, german, catholic, 500, 0.5)
province:add_nucleus(bolivia)
province:give_to(bolivia)

province = Province:new{ ref_name = "santissima_trinidade", color = 0x5E1EFF }
province.name = _("Santíssima Trinidade")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, german, catholic, 5000, 0.7)
province:add_pop(farmer, german, catholic, 5000, 0.1)
province:add_pop(soldier, german, catholic, 5000, 0.2)
province:add_pop(craftsmen, german, catholic, 5000, 0.2)
province:add_pop(bureaucrat, german, catholic, 5000, 0.7)
province:add_pop(aristocrat, german, catholic, 5000, 0.2)
province:add_pop(clergymen, german, catholic, 5000, 0.3)
province:add_pop(laborer, german, catholic, 5000, 0.2)
province:add_pop(entrepreneur, german, catholic, 500, 0.9)
province:add_pop(slave, german, catholic, 500, 0.5)
province:add_nucleus(bolivia)
province:give_to(bolivia)

province = Province:new{ ref_name = "fuerte_olimpo", color = 0x6f6071 }
province.name = _("Fuerte Olimpo")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, german, catholic, 5000, 0.7)
province:add_pop(farmer, german, catholic, 5000, 0.1)
province:add_pop(soldier, german, catholic, 5000, 0.2)
province:add_pop(craftsmen, german, catholic, 5000, 0.2)
province:add_pop(bureaucrat, german, catholic, 5000, 0.7)
province:add_pop(aristocrat, german, catholic, 5000, 0.2)
province:add_pop(clergymen, german, catholic, 5000, 0.3)
province:add_pop(laborer, german, catholic, 5000, 0.2)
province:add_pop(entrepreneur, german, catholic, 500, 0.9)
province:add_pop(slave, german, catholic, 500, 0.5)
province:add_nucleus(bolivia)

province = Province:new{ ref_name = "nueva_burdeos", color = 0xFFD149 }
province.name = _("Nueva Burdeos")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, german, catholic, 5000, 0.7)
province:add_pop(farmer, german, catholic, 5000, 0.1)
province:add_pop(soldier, german, catholic, 5000, 0.2)
province:add_pop(craftsmen, german, catholic, 5000, 0.2)
province:add_pop(bureaucrat, german, catholic, 5000, 0.7)
province:add_pop(aristocrat, german, catholic, 5000, 0.2)
province:add_pop(clergymen, german, catholic, 5000, 0.3)
province:add_pop(laborer, german, catholic, 5000, 0.2)
province:add_pop(entrepreneur, german, catholic, 500, 0.9)
province:add_pop(slave, german, catholic, 500, 0.5)
province:add_nucleus(bolivia)
province:add_nucleus(paraguay)

province = Province:new{ ref_name = "la_paz", color = 0xFF2158 }
province.name = _("La Paz")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, german, catholic, 5000, 0.7)
province:add_pop(farmer, german, catholic, 5000, 0.1)
province:add_pop(soldier, german, catholic, 5000, 0.2)
province:add_pop(craftsmen, german, catholic, 5000, 0.2)
province:add_pop(bureaucrat, german, catholic, 5000, 0.7)
province:add_pop(aristocrat, german, catholic, 5000, 0.2)
province:add_pop(clergymen, german, catholic, 5000, 0.3)
province:add_pop(laborer, german, catholic, 5000, 0.2)
province:add_pop(entrepreneur, german, catholic, 500, 0.9)
province:add_pop(slave, german, catholic, 500, 0.5)
province:add_nucleus(bolivia)
province:give_to(bolivia)

province = Province:new{ ref_name = "cochabamba", color = 0xCB3FFF }
province.name = _("Cochabamba")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, german, catholic, 5000, 0.7)
province:add_pop(farmer, german, catholic, 5000, 0.1)
province:add_pop(soldier, german, catholic, 5000, 0.2)
province:add_pop(craftsmen, german, catholic, 5000, 0.2)
province:add_pop(bureaucrat, german, catholic, 5000, 0.7)
province:add_pop(aristocrat, german, catholic, 5000, 0.2)
province:add_pop(clergymen, german, catholic, 5000, 0.3)
province:add_pop(laborer, german, catholic, 5000, 0.2)
province:add_pop(entrepreneur, german, catholic, 500, 0.9)
province:add_pop(slave, german, catholic, 500, 0.5)
province:add_nucleus(bolivia)
province:give_to(bolivia)

province = Province:new{ ref_name = "oruro", color = 0x75FFCC }
province.name = _("Oruro")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, german, catholic, 5000, 0.7)
province:add_pop(farmer, german, catholic, 5000, 0.1)
province:add_pop(soldier, german, catholic, 5000, 0.2)
province:add_pop(craftsmen, german, catholic, 5000, 0.2)
province:add_pop(bureaucrat, german, catholic, 5000, 0.7)
province:add_pop(aristocrat, german, catholic, 5000, 0.2)
province:add_pop(clergymen, german, catholic, 5000, 0.3)
province:add_pop(laborer, german, catholic, 5000, 0.2)
province:add_pop(entrepreneur, german, catholic, 500, 0.9)
province:add_pop(slave, german, catholic, 500, 0.5)
province:add_nucleus(bolivia)
province:give_to(bolivia)

province = Province:new{ ref_name = "potosi", color = 0xFC63FF }
province.name = _("Potosí")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, german, catholic, 5000, 0.7)
province:add_pop(farmer, german, catholic, 5000, 0.1)
province:add_pop(soldier, german, catholic, 5000, 0.2)
province:add_pop(craftsmen, german, catholic, 5000, 0.2)
province:add_pop(bureaucrat, german, catholic, 5000, 0.7)
province:add_pop(aristocrat, german, catholic, 5000, 0.2)
province:add_pop(clergymen, german, catholic, 5000, 0.3)
province:add_pop(laborer, german, catholic, 5000, 0.2)
province:add_pop(entrepreneur, german, catholic, 500, 0.9)
province:add_pop(slave, german, catholic, 500, 0.5)
province:add_nucleus(bolivia)
province:give_to(bolivia)

province = Province:new{ ref_name = "chuquisaca", color = 0x4FA7FF }
province.name = _("Chuquisaca")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, german, catholic, 5000, 0.7)
province:add_pop(farmer, german, catholic, 5000, 0.1)
province:add_pop(soldier, german, catholic, 5000, 0.2)
province:add_pop(craftsmen, german, catholic, 5000, 0.2)
province:add_pop(bureaucrat, german, catholic, 5000, 0.7)
province:add_pop(aristocrat, german, catholic, 5000, 0.2)
province:add_pop(clergymen, german, catholic, 5000, 0.3)
province:add_pop(laborer, german, catholic, 5000, 0.2)
province:add_pop(entrepreneur, german, catholic, 500, 0.9)
province:add_pop(slave, german, catholic, 500, 0.5)
province:add_nucleus(bolivia)
province:give_to(bolivia)

province = Province:new{ ref_name = "tarija", color = 0x907CFF }
province.name = _("Tarija")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, german, catholic, 5000, 0.7)
province:add_pop(farmer, german, catholic, 5000, 0.1)
province:add_pop(soldier, german, catholic, 5000, 0.2)
province:add_pop(craftsmen, german, catholic, 5000, 0.2)
province:add_pop(bureaucrat, german, catholic, 5000, 0.7)
province:add_pop(aristocrat, german, catholic, 5000, 0.2)
province:add_pop(clergymen, german, catholic, 5000, 0.3)
province:add_pop(laborer, german, catholic, 5000, 0.2)
province:add_pop(entrepreneur, german, catholic, 500, 0.9)
province:add_pop(slave, german, catholic, 500, 0.5)
province:add_nucleus(bolivia)
province:give_to(bolivia)
