--------------------------------------------------------------
-- Continent: Americas
-- Subcontinent: North America
-- Country: The British Empire (Canada + bermuda)
province = Province:new{ ref_name = "inner_baffin", color = rgb(236, 153, 255) }
province.name = _("Inner Baffin")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)

province = Province:new{ ref_name = "outer_baffin", color = rgb(175, 255, 219) }
province.name = _("Outer Baffin")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)
province:give_to(united_kingdom)

province = Province:new{ ref_name = "arctic_islands", color = rgb(214, 206, 255) }
province.name = _("Arctic Islands")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)

province = Province:new{ ref_name = "north_yukon", color = rgb(255, 66, 198) }
province.name = _("North Yukon")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)

province = Province:new{ ref_name = "south_yukon", color = rgb(86, 246, 255) }
province.name = _("South Yukon")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)

province = Province:new{ ref_name = "fort_resolution", color = rgb(255, 253, 181) }
province.name = _("Fort Resolution")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)

province = Province:new{ ref_name = "southern_arctic", color = rgb(255, 84, 137) }
province.name = _("Southern Arctic")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)

province = Province:new{ ref_name = "rankin_inlet", color = rgb(142, 176, 255) }
province.name = _("Rankin Inlet")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)

province = Province:new{ ref_name = "eastern_northwestern_territories", color = rgb(255, 162, 155) }
province.name = _("Eastern Northwestern Territories")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)

province = Province:new{ ref_name = "hudson_bay_islands", color = rgb(255, 71, 255) }
province.name = _("Hudson Bay Islands")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)

province = Province:new{ ref_name = "north_quebec", color = rgb(188, 112, 255) }
province.name = _("North Quebec")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)

province = Province:new{ ref_name = "south_quebec", color = rgb(255, 95, 84) }
province.name = _("South Quebec")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)
province:give_to(united_kingdom)

province = Province:new{ ref_name = "labrador", color = rgb(168, 237, 255) }
province.name = _("Labrador")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)
province:give_to(united_kingdom)

province = Province:new{ ref_name = "newfoundland", color = rgb(91, 255, 148) }
province.name = _("Newfoundland")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)
province:give_to(united_kingdom)

province = Province:new{ ref_name = "prince_edward_island", color = rgb(104, 174, 255) }
province.name = _("Prince Edward Island")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)
province:give_to(united_kingdom)

province = Province:new{ ref_name = "nova_scotia", color = rgb(196, 255, 225) }
province.name = _("Nova Scotia")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)
province:give_to(united_kingdom)

province = Province:new{ ref_name = "new_brunswick", color = rgb(153, 99, 255) }
province.name = _("New Brunswick")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)
province:give_to(united_kingdom)

province = Province:new{ ref_name = "temiscouata", color = rgb(255, 126, 119) }
province.name = _("Temiscouata")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)
province:give_to(united_kingdom)

province = Province:new{ ref_name = "madawaska", color = rgb(204, 255, 228) }
province.name = _("Madawaska")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)
province:give_to(united_kingdom)

province = Province:new{ ref_name = "ontario", color = rgb(255, 124, 153) }
province.name = _("Ontario")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)
province:give_to(united_kingdom)

province = Province:new{ ref_name = "north_ontario", color = rgb(142, 182, 255) }
province.name = _("North Ontario")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)

province = Province:new{ ref_name = "thunder_bay", color = rgb(211, 255, 240) }
province.name = _("Thunder Bay")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)
province:give_to(united_kingdom)

province = Province:new{ ref_name = "kenora", color = rgb(255, 99, 231) }
province.name = _("Kenora")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)
province:give_to(united_kingdom)

province = Province:new{ ref_name = "port_nelson", color = rgb(114, 255, 252) }
province.name = _("Port Nelson")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)

province = Province:new{ ref_name = "winnipeg", color = rgb(255, 138, 130) }
province.name = _("Winnipeg")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)

province = Province:new{ ref_name = "athabasca", color = rgb(255, 252, 130) }
province.name = _("Athabasca")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)

-- Change name to Saskatchewan after 1905
province = Province:new{ ref_name = "eastern_prairies", color = rgb(142, 204, 255) }
province.name = _("Eastern Prairies")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)

province = Province:new{ ref_name = "western_prairies", color = rgb(177, 114, 255) }
province.name = _("Western Prairies")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)

province = Province:new{ ref_name = "boreal_plains", color = rgb(255, 66, 85) }
province.name = _("Boreal Plains")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)

province = Province:new{ ref_name = "northern_canadian_rockies", color = rgb(102, 203, 255) }
province.name = _("Northern Canadian Rockies")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)

province = Province:new{ ref_name = "southern_canadian_rockies", color = rgb(255, 94, 230) }
province.name = _("Southern Canadian Rockies")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)
province:give_to(united_kingdom)

province = Province:new{ ref_name = "north_vancouver", color = rgb(137, 233, 255) }
province.name = _("North Vancouver")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)
province:give_to(united_kingdom)

province = Province:new{ ref_name = "south_vancouver", color = 0xffb5a0 }
province.name = _("South Vancouver")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)
province:give_to(united_kingdom)

province = Province:new{ ref_name = "queen_charlotte_islands", color = rgb(255, 168, 253) }
province.name = _("Queen Charlotte Islands")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)
province:give_to(united_kingdom)

province = Province:new{ ref_name = "bermuda", color = rgb(232, 61, 255) }
province.name = _("Bermuda")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(burgeoise, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(burgeoise, british, protestant, 100, 0.9)
province:add_pop(artisan, american, protestant, 300, 0.7)
province:add_pop(farmer, american, protestant, 2700, 0.6)
province:add_pop(soldier, american, protestant, 800, 0.8)
province:add_pop(craftsmen, american, protestant, 700, 0.5)
province:add_pop(bureaucrat, american, protestant, 200, 0.7)
province:add_pop(burgeoise, american, protestant, 200, 0.9)
province:add_pop(clergymen, american, protestant, 500, 0.9)
province:add_pop(laborer, american, protestant, 2700, 0.8)
province:add_pop(burgeoise, american, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)
province:give_to(united_kingdom)