--------------------------------------------------------------
-- Continent: Americas
-- Subcontinent: South America
-- Country: Chile + Patagonian Chile + Ex-Bolivian territory

province = Province:new{ ref_name = "iquique", color = 0xFF7856 }
province.name = _("Iquique")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, chilean, catholic, 500, 0.7)
province:add_pop(farmer, chilean, catholic, 5000, 0.1)
province:add_pop(soldier, chilean, catholic, 500, 0.2)
province:add_pop(craftsmen, chilean, catholic, 500, 0.2)
province:add_pop(bureaucrat, chilean, catholic, 500, 0.7)
province:add_pop(aristocrat, chilean, catholic, 500, 0.2)
province:add_pop(clergymen, chilean, catholic, 500, 0.3)
province:add_pop(laborer, chilean, catholic, 500, 0.2)
province:add_pop(entrepreneur, chilean, catholic, 500, 0.9)
province:add_nucleus(chile)
province:add_nucleus(bolivia)
province:give_to(bolivia)

province = Province:new{ ref_name = "calama", color = 0x5157FF }
province.name = _("Calama")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, chilean, catholic, 500, 0.7)
province:add_pop(farmer, chilean, catholic, 5000, 0.1)
province:add_pop(soldier, chilean, catholic, 500, 0.2)
province:add_pop(craftsmen, chilean, catholic, 500, 0.2)
province:add_pop(bureaucrat, chilean, catholic, 500, 0.7)
province:add_pop(aristocrat, chilean, catholic, 500, 0.2)
province:add_pop(clergymen, chilean, catholic, 500, 0.3)
province:add_pop(laborer, chilean, catholic, 500, 0.2)
province:add_pop(entrepreneur, chilean, catholic, 500, 0.9)
province:add_nucleus(chile)
province:add_nucleus(bolivia)
province:give_to(bolivia)

province = Province:new{ ref_name = "antofagasta", color = 0xF2FFD8 }
province.name = _("Antofagasta")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, chilean, catholic, 500, 0.7)
province:add_pop(farmer, chilean, catholic, 5000, 0.1)
province:add_pop(soldier, chilean, catholic, 500, 0.2)
province:add_pop(craftsmen, chilean, catholic, 500, 0.2)
province:add_pop(bureaucrat, chilean, catholic, 500, 0.7)
province:add_pop(aristocrat, chilean, catholic, 500, 0.2)
province:add_pop(clergymen, chilean, catholic, 500, 0.3)
province:add_pop(laborer, chilean, catholic, 500, 0.2)
province:add_pop(entrepreneur, chilean, catholic, 500, 0.9)
province:add_nucleus(chile)
province:add_nucleus(bolivia)
province:give_to(chile)

province = Province:new{ ref_name = "copiapo", color = 0x9849FF }
province.name = _("Copiapó")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, chilean, catholic, 500, 0.7)
province:add_pop(farmer, chilean, catholic, 5000, 0.1)
province:add_pop(soldier, chilean, catholic, 500, 0.2)
province:add_pop(craftsmen, chilean, catholic, 500, 0.2)
province:add_pop(bureaucrat, chilean, catholic, 500, 0.7)
province:add_pop(aristocrat, chilean, catholic, 500, 0.2)
province:add_pop(clergymen, chilean, catholic, 500, 0.3)
province:add_pop(laborer, chilean, catholic, 500, 0.2)
province:add_pop(entrepreneur, chilean, catholic, 500, 0.9)
province:add_nucleus(chile)
province:give_to(chile)

province = Province:new{ ref_name = "coquimbo", color = 0x8C4FFF }
province.name = _("Coquimbo")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, chilean, catholic, 500, 0.7)
province:add_pop(farmer, chilean, catholic, 5000, 0.1)
province:add_pop(soldier, chilean, catholic, 500, 0.2)
province:add_pop(craftsmen, chilean, catholic, 500, 0.2)
province:add_pop(bureaucrat, chilean, catholic, 500, 0.7)
province:add_pop(aristocrat, chilean, catholic, 500, 0.2)
province:add_pop(clergymen, chilean, catholic, 500, 0.3)
province:add_pop(laborer, chilean, catholic, 500, 0.2)
province:add_pop(entrepreneur, chilean, catholic, 500, 0.9)
province:add_nucleus(chile)
province:give_to(chile)

province = Province:new{ ref_name = "illapel", color = 0x49F5FF }
province.name = _("Illapel")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, chilean, catholic, 500, 0.7)
province:add_pop(farmer, chilean, catholic, 5000, 0.1)
province:add_pop(soldier, chilean, catholic, 500, 0.2)
province:add_pop(craftsmen, chilean, catholic, 500, 0.2)
province:add_pop(bureaucrat, chilean, catholic, 500, 0.7)
province:add_pop(aristocrat, chilean, catholic, 500, 0.2)
province:add_pop(clergymen, chilean, catholic, 500, 0.3)
province:add_pop(laborer, chilean, catholic, 500, 0.2)
province:add_pop(entrepreneur, chilean, catholic, 500, 0.9)
province:add_nucleus(chile)
province:give_to(chile)

province = Province:new{ ref_name = "santiago", color = 0xCB23FF }
province.name = _("Santiago")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, chilean, catholic, 5000, 0.7)
province:add_pop(farmer, chilean, catholic, 25000, 0.1)
province:add_pop(soldier, chilean, catholic, 5000, 0.2)
province:add_pop(craftsmen, chilean, catholic, 5000, 0.2)
province:add_pop(bureaucrat, chilean, catholic, 5000, 0.7)
province:add_pop(aristocrat, chilean, catholic, 5000, 0.2)
province:add_pop(clergymen, chilean, catholic, 5000, 0.3)
province:add_pop(laborer, chilean, catholic, 5000, 0.2)
province:add_pop(entrepreneur, chilean, catholic, 500, 0.9)
province:add_nucleus(chile)
province:give_to(chile)
Nation:set_capital(chile, province)

province = Province:new{ ref_name = "curico", color = 0xFFE5C1 }
province.name = _("Curicó")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, chilean, catholic, 500, 0.7)
province:add_pop(farmer, chilean, catholic, 5000, 0.1)
province:add_pop(soldier, chilean, catholic, 500, 0.2)
province:add_pop(craftsmen, chilean, catholic, 500, 0.2)
province:add_pop(bureaucrat, chilean, catholic, 500, 0.7)
province:add_pop(aristocrat, chilean, catholic, 500, 0.2)
province:add_pop(clergymen, chilean, catholic, 500, 0.3)
province:add_pop(laborer, chilean, catholic, 500, 0.2)
province:add_pop(entrepreneur, chilean, catholic, 500, 0.9)
province:add_nucleus(chile)
province:give_to(chile)

province = Province:new{ ref_name = "chillan", color = 0x1691FF }
province.name = _("Chillán")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, chilean, catholic, 500, 0.7)
province:add_pop(farmer, chilean, catholic, 5000, 0.1)
province:add_pop(soldier, chilean, catholic, 500, 0.2)
province:add_pop(craftsmen, chilean, catholic, 500, 0.2)
province:add_pop(bureaucrat, chilean, catholic, 500, 0.7)
province:add_pop(aristocrat, chilean, catholic, 500, 0.2)
province:add_pop(clergymen, chilean, catholic, 500, 0.3)
province:add_pop(laborer, chilean, catholic, 500, 0.2)
province:add_pop(entrepreneur, chilean, catholic, 500, 0.9)
province:add_nucleus(chile)
province:give_to(chile)

province = Province:new{ ref_name = "concepcion", color = 0xFF4D3D }
province.name = _("Concepción")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, chilean, catholic, 500, 0.7)
province:add_pop(farmer, chilean, catholic, 5000, 0.1)
province:add_pop(soldier, chilean, catholic, 500, 0.2)
province:add_pop(craftsmen, chilean, catholic, 500, 0.2)
province:add_pop(bureaucrat, chilean, catholic, 500, 0.7)
province:add_pop(aristocrat, chilean, catholic, 500, 0.2)
province:add_pop(clergymen, chilean, catholic, 500, 0.3)
province:add_pop(laborer, chilean, catholic, 500, 0.2)
province:add_pop(entrepreneur, chilean, catholic, 500, 0.9)
province:add_nucleus(chile)
province:give_to(chile)

province = Province:new{ ref_name = "valdivia", color = 0xA2FF00 }
province.name = _("Valdivia")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mapuche, animist, 500, 0.7)
province:add_pop(farmer, mapuche, animist, 5000, 0.1)
province:add_pop(soldier, mapuche, animist, 500, 0.2)
province:add_pop(craftsmen, mapuche, animist, 500, 0.2)
province:add_pop(bureaucrat, mapuche, animist, 500, 0.7)
province:add_pop(aristocrat, mapuche, animist, 500, 0.2)
province:add_pop(clergymen, mapuche, animist, 500, 0.3)
province:add_pop(laborer, mapuche, animist, 500, 0.2)
province:add_nucleus(chile)

province = Province:new{ ref_name = "osorno", color = 0xFFE554 }
province.name = _("Osorno")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mapuche, animist, 500, 0.7)
province:add_pop(farmer, mapuche, animist, 5000, 0.1)
province:add_pop(soldier, mapuche, animist, 500, 0.2)
province:add_pop(craftsmen, mapuche, animist, 500, 0.2)
province:add_pop(bureaucrat, mapuche, animist, 500, 0.7)
province:add_pop(aristocrat, mapuche, animist, 500, 0.2)
province:add_pop(clergymen, mapuche, animist, 500, 0.3)
province:add_pop(laborer, mapuche, animist, 500, 0.2)
province:add_nucleus(chile)

province = Province:new{ ref_name = "chiloe", color = 0xFF00E5 }
province.name = _("Chiloé")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mapuche, animist, 500, 0.7)
province:add_pop(farmer, mapuche, animist, 5000, 0.1)
province:add_pop(soldier, mapuche, animist, 500, 0.2)
province:add_pop(craftsmen, mapuche, animist, 500, 0.2)
province:add_pop(bureaucrat, mapuche, animist, 500, 0.7)
province:add_pop(aristocrat, mapuche, animist, 500, 0.2)
province:add_pop(clergymen, mapuche, animist, 500, 0.3)
province:add_pop(laborer, mapuche, animist, 500, 0.2)
province:add_nucleus(chile)

province = Province:new{ ref_name = "aysen", color = 0x0090FF }
province.name = _("Aysén")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mapuche, animist, 500, 0.7)
province:add_pop(farmer, mapuche, animist, 5000, 0.1)
province:add_pop(soldier, mapuche, animist, 500, 0.2)
province:add_pop(craftsmen, mapuche, animist, 500, 0.2)
province:add_pop(bureaucrat, mapuche, animist, 500, 0.7)
province:add_pop(aristocrat, mapuche, animist, 500, 0.2)
province:add_pop(clergymen, mapuche, animist, 500, 0.3)
province:add_pop(laborer, mapuche, animist, 500, 0.2)
province:add_nucleus(chile)

province = Province:new{ ref_name = "punta_arenas", color = 0x3F3B39 }
province.name = _("Punta Arenas")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mapuche, animist, 500, 0.7)
province:add_pop(farmer, mapuche, animist, 5000, 0.1)
province:add_pop(soldier, mapuche, animist, 500, 0.2)
province:add_pop(craftsmen, mapuche, animist, 500, 0.2)
province:add_pop(bureaucrat, mapuche, animist, 500, 0.7)
province:add_pop(aristocrat, mapuche, animist, 500, 0.2)
province:add_pop(clergymen, mapuche, animist, 500, 0.3)
province:add_pop(laborer, mapuche, animist, 500, 0.2)
province:add_nucleus(chile)
province:add_nucleus(argentina)

province = Province:new{ ref_name = "san_gregorio", color = 0xFFD800 }
province.name = _("San Gregorio")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mapuche, animist, 500, 0.7)
province:add_pop(farmer, mapuche, animist, 5000, 0.1)
province:add_pop(soldier, mapuche, animist, 500, 0.2)
province:add_pop(craftsmen, mapuche, animist, 500, 0.2)
province:add_pop(bureaucrat, mapuche, animist, 500, 0.7)
province:add_pop(aristocrat, mapuche, animist, 500, 0.2)
province:add_pop(clergymen, mapuche, animist, 500, 0.3)
province:add_pop(laborer, mapuche, animist, 500, 0.2)
province:add_nucleus(chile)
province:add_nucleus(argentina)

province = Province:new{ ref_name = "puerto_porvenir", color = 0x0f145d }
province.name = _("Puerto Porvenir")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mapuche, animist, 500, 0.7)
province:add_pop(farmer, mapuche, animist, 5000, 0.1)
province:add_pop(soldier, mapuche, animist, 500, 0.2)
province:add_pop(craftsmen, mapuche, animist, 500, 0.2)
province:add_pop(bureaucrat, mapuche, animist, 500, 0.7)
province:add_pop(aristocrat, mapuche, animist, 500, 0.2)
province:add_pop(clergymen, mapuche, animist, 500, 0.3)
province:add_pop(laborer, mapuche, animist, 500, 0.2)
province:add_nucleus(chile)
province:add_nucleus(argentina)

province = Province:new{ ref_name = "los_rios", color = 0xb6ff50 }
province.name = _("Los Rios")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mapuche, animist, 500, 0.7)
province:add_pop(farmer, mapuche, animist, 5000, 0.1)
province:add_pop(soldier, mapuche, animist, 500, 0.2)
province:add_pop(craftsmen, mapuche, animist, 500, 0.2)
province:add_pop(bureaucrat, mapuche, animist, 500, 0.7)
province:add_pop(aristocrat, mapuche, animist, 500, 0.2)
province:add_pop(clergymen, mapuche, animist, 500, 0.3)
province:add_pop(laborer, mapuche, animist, 500, 0.2)
province:add_nucleus(chile)
province:add_nucleus(argentina)

--------------------------------------------------------------
-- Continent: Americas
-- Subcontinent: South America
-- Country: United Kingdom
province = Province:new{ ref_name = "falkland_islands", color = 0x078689 }
province.name = _("Falkland Islands")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, british, protestant, 300, 0.7)
province:add_pop(farmer, british, protestant, 2700, 0.6)
province:add_pop(soldier, british, protestant, 800, 0.8)
province:add_pop(craftsmen, british, protestant, 700, 0.5)
province:add_pop(bureaucrat, british, protestant, 200, 0.7)
province:add_pop(aristocrat, british, protestant, 200, 0.9)
province:add_pop(clergymen, british, protestant, 500, 0.9)
province:add_pop(laborer, british, protestant, 2700, 0.8)
province:add_pop(entrepreneur, british, protestant, 100, 0.9)
province:add_nucleus(united_kingdom)
province:give_to(united_kingdom)
