--------------------------------------------------------------
-- Continent: America
-- Subcontinent: North America
-- Country: Mexico

province = Province:new{ ref_name = "yucatan", color = 0x567bff }
province.name = _("Yucatán")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "veracruz", color = 0xff758e }
province.name = _("Veracruz")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "campico", color = 0x6051ff }
province.name = _("Campico")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "coahuila_y_texas", color = 0xff7279 }
province.name = _("Coahuila")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "chihuahua", color = 0x38daff }
province.name = _("Chihuahua")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "alta_california", color = 0xc6cbff }
province.name = _("Alta California")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "baja_california", color = 0xff38e7 }
province.name = _("Baja California")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "tamaulipas", color = 0xff87bd }
province.name = _("Tamaulipas")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "nuevo_leon", color = 0xbfffce }
province.name = _("Nuevo León")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "sonora", color = 0x9bffe9 }
province.name = _("Sonora")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "sinaloa", color = 0xffad87 }
province.name = _("Sinaloa")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "jalisco", color = 0x361cff }
province.name = _("Jalisco")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "durango", color = 0x92ff60 }
province.name = _("Durango")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "zacatecas", color = 0xff93a0 }
province.name = _("Zacatecas")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "san_luis_potosi", color = 0x3fffe8 }
province.name = _("San Luis Potosi")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "guanajuato", color = 0xf70fff }
province.name = _("Guanajuato")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "colima", color = 0xff7e5e }
province.name = _("Colima")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "michoacan", color = 0xc4ffc4 }
province.name = _("Michoacán")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "queretaro", color = 0xbbb2ff }
province.name = _("Querétaro")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "mexico", color = 0xff32e3 }
province.name = _("México")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "puebla", color = 0x927aff }
province.name = _("Puebla")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "tlaxcala", color = 0x89ffe1 }
province.name = _("Tlaxcala")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "oaxaca", color = 0x8effa8 }
province.name = _("Oaxaca")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "chiapas", color = 0xbf72ff }
province.name = _("Chiapas")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "nuevo_mexico", color = 0x56ffb8 }
province.name = _("Nuevo México")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "south_new_mexico", color = 0x91a1ff }
province.name = _("South New Mexico")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, mexican, catholic, 2000, 0.8)
province:add_pop(farmer, mexican, catholic, 8000, 0.5)
province:add_pop(soldier, mexican, catholic, 1000, 0.6)
province:add_pop(craftsmen, mexican, catholic, 2000, 0.4)
province:add_pop(bureaucrat, mexican, catholic, 500, 0.6)
province:add_pop(aristocrat, mexican, catholic, 100, 0.8)
province:add_pop(clergymen, mexican, catholic, 1000, 0.5)
province:add_pop(laborer, mexican, catholic, 1000, 0.5)
province:add_pop(entrepreneur, mexican, catholic, 50, 0.9)
province:add_nucleus(mexico)
province:give_to(mexico)
