--------------------------------------------------------------
-- Continent: Americas
-- Subcontinent: North America
-- Country: USA
province = Province:new{ ref_name = "upper_coast", color = 0xa4dd20 }
province.name = _("Upper Coast")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:add_nucleus(texas)
province:give_to(united_states)

province = Province:new{ ref_name = "florida", color = 0x70a6ff }
province.name = _("Florida")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "connecticut", color = 0xe987ff }
province.name = _("Connecticut")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "new_jersey", color = 0xffaea8 }
province.name = _("New Jersey")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "rhode_island", color = 0x7b07ff }
province.name = _("Rhode Island")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "new_york", color = 0xbcfdff }
province.name = _("New York")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "manhattan", color = 0x9f68ff }
province.name = _("Manhattan")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "massachusetts", color = 0x639fff }
province.name = _("Massachusetts")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "new_hampshire", color = 0xf830ff }
province.name = _("New Hampshire")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "vermont", color = 0xff4e32 }
province.name = _("Vermont")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "north_maine", color = 0x91aeff }
province.name = _("North Maine")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "maine", color = 0xff4c7f }
province.name = _("Maine")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)
Nation:set_capital(united_states, province)

province = Province:new{ ref_name = "delaware", color = 0xa372ff }
province.name = _("Delaware")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "maryland", color = 0xa5ffed }
province.name = _("Maryland")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "pennsylvania", color = 0xff49a7 }
province.name = _("Pennsylvania")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "virginia", color = 0xff7579 }
province.name = _("Virginia")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "north_carolina", color = 0x7cb0ff }
province.name = _("North Carolina")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "south_carolina", color = rgb(255, 181, 231) }
province.name = _("South Carolina")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "west_virginia", color = rgb(217, 158, 255) }
province.name = _("West Virginia")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "ohio", color = rgb(140, 212, 255) }
province.name = _("Ohio")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "michigan", color = rgb(255, 45, 174) }
province.name = _("Michigan")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "upper_peninsula", color = 0xd896ff }
province.name = _("Upper Peninsula")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "indiana", color = rgb(188, 255, 239) }
province.name = _("Indiana")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "kentucky", color = rgb(150, 127, 255) }
province.name = _("Kentucky")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "tennessee", color = rgb(255, 76, 189) }
province.name = _("Tennessee")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "georgia", color = rgb(255, 251, 73) }
province.name = _("Georgia")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

-- SWEET HOME ALABAMA!
province = Province:new{ ref_name = "alabama", color = rgb(255, 124, 107) }
province.name = _("Alabama")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "mississipi", color = rgb(255, 102, 221) }
province.name = _("Mississipi")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "mobile", color = rgb(255, 79, 175) }
province.name = _("Mobile")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "biloxi", color = rgb(115, 28, 255) }
province.name = _("Biloxi")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "east_louisiana", color = rgb(199, 48, 255) }
province.name = _("East Louisiana")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "louisiana", color = rgb(91, 146, 255) }
province.name = _("Louisiana")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(united_states)

province = Province:new{ ref_name = "arkansas", color = rgb(123, 255, 22) }
province.name = _("Arkansas")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "missouri", color = rgb(223, 175, 255) }
province.name = _("Missouri")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "iowa", color = rgb(255, 253, 209) }
province.name = _("Iowa")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "illinois", color = rgb(255, 58, 130) }
province.name = _("Illinois")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "winsconsin", color = rgb(255, 205, 155) }
province.name = _("Winsconsin")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "minnesota", color = rgb(168, 255, 201) }
province.name = _("Minnesota")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "north_dakota", color = rgb(191, 255, 204) }
province.name = _("North Dakota")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "south_dakota", color = rgb(160, 255, 250) }
province.name = _("South Dakota")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "nebraska", color = 0xffe0ef }
province.name = _("Nebraska")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "grand_portage", color = rgb(255, 89, 166) }
province.name = _("Grand Portage")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "kansas", color = rgb(255, 113, 73) }
province.name = _("Kansas")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "kansas_indian_territory", color = 0xddfff2 }
province.name = _("Kansas Indian Territory")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "oklahoma", color = 0x84f0ff }
province.name = _("Oklahoma")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "north_oklahoma", color = 0x257883 }
province.name = _("North Oklahoma")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "neutral_strip", color = rgb(233, 147, 255) }
province.name = _("Neutral Strip")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "northern_texas", color = rgb(255, 102, 137) }
province.name = _("Northern Texas")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "eastern_texas", color = rgb(94, 174, 255) }
province.name = _("Eastern Texas")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "el_paso", color = rgb(255, 165, 211) }
province.name = _("El Paso")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "southern_texas", color = rgb(168, 202, 255) }
province.name = _("Southern Texas")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "corpus_christi", color = rgb(173, 255, 241) }
province.name = _("Corpus Christi")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(mexico)

province = Province:new{ ref_name = "hill_country", color = rgb(255, 225, 127) }
province.name = _("Hill Country")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)
province:give_to(mexico)

province = Province:new{ ref_name = "southwestern_colorado", color = rgb(235, 158, 255) }
province.name = _("Southwestern Colorado")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "northwestern_colorado", color = rgb(28, 164, 255) }
province.name = _("Northwestern Colorado")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "colorado", color = rgb(255, 40, 215) }
province.name = _("Colorado")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "southern_wyoming", color = rgb(109, 182, 255) }
province.name = _("Southern Wyoming")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "southwestern_wyoming", color = rgb(40, 90, 255) }
province.name = _("Southwestern Wyoming")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "western_wyoming", color = rgb(255, 58, 97) }
province.name = _("Western Wyoming")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "wyoming", color = rgb(177, 135, 255) }
province.name = _("Wyoming")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "montana", color = rgb(255, 188, 196) }
province.name = _("Montana")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "western_montana", color = rgb(255, 165, 145) }
province.name = _("Western Montana")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "idaho", color = rgb(255, 163, 204) }
province.name = _("Idaho")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "east_oregon", color = rgb(89, 235, 255) }
province.name = _("East Oregon")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "west_oregon", color = rgb(224, 103, 255) }
province.name = _("West Oregon")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "washington", color = 0xe066ff }
province.name = _("Washington")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(united_states)

province = Province:new{ ref_name = "nevada", color = rgb(157, 122, 255) }
province.name = _("Nevada")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "utah", color = rgb(109, 225, 255) }
province.name = _("Utah")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(mexico)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "rocky_mountains", color = rgb(246, 165, 255) }
province.name = _("Rocky Mountains")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(mexico)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "northern_arizona", color = rgb(204, 173, 255) }
province.name = _("Northern Arizona")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(mexico)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "southern_arizona", color = rgb(255, 193, 208) }
province.name = _("Southern Arizona")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(mexico)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "east_new_mexico", color = rgb(109, 255, 242) }
province.name = _("East New Mexico")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(mexico)
province:add_nucleus(mexico)
province:give_to(mexico)

province = Province:new{ ref_name = "south_new_mexico ", color = rgb(45, 161, 255) }
province.name = _("South New Mexico ")
province:register()
province:add_industry(wheat_farm, andes_transport)
province:add_pop(artisan, yankee, protestant, 500, 0.7)
province:add_pop(farmer, yankee, protestant, 500, 0.1)
province:add_pop(soldier, yankee, protestant, 500, 0.2)
province:add_pop(craftsmen, yankee, protestant, 500, 0.2)
province:add_pop(bureaucrat, yankee, protestant, 500, 0.7)
province:add_pop(aristocrat, yankee, protestant, 500, 0.2)
province:add_pop(clergymen, yankee, protestant, 500, 0.3)
province:add_pop(laborer, yankee, protestant, 500, 0.2)
province:add_pop(entrepreneur, yankee, protestant, 500, 0.9)
province:add_pop(slave, yankee, protestant, 500, 0.5)
province:add_nucleus(mexico)
province:add_nucleus(mexico)
province:give_to(mexico)
