--------------------------------------------------------------
-- Continent: Oceania
-- Subcontinent: Polynesia
-- Country: Hawai'i
province = Province:new{ ref_name = "papahānaumokuākea", color = 0xcea3ff }
province.name = _("Papahānaumokuākea")
province:register()
province:add_pop(artisan, polynesian, protestant, 10, 0.6)
province:add_pop(farmer, polynesian, protestant, 8000, 0.4)
province:add_pop(soldier, polynesian, protestant, 10, 0.6)
province:add_pop(craftsmen, polynesian, protestant, 10, 0.4)
province:add_pop(bureaucrat, polynesian, protestant, 10, 0.8)
province:add_pop(aristocrat, polynesian, protestant, 25, 0.5)
province:add_pop(clergymen, polynesian, protestant, 10, 0.6)
province:add_pop(laborer, polynesian, protestant, 1000, 0.5)
province:add_pop(entrepreneur, polynesian, protestant, 5, 0.9)
province:add_nucleus(hawai_i)
province:give_to(hawai_i)

province = Province:new{ ref_name = "kaua_i", color = 0x0f6bff }
province.name = _("Kaua'i")
province:register()
province:add_pop(artisan, polynesian, protestant, 10, 0.6)
province:add_pop(farmer, polynesian, protestant, 8000, 0.4)
province:add_pop(soldier, polynesian, protestant, 10, 0.6)
province:add_pop(craftsmen, polynesian, protestant, 10, 0.4)
province:add_pop(bureaucrat, polynesian, protestant, 10, 0.8)
province:add_pop(aristocrat, polynesian, protestant, 25, 0.5)
province:add_pop(clergymen, polynesian, protestant, 10, 0.6)
province:add_pop(laborer, polynesian, protestant, 1000, 0.5)
province:add_pop(entrepreneur, polynesian, protestant, 5, 0.9)
province:add_nucleus(hawai_i)
province:give_to(hawai_i)

province = Province:new{ ref_name = "o_ahu_maui", color = 0xff7247 }
province.name = _("O'ahu-Maui")
province:register()
province:add_pop(artisan, polynesian, protestant, 10, 0.6)
province:add_pop(farmer, polynesian, protestant, 8000, 0.4)
province:add_pop(soldier, polynesian, protestant, 10, 0.6)
province:add_pop(craftsmen, polynesian, protestant, 10, 0.4)
province:add_pop(bureaucrat, polynesian, protestant, 10, 0.8)
province:add_pop(aristocrat, polynesian, protestant, 25, 0.5)
province:add_pop(clergymen, polynesian, protestant, 10, 0.6)
province:add_pop(laborer, polynesian, protestant, 1000, 0.5)
province:add_pop(entrepreneur, polynesian, protestant, 5, 0.9)
province:add_nucleus(hawai_i)
province:give_to(hawai_i)

-- Whoever did this please fix!!!!
province = Province:new{ ref_name = "hawai_i", color = 0xff54a1 }
province.name = _("Hawai'i")
province:register()
province:add_pop(artisan, polynesian, protestant, 10, 0.6)
province:add_pop(farmer, polynesian, protestant, 8000, 0.4)
province:add_pop(soldier, polynesian, protestant, 10, 0.6)
province:add_pop(craftsmen, polynesian, protestant, 10, 0.4)
province:add_pop(bureaucrat, polynesian, protestant, 10, 0.8)
province:add_pop(aristocrat, polynesian, protestant, 25, 0.5)
province:add_pop(clergymen, polynesian, protestant, 10, 0.6)
province:add_pop(laborer, polynesian, protestant, 1000, 0.5)
province:add_pop(entrepreneur, polynesian, protestant, 5, 0.9)
province:add_nucleus(hawai_i)
province:give_to(hawai_i)
hawai_i:set_capital(province)