#ifndef ACTIONS_H
#define ACTIONS_H

#include "serializer.hpp"

enum ActionType {
    ACTION_PROVINCE_UPDATE,
    ACTION_PROVINCE_ADD,
    ACTION_PROVINCE_REMOVE,
    ACTION_PROVINCE_COLONIZE,

    ACTION_NATION_UPDATE,
    ACTION_NATION_ADD,
    ACTION_NATION_REMOVE,
    ACTION_NATION_ENACT_POLICY,
    ACTION_NATION_TAKE_DESCISION,

    ACTION_UNIT_UPDATE,
    ACTION_UNIT_ADD,
    ACTION_UNIT_REMOVE,
    ACTION_UNIT_CHANGE_TARGET,

    ACTION_BOAT_UPDATE,
    ACTION_BOAT_ADD,
    ACTION_BOAT_REMOVE,
    ACTION_BOAT_CHANGE_TARGET,

    ACTION_OUTPOST_UPDATE,
    ACTION_OUTPOST_ADD,
    ACTION_OUTPOST_START_BUILDING_UNIT,
    ACTION_OUTPOST_START_BUILDING_BOAT,

    ACTION_CHANGE_TREATY_APPROVAL,
    ACTION_DRAFT_TREATY,

    // Tell client that a whole tick has been done :D
    ACTION_WORLD_TICK,

    // Self-explanaitory
    ACTION_SELECT_NATION,

    // Gaming chatting
    ACTION_CHAT_MESSAGE,
    ACTION_CHAT_NICKNAME,

    // Testing
    ACTION_PING,
    ACTION_PONG,

    // Errors
    ACTION_BAD,
};

class Action {
public:
    enum ActionType type;
    
    Action(enum ActionType _type) : type(_type) {};
};

#endif
