--------------------------------------------------------------
-- Continent: Europe
-- Subcontinent: Middle Europe
-- Country: Austrian Empire
province = Province:new{ ref_name = "vorarlberg", color = 0x5effb6 }
province.name = _("Vorarlberg")
Province:register(province)
Province:add_pop(province, artisan, german, catholic, 5000, 0.9)
Province:add_pop(province, farmer, german, catholic, 40000, 0.8)
Province:add_pop(province, soldier, german, catholic, 8000, 0.8)
Province:add_pop(province, craftsmen, german, catholic, 5000, 0.9)
Province:add_pop(province, bureaucrat, german, catholic, 5000, 0.9)
Province:add_pop(province, aristocrat, german, catholic, 5000, 0.9)
Province:add_pop(province, clergymen, german, catholic, 5000, 0.9)
Province:add_pop(province, laborer, german, catholic, 50000, 0.8)
Province:add_pop(province, entrepreneur, german, catholic, 800, 0.9)
Province:add_nucleus(province, austria)
Province:give_to(province, austria)

province = Province:new{ ref_name = "tyrol", color = 0xff899f }
province.name = _("Tyrol")
Province:register(province)
Province:add_pop(province, artisan, german, catholic, 5000, 0.9)
Province:add_pop(province, farmer, german, catholic, 40000, 0.8)
Province:add_pop(province, soldier, german, catholic, 8000, 0.8)
Province:add_pop(province, craftsmen, german, catholic, 5000, 0.9)
Province:add_pop(province, bureaucrat, german, catholic, 5000, 0.9)
Province:add_pop(province, aristocrat, german, catholic, 5000, 0.9)
Province:add_pop(province, clergymen, german, catholic, 5000, 0.9)
Province:add_pop(province, laborer, german, catholic, 50000, 0.8)
Province:add_pop(province, entrepreneur, german, catholic, 800, 0.9)
Province:add_nucleus(province, austria)
Province:give_to(province, austria)

province = Province:new{ ref_name = "salzburg", color = 0xff4c85 }
province.name = _("Salzburg")
Province:register(province)
Province:add_pop(province, artisan, german, catholic, 5000, 0.9)
Province:add_pop(province, farmer, german, catholic, 40000, 0.8)
Province:add_pop(province, soldier, german, catholic, 8000, 0.8)
Province:add_pop(province, craftsmen, german, catholic, 5000, 0.9)
Province:add_pop(province, bureaucrat, german, catholic, 5000, 0.9)
Province:add_pop(province, aristocrat, german, catholic, 5000, 0.9)
Province:add_pop(province, clergymen, german, catholic, 5000, 0.9)
Province:add_pop(province, laborer, german, catholic, 50000, 0.8)
Province:add_pop(province, entrepreneur, german, catholic, 800, 0.9)
Province:add_nucleus(province, austria)
--Province:add_nucleus(province, salzburg)
Province:give_to(province, austria)

province = Province:new{ ref_name = "carinthia", color = 0xd1ffff }
province.name = _("Carinthia")
Province:register(province)
Province:add_pop(province, artisan, german, catholic, 5000, 0.9)
Province:add_pop(province, farmer, german, catholic, 40000, 0.8)
Province:add_pop(province, soldier, german, catholic, 8000, 0.8)
Province:add_pop(province, craftsmen, german, catholic, 5000, 0.9)
Province:add_pop(province, bureaucrat, german, catholic, 5000, 0.9)
Province:add_pop(province, aristocrat, german, catholic, 5000, 0.9)
Province:add_pop(province, clergymen, german, catholic, 5000, 0.9)
Province:add_pop(province, laborer, german, catholic, 50000, 0.8)
Province:add_pop(province, entrepreneur, german, catholic, 800, 0.9)
Province:add_nucleus(province, austria)
Province:give_to(province, austria)

province = Province:new{ ref_name = "styria", color = 0x77ffff }
province.name = _("Styria")
Province:register(province)
Province:add_pop(province, artisan, german, catholic, 5000, 0.9)
Province:add_pop(province, farmer, german, catholic, 40000, 0.8)
Province:add_pop(province, soldier, german, catholic, 8000, 0.8)
Province:add_pop(province, craftsmen, german, catholic, 5000, 0.9)
Province:add_pop(province, bureaucrat, german, catholic, 5000, 0.9)
Province:add_pop(province, aristocrat, german, catholic, 5000, 0.9)
Province:add_pop(province, clergymen, german, catholic, 5000, 0.9)
Province:add_pop(province, laborer, german, catholic, 50000, 0.8)
Province:add_pop(province, entrepreneur, german, catholic, 800, 0.9)
Province:add_nucleus(province, austria)
Province:give_to(province, austria)

province = Province:new{ ref_name = "upper_austria", color = 0xff6554 }
province.name = _("Upper Austria")
Province:register(province)
Province:add_pop(province, artisan, german, catholic, 5000, 0.9)
Province:add_pop(province, farmer, german, catholic, 40000, 0.8)
Province:add_pop(province, soldier, german, catholic, 8000, 0.8)
Province:add_pop(province, craftsmen, german, catholic, 5000, 0.9)
Province:add_pop(province, bureaucrat, german, catholic, 5000, 0.9)
Province:add_pop(province, aristocrat, german, catholic, 5000, 0.9)
Province:add_pop(province, clergymen, german, catholic, 5000, 0.9)
Province:add_pop(province, laborer, german, catholic, 50000, 0.8)
Province:add_pop(province, entrepreneur, german, catholic, 800, 0.9)
Province:add_nucleus(province, austria)
Province:give_to(province, austria)

province = Province:new{ ref_name = "lower_austria", color = 0xfffd89 }
province.name = _("Lower Austria")
Province:register(province)
Province:add_pop(province, artisan, german, catholic, 5000, 0.9)
Province:add_pop(province, farmer, german, catholic, 40000, 0.8)
Province:add_pop(province, soldier, german, catholic, 8000, 0.8)
Province:add_pop(province, craftsmen, german, catholic, 5000, 0.9)
Province:add_pop(province, bureaucrat, german, catholic, 5000, 0.9)
Province:add_pop(province, aristocrat, german, catholic, 5000, 0.9)
Province:add_pop(province, clergymen, german, catholic, 5000, 0.9)
Province:add_pop(province, laborer, german, catholic, 50000, 0.8)
Province:add_pop(province, entrepreneur, german, catholic, 800, 0.9)
Province:add_nucleus(province, austria)
Province:give_to(province, austria)

province = Province:new{ ref_name = "burgenland", color = 0x7c92ff }
province.name = _("Burgenland")
Province:register(province)
Province:add_pop(province, artisan, german, catholic, 5000, 0.9)
Province:add_pop(province, farmer, german, catholic, 40000, 0.8)
Province:add_pop(province, soldier, german, catholic, 8000, 0.8)
Province:add_pop(province, craftsmen, german, catholic, 5000, 0.9)
Province:add_pop(province, bureaucrat, german, catholic, 5000, 0.9)
Province:add_pop(province, aristocrat, german, catholic, 5000, 0.9)
Province:add_pop(province, clergymen, german, catholic, 5000, 0.9)
Province:add_pop(province, laborer, german, catholic, 50000, 0.8)
Province:add_pop(province, entrepreneur, german, catholic, 800, 0.9)
Province:add_nucleus(province, austria)
Province:give_to(province, austria)