province = Province:create{ ref_name = "bourgas", color = 0xff7c89 }
province.name = _("Bourgas")
Province:register(province)
Province:add_pop(province, artisan, bulgarian, orthodox, 1000, 0.6)
Province:add_pop(province, farmer, bulgarian, orthodox, 5000, 0.2)
Province:add_pop(province, soldier, bulgarian, orthodox, 1000, 0.6)
Province:add_pop(province, craftsmen, bulgarian, orthodox, 1000, 0.4)
Province:add_pop(province, bureaucrat, bulgarian, orthodox, 1000, 0.8)
Province:add_pop(province, aristocrat, bulgarian, orthodox, 1000, 0.7)
Province:add_pop(province, clergymen, bulgarian, orthodox, 1000, 0.6)
Province:add_pop(province, laborer, bulgarian, orthodox, 1000, 0.4)
Province:add_pop(province, entrepreneur, bulgarian, orthodox, 1000, 0.9)
Province:add_nucleus(province, bulgaria)
Province:add_nucleus(province, turkey)
Province:give_to(province, turkey)

province = Province:create{ ref_name = "varna", color = 0x9844ff }
province.name = _("Varna")
Province:register(province)
Province:add_pop(province, artisan, bulgarian, orthodox, 1000, 0.6)
Province:add_pop(province, farmer, bulgarian, orthodox, 5000, 0.2)
Province:add_pop(province, soldier, bulgarian, orthodox, 1000, 0.6)
Province:add_pop(province, craftsmen, bulgarian, orthodox, 1000, 0.4)
Province:add_pop(province, bureaucrat, bulgarian, orthodox, 1000, 0.8)
Province:add_pop(province, aristocrat, bulgarian, orthodox, 1000, 0.7)
Province:add_pop(province, clergymen, bulgarian, orthodox, 1000, 0.6)
Province:add_pop(province, laborer, bulgarian, orthodox, 1000, 0.4)
Province:add_pop(province, entrepreneur, bulgarian, orthodox, 1000, 0.9)
Province:add_nucleus(province, bulgaria)
Province:add_nucleus(province, turkey)
Province:give_to(province, turkey)

province = Province:create{ ref_name = "vidin", color = 0xff2119 }
province.name = _("Vidin")
Province:register(province)
Province:add_pop(province, artisan, bulgarian, orthodox, 1000, 0.6)
Province:add_pop(province, farmer, bulgarian, orthodox, 5000, 0.2)
Province:add_pop(province, soldier, bulgarian, orthodox, 1000, 0.6)
Province:add_pop(province, craftsmen, bulgarian, orthodox, 1000, 0.4)
Province:add_pop(province, bureaucrat, bulgarian, orthodox, 1000, 0.8)
Province:add_pop(province, aristocrat, bulgarian, orthodox, 1000, 0.7)
Province:add_pop(province, clergymen, bulgarian, orthodox, 1000, 0.6)
Province:add_pop(province, laborer, bulgarian, orthodox, 1000, 0.4)
Province:add_pop(province, entrepreneur, bulgarian, orthodox, 1000, 0.9)
Province:add_nucleus(province, bulgaria)
Province:add_nucleus(province, turkey)
Province:give_to(province, turkey)

province = Province:create{ ref_name = "lovetch", color = 0xbcffdd }
province.name = _("Lovetch")
Province:register(province)
Province:add_pop(province, artisan, bulgarian, orthodox, 1000, 0.6)
Province:add_pop(province, farmer, bulgarian, orthodox, 5000, 0.2)
Province:add_pop(province, soldier, bulgarian, orthodox, 1000, 0.6)
Province:add_pop(province, craftsmen, bulgarian, orthodox, 1000, 0.4)
Province:add_pop(province, bureaucrat, bulgarian, orthodox, 1000, 0.8)
Province:add_pop(province, aristocrat, bulgarian, orthodox, 1000, 0.7)
Province:add_pop(province, clergymen, bulgarian, orthodox, 1000, 0.6)
Province:add_pop(province, laborer, bulgarian, orthodox, 1000, 0.4)
Province:add_pop(province, entrepreneur, bulgarian, orthodox, 1000, 0.9)
Province:add_nucleus(province, bulgaria)
Province:add_nucleus(province, turkey)
Province:give_to(province, turkey)

province = Province:create{ ref_name = "blagoevgrad", color = 0xff666b }
province.name = _("Blagoevgrad")
Province:register(province)
Province:add_pop(province, artisan, bulgarian, orthodox, 1000, 0.6)
Province:add_pop(province, farmer, bulgarian, orthodox, 5000, 0.2)
Province:add_pop(province, soldier, bulgarian, orthodox, 1000, 0.6)
Province:add_pop(province, craftsmen, bulgarian, orthodox, 1000, 0.4)
Province:add_pop(province, bureaucrat, bulgarian, orthodox, 1000, 0.8)
Province:add_pop(province, aristocrat, bulgarian, orthodox, 1000, 0.7)
Province:add_pop(province, clergymen, bulgarian, orthodox, 1000, 0.6)
Province:add_pop(province, laborer, bulgarian, orthodox, 1000, 0.4)
Province:add_pop(province, entrepreneur, bulgarian, orthodox, 1000, 0.9)
Province:add_nucleus(province, bulgaria)
Province:add_nucleus(province, turkey)
Province:give_to(province, turkey)