--------------------------------------------------------------
-- Continent: Europe
-- Subcontinent: Baltics
-- Country: Estonia
province = Province:create{ ref_name = "saare", color = 0xfff06d }
province.name = _("Saare")
Province:register(province)
Province:add_pop(province, artisan, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, farmer, estonian, orthodox, 40000, 0.8)
Province:add_pop(province, soldier, estonian, orthodox, 8000, 0.8)
Province:add_pop(province, craftsmen, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, bureaucrat, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, aristocrat, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, clergymen, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, laborer, estonian, orthodox, 50000, 0.8)
Province:add_pop(province, entrepreneur, estonian, orthodox, 800, 0.9)
Province:add_nucleus(province, estonia)
Province:add_nucleus(province, russia)
Province:give_to(province, russia)

province = Province:create{ ref_name = "hiiu", color = 0xff4fe4 }
province.name = _("Hiiu")
Province:register(province)
Province:add_pop(province, artisan, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, farmer, estonian, orthodox, 40000, 0.8)
Province:add_pop(province, soldier, estonian, orthodox, 8000, 0.8)
Province:add_pop(province, craftsmen, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, bureaucrat, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, aristocrat, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, clergymen, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, laborer, estonian, orthodox, 50000, 0.8)
Province:add_pop(province, entrepreneur, estonian, orthodox, 800, 0.9)
Province:add_nucleus(province, estonia)
Province:add_nucleus(province, russia)
Province:give_to(province, russia)

province = Province:create{ ref_name = "harju", color = 0x70ffe0 }
province.name = _("Harju")
Province:register(province)
Province:add_pop(province, artisan, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, farmer, estonian, orthodox, 40000, 0.8)
Province:add_pop(province, soldier, estonian, orthodox, 8000, 0.8)
Province:add_pop(province, craftsmen, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, bureaucrat, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, aristocrat, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, clergymen, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, laborer, estonian, orthodox, 50000, 0.8)
Province:add_pop(province, entrepreneur, estonian, orthodox, 800, 0.9)
Province:add_nucleus(province, estonia)
Province:add_nucleus(province, russia)
Province:give_to(province, russia)

province = Province:create{ ref_name = "laane", color = 0x3a7cff }
province.name = _("Lääne")
Province:register(province)
Province:add_pop(province, artisan, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, farmer, estonian, orthodox, 40000, 0.8)
Province:add_pop(province, soldier, estonian, orthodox, 8000, 0.8)
Province:add_pop(province, craftsmen, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, bureaucrat, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, aristocrat, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, clergymen, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, laborer, estonian, orthodox, 50000, 0.8)
Province:add_pop(province, entrepreneur, estonian, orthodox, 800, 0.9)
Province:add_nucleus(province, estonia)
Province:add_nucleus(province, russia)
Province:give_to(province, russia)

province = Province:create{ ref_name = "parnu", color = 0x5effae }
province.name = _("Pärnu")
Province:register(province)
Province:add_pop(province, artisan, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, farmer, estonian, orthodox, 40000, 0.8)
Province:add_pop(province, soldier, estonian, orthodox, 8000, 0.8)
Province:add_pop(province, craftsmen, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, bureaucrat, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, aristocrat, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, clergymen, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, laborer, estonian, orthodox, 50000, 0.8)
Province:add_pop(province, entrepreneur, estonian, orthodox, 800, 0.9)
Province:add_nucleus(province, estonia)
Province:add_nucleus(province, russia)
Province:give_to(province, russia)

province = Province:create{ ref_name = "viljandi", color = 0x8132ff }
province.name = _("Viljandi")
Province:register(province)
Province:add_pop(province, artisan, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, farmer, estonian, orthodox, 40000, 0.8)
Province:add_pop(province, soldier, estonian, orthodox, 8000, 0.8)
Province:add_pop(province, craftsmen, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, bureaucrat, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, aristocrat, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, clergymen, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, laborer, estonian, orthodox, 50000, 0.8)
Province:add_pop(province, entrepreneur, estonian, orthodox, 800, 0.9)
Province:add_nucleus(province, estonia)
Province:add_nucleus(province, russia)
Province:give_to(province, russia)

province = Province:create{ ref_name = "jarva", color = 0xff6b86 }
province.name = _("Järva")
Province:register(province)
Province:add_pop(province, artisan, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, farmer, estonian, orthodox, 40000, 0.8)
Province:add_pop(province, soldier, estonian, orthodox, 8000, 0.8)
Province:add_pop(province, craftsmen, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, bureaucrat, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, aristocrat, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, clergymen, estonian, orthodox, 5000, 0.9)
Province:add_pop(province, laborer, estonian, orthodox, 50000, 0.8)
Province:add_pop(province, entrepreneur, estonian, orthodox, 800, 0.9)
Province:add_nucleus(province, estonia)
Province:add_nucleus(province, russia)
Province:give_to(province, russia)
