--------------------------------------------------------------
-- Continent: Europe
-- Subcontinent: Middle Europe
-- Country: Austrian Empire
province = Province:create{ ref_name = "finistere", color = 0x979939 }
province.name = _("Finistère")
Province:register(province)
Province:add_pop(province, artisan, french, catholic, 5000, 0.9)
Province:add_pop(province, farmer, french, catholic, 40000, 0.8)
Province:add_pop(province, soldier, french, catholic, 8000, 0.8)
Province:add_pop(province, craftsmen, french, catholic, 5000, 0.9)
Province:add_pop(province, bureaucrat, french, catholic, 5000, 0.9)
Province:add_pop(province, aristocrat, french, catholic, 5000, 0.9)
Province:add_pop(province, clergymen, french, catholic, 5000, 0.9)
Province:add_pop(province, laborer, french, catholic, 50000, 0.8)
Province:add_pop(province, entrepreneur, french, catholic, 800, 0.9)
Province:add_nucleus(province, brittany)
Province:add_nucleus(province, france)
Province:give_to(province, france)

province = Province:create{ ref_name = "cotes_d_armor", color = 0xcf3be0 }
province.name = _("Côtes d' Armor")
Province:register(province)
Province:add_pop(province, artisan, french, catholic, 5000, 0.9)
Province:add_pop(province, farmer, french, catholic, 40000, 0.8)
Province:add_pop(province, soldier, french, catholic, 8000, 0.8)
Province:add_pop(province, craftsmen, french, catholic, 5000, 0.9)
Province:add_pop(province, bureaucrat, french, catholic, 5000, 0.9)
Province:add_pop(province, aristocrat, french, catholic, 5000, 0.9)
Province:add_pop(province, clergymen, french, catholic, 5000, 0.9)
Province:add_pop(province, laborer, french, catholic, 50000, 0.8)
Province:add_pop(province, entrepreneur, french, catholic, 800, 0.9)
Province:add_nucleus(province, brittany)
Province:add_nucleus(province, france)
Province:give_to(province, france)

province = Province:create{ ref_name = "morbihan", color = 0x592dc0 }
province.name = _("Morbihan")
Province:register(province)
Province:add_pop(province, artisan, french, catholic, 5000, 0.9)
Province:add_pop(province, farmer, french, catholic, 40000, 0.8)
Province:add_pop(province, soldier, french, catholic, 8000, 0.8)
Province:add_pop(province, craftsmen, french, catholic, 5000, 0.9)
Province:add_pop(province, bureaucrat, french, catholic, 5000, 0.9)
Province:add_pop(province, aristocrat, french, catholic, 5000, 0.9)
Province:add_pop(province, clergymen, french, catholic, 5000, 0.9)
Province:add_pop(province, laborer, french, catholic, 50000, 0.8)
Province:add_pop(province, entrepreneur, french, catholic, 800, 0.9)
Province:add_nucleus(province, brittany)
Province:add_nucleus(province, france)
Province:give_to(province, france)

province = Province:create{ ref_name = "ille_et_vilaine", color = 0x487f80 }
province.name = _("Ille et Vilaine")
Province:register(province)
Province:add_pop(province, artisan, french, catholic, 5000, 0.9)
Province:add_pop(province, farmer, french, catholic, 40000, 0.8)
Province:add_pop(province, soldier, french, catholic, 8000, 0.8)
Province:add_pop(province, craftsmen, french, catholic, 5000, 0.9)
Province:add_pop(province, bureaucrat, french, catholic, 5000, 0.9)
Province:add_pop(province, aristocrat, french, catholic, 5000, 0.9)
Province:add_pop(province, clergymen, french, catholic, 5000, 0.9)
Province:add_pop(province, laborer, french, catholic, 50000, 0.8)
Province:add_pop(province, entrepreneur, french, catholic, 800, 0.9)
Province:add_nucleus(province, brittany)
Province:add_nucleus(province, france)
Province:give_to(province, france)

province = Province:create{ ref_name = "manche", color = 0x9f1da0 }
province.name = _("Manche")
Province:register(province)
Province:add_pop(province, artisan, french, catholic, 5000, 0.9)
Province:add_pop(province, farmer, french, catholic, 40000, 0.8)
Province:add_pop(province, soldier, french, catholic, 8000, 0.8)
Province:add_pop(province, craftsmen, french, catholic, 5000, 0.9)
Province:add_pop(province, bureaucrat, french, catholic, 5000, 0.9)
Province:add_pop(province, aristocrat, french, catholic, 5000, 0.9)
Province:add_pop(province, clergymen, french, catholic, 5000, 0.9)
Province:add_pop(province, laborer, french, catholic, 50000, 0.8)
Province:add_pop(province, entrepreneur, french, catholic, 800, 0.9)
Province:add_nucleus(province, normandy)
Province:add_nucleus(province, france)
Province:give_to(province, france)

province = Province:create{ ref_name = "calvados", color = 0x301ec0 }
province.name = _("Calvados")
Province:register(province)
Province:add_pop(province, artisan, french, catholic, 5000, 0.9)
Province:add_pop(province, farmer, french, catholic, 40000, 0.8)
Province:add_pop(province, soldier, french, catholic, 8000, 0.8)
Province:add_pop(province, craftsmen, french, catholic, 5000, 0.9)
Province:add_pop(province, bureaucrat, french, catholic, 5000, 0.9)
Province:add_pop(province, aristocrat, french, catholic, 5000, 0.9)
Province:add_pop(province, clergymen, french, catholic, 5000, 0.9)
Province:add_pop(province, laborer, french, catholic, 50000, 0.8)
Province:add_pop(province, entrepreneur, french, catholic, 800, 0.9)
Province:add_nucleus(province, normandy)
Province:add_nucleus(province, france)
Province:give_to(province, france)

province = Province:create{ ref_name = "orne", color = 0x994be1 }
province.name = _("Orne")
Province:register(province)
Province:add_pop(province, artisan, french, catholic, 5000, 0.9)
Province:add_pop(province, farmer, french, catholic, 40000, 0.8)
Province:add_pop(province, soldier, french, catholic, 8000, 0.8)
Province:add_pop(province, craftsmen, french, catholic, 5000, 0.9)
Province:add_pop(province, bureaucrat, french, catholic, 5000, 0.9)
Province:add_pop(province, aristocrat, french, catholic, 5000, 0.9)
Province:add_pop(province, clergymen, french, catholic, 5000, 0.9)
Province:add_pop(province, laborer, french, catholic, 50000, 0.8)
Province:add_pop(province, entrepreneur, french, catholic, 800, 0.9)
Province:add_nucleus(province, normandy)
Province:add_nucleus(province, france)
Province:give_to(province, france)

province = Province:create{ ref_name = "eure", color = 0xca19c0 }
province.name = _("Eure")
Province:register(province)
Province:add_pop(province, artisan, french, catholic, 5000, 0.9)
Province:add_pop(province, farmer, french, catholic, 40000, 0.8)
Province:add_pop(province, soldier, french, catholic, 8000, 0.8)
Province:add_pop(province, craftsmen, french, catholic, 5000, 0.9)
Province:add_pop(province, bureaucrat, french, catholic, 5000, 0.9)
Province:add_pop(province, aristocrat, french, catholic, 5000, 0.9)
Province:add_pop(province, clergymen, french, catholic, 5000, 0.9)
Province:add_pop(province, laborer, french, catholic, 50000, 0.8)
Province:add_pop(province, entrepreneur, french, catholic, 800, 0.9)
Province:add_nucleus(province, normandy)
Province:add_nucleus(province, france)
Province:give_to(province, france)

province = Province:create{ ref_name = "seine_maritime", color = 0x349ba0 }
province.name = _("Seine Maritime")
Province:register(province)
Province:add_pop(province, artisan, french, catholic, 5000, 0.9)
Province:add_pop(province, farmer, french, catholic, 40000, 0.8)
Province:add_pop(province, soldier, french, catholic, 8000, 0.8)
Province:add_pop(province, craftsmen, french, catholic, 5000, 0.9)
Province:add_pop(province, bureaucrat, french, catholic, 5000, 0.9)
Province:add_pop(province, aristocrat, french, catholic, 5000, 0.9)
Province:add_pop(province, clergymen, french, catholic, 5000, 0.9)
Province:add_pop(province, laborer, french, catholic, 50000, 0.8)
Province:add_pop(province, entrepreneur, french, catholic, 800, 0.9)
Province:add_nucleus(province, normandy)
Province:add_nucleus(province, france)
Province:give_to(province, france)

-- TODO: Rest of france, we just have done brittany and normandy