--------------------------------------------------------------
-- Continent: Europe
-- Subcontinent: Middle Europe
-- Country: Austrian Empire
province = Province:new{ ref_name = "vorarlberg", color = 0x5effb6 }
province.name = _("Vorarlberg")
province:register()
province:add_pop(artisan, german, catholic, 5000, 0.9)
province:add_pop(farmer, german, catholic, 40000, 0.8)
province:add_pop(soldier, german, catholic, 8000, 0.8)
province:add_pop(craftsmen, german, catholic, 5000, 0.9)
province:add_pop(bureaucrat, german, catholic, 5000, 0.9)
province:add_pop(aristocrat, german, catholic, 5000, 0.9)
province:add_pop(clergymen, german, catholic, 5000, 0.9)
province:add_pop(laborer, german, catholic, 50000, 0.8)
province:add_pop(entrepreneur, german, catholic, 800, 0.9)
province:add_nucleus(austria)
province:give_to(austria)

province = Province:new{ ref_name = "tyrol", color = 0xff899f }
province.name = _("Tyrol")
province:register()
province:add_pop(artisan, german, catholic, 5000, 0.9)
province:add_pop(farmer, german, catholic, 40000, 0.8)
province:add_pop(soldier, german, catholic, 8000, 0.8)
province:add_pop(craftsmen, german, catholic, 5000, 0.9)
province:add_pop(bureaucrat, german, catholic, 5000, 0.9)
province:add_pop(aristocrat, german, catholic, 5000, 0.9)
province:add_pop(clergymen, german, catholic, 5000, 0.9)
province:add_pop(laborer, german, catholic, 50000, 0.8)
province:add_pop(entrepreneur, german, catholic, 800, 0.9)
province:add_nucleus(austria)
province:give_to(austria)

province = Province:new{ ref_name = "salzburg", color = 0xff4c85 }
province.name = _("Salzburg")
province:register()
province:add_pop(artisan, german, catholic, 5000, 0.9)
province:add_pop(farmer, german, catholic, 40000, 0.8)
province:add_pop(soldier, german, catholic, 8000, 0.8)
province:add_pop(craftsmen, german, catholic, 5000, 0.9)
province:add_pop(bureaucrat, german, catholic, 5000, 0.9)
province:add_pop(aristocrat, german, catholic, 5000, 0.9)
province:add_pop(clergymen, german, catholic, 5000, 0.9)
province:add_pop(laborer, german, catholic, 50000, 0.8)
province:add_pop(entrepreneur, german, catholic, 800, 0.9)
province:add_nucleus(austria)
--province:add_nucleus(salzburg)
province:give_to(austria)

province = Province:new{ ref_name = "carinthia", color = 0xd1ffff }
province.name = _("Carinthia")
province:register()
province:add_pop(artisan, german, catholic, 5000, 0.9)
province:add_pop(farmer, german, catholic, 40000, 0.8)
province:add_pop(soldier, german, catholic, 8000, 0.8)
province:add_pop(craftsmen, german, catholic, 5000, 0.9)
province:add_pop(bureaucrat, german, catholic, 5000, 0.9)
province:add_pop(aristocrat, german, catholic, 5000, 0.9)
province:add_pop(clergymen, german, catholic, 5000, 0.9)
province:add_pop(laborer, german, catholic, 50000, 0.8)
province:add_pop(entrepreneur, german, catholic, 800, 0.9)
province:add_nucleus(austria)
province:give_to(austria)

province = Province:new{ ref_name = "styria", color = 0x77ffff }
province.name = _("Styria")
province:register()
province:add_pop(artisan, german, catholic, 5000, 0.9)
province:add_pop(farmer, german, catholic, 40000, 0.8)
province:add_pop(soldier, german, catholic, 8000, 0.8)
province:add_pop(craftsmen, german, catholic, 5000, 0.9)
province:add_pop(bureaucrat, german, catholic, 5000, 0.9)
province:add_pop(aristocrat, german, catholic, 5000, 0.9)
province:add_pop(clergymen, german, catholic, 5000, 0.9)
province:add_pop(laborer, german, catholic, 50000, 0.8)
province:add_pop(entrepreneur, german, catholic, 800, 0.9)
province:add_nucleus(austria)
province:give_to(austria)

province = Province:new{ ref_name = "upper_austria", color = 0xff6554 }
province.name = _("Upper Austria")
province:register()
province:add_pop(artisan, german, catholic, 5000, 0.9)
province:add_pop(farmer, german, catholic, 40000, 0.8)
province:add_pop(soldier, german, catholic, 8000, 0.8)
province:add_pop(craftsmen, german, catholic, 5000, 0.9)
province:add_pop(bureaucrat, german, catholic, 5000, 0.9)
province:add_pop(aristocrat, german, catholic, 5000, 0.9)
province:add_pop(clergymen, german, catholic, 5000, 0.9)
province:add_pop(laborer, german, catholic, 50000, 0.8)
province:add_pop(entrepreneur, german, catholic, 800, 0.9)
province:add_nucleus(austria)
province:give_to(austria)

province = Province:new{ ref_name = "lower_austria", color = 0xfffd89 }
province.name = _("Lower Austria")
province:register()
province:add_pop(artisan, german, catholic, 5000, 0.9)
province:add_pop(farmer, german, catholic, 40000, 0.8)
province:add_pop(soldier, german, catholic, 8000, 0.8)
province:add_pop(craftsmen, german, catholic, 5000, 0.9)
province:add_pop(bureaucrat, german, catholic, 5000, 0.9)
province:add_pop(aristocrat, german, catholic, 5000, 0.9)
province:add_pop(clergymen, german, catholic, 5000, 0.9)
province:add_pop(laborer, german, catholic, 50000, 0.8)
province:add_pop(entrepreneur, german, catholic, 800, 0.9)
province:add_nucleus(austria)
province:give_to(austria)

province = Province:new{ ref_name = "burgenland", color = 0x7c92ff }
province.name = _("Burgenland")
province:register()
province:add_pop(artisan, german, catholic, 5000, 0.9)
province:add_pop(farmer, german, catholic, 40000, 0.8)
province:add_pop(soldier, german, catholic, 8000, 0.8)
province:add_pop(craftsmen, german, catholic, 5000, 0.9)
province:add_pop(bureaucrat, german, catholic, 5000, 0.9)
province:add_pop(aristocrat, german, catholic, 5000, 0.9)
province:add_pop(clergymen, german, catholic, 5000, 0.9)
province:add_pop(laborer, german, catholic, 50000, 0.8)
province:add_pop(entrepreneur, german, catholic, 800, 0.9)
province:add_nucleus(austria)
province:give_to(austria)