province = Province:new{ ref_name = "bourgas", color = 0xff7c89 }
province.name = _("Bourgas")
province:register()
province:add_pop(artisan, bulgarian, orthodox, 1000, 0.6)
province:add_pop(farmer, bulgarian, orthodox, 5000, 0.2)
province:add_pop(soldier, bulgarian, orthodox, 1000, 0.6)
province:add_pop(craftsmen, bulgarian, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, bulgarian, orthodox, 1000, 0.8)
province:add_pop(aristocrat, bulgarian, orthodox, 1000, 0.7)
province:add_pop(clergymen, bulgarian, orthodox, 1000, 0.6)
province:add_pop(laborer, bulgarian, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, bulgarian, orthodox, 1000, 0.9)
province:add_nucleus(bulgaria)
province:add_nucleus(turkey)
province:give_to(turkey)

province = Province:new{ ref_name = "varna", color = 0x9844ff }
province.name = _("Varna")
province:register()
province:add_pop(artisan, bulgarian, orthodox, 1000, 0.6)
province:add_pop(farmer, bulgarian, orthodox, 5000, 0.2)
province:add_pop(soldier, bulgarian, orthodox, 1000, 0.6)
province:add_pop(craftsmen, bulgarian, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, bulgarian, orthodox, 1000, 0.8)
province:add_pop(aristocrat, bulgarian, orthodox, 1000, 0.7)
province:add_pop(clergymen, bulgarian, orthodox, 1000, 0.6)
province:add_pop(laborer, bulgarian, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, bulgarian, orthodox, 1000, 0.9)
province:add_nucleus(bulgaria)
province:add_nucleus(turkey)
province:give_to(turkey)

province = Province:new{ ref_name = "vidin", color = 0xff2119 }
province.name = _("Vidin")
province:register()
province:add_pop(artisan, bulgarian, orthodox, 1000, 0.6)
province:add_pop(farmer, bulgarian, orthodox, 5000, 0.2)
province:add_pop(soldier, bulgarian, orthodox, 1000, 0.6)
province:add_pop(craftsmen, bulgarian, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, bulgarian, orthodox, 1000, 0.8)
province:add_pop(aristocrat, bulgarian, orthodox, 1000, 0.7)
province:add_pop(clergymen, bulgarian, orthodox, 1000, 0.6)
province:add_pop(laborer, bulgarian, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, bulgarian, orthodox, 1000, 0.9)
province:add_nucleus(bulgaria)
province:add_nucleus(turkey)
province:give_to(turkey)

province = Province:new{ ref_name = "lovetch", color = 0xbcffdd }
province.name = _("Lovetch")
province:register()
province:add_pop(artisan, bulgarian, orthodox, 1000, 0.6)
province:add_pop(farmer, bulgarian, orthodox, 5000, 0.2)
province:add_pop(soldier, bulgarian, orthodox, 1000, 0.6)
province:add_pop(craftsmen, bulgarian, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, bulgarian, orthodox, 1000, 0.8)
province:add_pop(aristocrat, bulgarian, orthodox, 1000, 0.7)
province:add_pop(clergymen, bulgarian, orthodox, 1000, 0.6)
province:add_pop(laborer, bulgarian, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, bulgarian, orthodox, 1000, 0.9)
province:add_nucleus(bulgaria)
province:add_nucleus(turkey)
province:give_to(turkey)

province = Province:new{ ref_name = "blagoevgrad", color = 0xff666b }
province.name = _("Blagoevgrad")
province:register()
province:add_pop(artisan, bulgarian, orthodox, 1000, 0.6)
province:add_pop(farmer, bulgarian, orthodox, 5000, 0.2)
province:add_pop(soldier, bulgarian, orthodox, 1000, 0.6)
province:add_pop(craftsmen, bulgarian, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, bulgarian, orthodox, 1000, 0.8)
province:add_pop(aristocrat, bulgarian, orthodox, 1000, 0.7)
province:add_pop(clergymen, bulgarian, orthodox, 1000, 0.6)
province:add_pop(laborer, bulgarian, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, bulgarian, orthodox, 1000, 0.9)
province:add_nucleus(bulgaria)
province:add_nucleus(turkey)
province:give_to(turkey)