--------------------------------------------------------------
-- Continent: Europe
-- Subcontinent: Middle Europe
-- Country: Denmark
province = Province:new{ ref_name = "nordjylland", color = 0x7cb7ff }
province.name = _("Nordjylland")
province:register()
province:add_pop(artisan, danish, protestant, 5000, 0.9)
province:add_pop(farmer, danish, protestant, 40000, 0.8)
province:add_pop(soldier, danish, protestant, 8000, 0.8)
province:add_pop(craftsmen, danish, protestant, 5000, 0.9)
province:add_pop(bureaucrat, danish, protestant, 5000, 0.9)
province:add_pop(aristocrat, danish, protestant, 5000, 0.9)
province:add_pop(clergymen, danish, protestant, 5000, 0.9)
province:add_pop(laborer, danish, protestant, 50000, 0.8)
province:add_pop(entrepreneur, danish, protestant, 800, 0.9)
province:add_nucleus(denmark)
province:add_nucleus(scandinavia)
province:give_to(denmark)

province = Province:new{ ref_name = "midtjylland", color = 0xc972ff }
province.name = _("Midtjylland")
province:register()
province:add_pop(artisan, danish, protestant, 5000, 0.9)
province:add_pop(farmer, danish, protestant, 40000, 0.8)
province:add_pop(soldier, danish, protestant, 8000, 0.8)
province:add_pop(craftsmen, danish, protestant, 5000, 0.9)
province:add_pop(bureaucrat, danish, protestant, 5000, 0.9)
province:add_pop(aristocrat, danish, protestant, 5000, 0.9)
province:add_pop(clergymen, danish, protestant, 5000, 0.9)
province:add_pop(laborer, danish, protestant, 50000, 0.8)
province:add_pop(entrepreneur, danish, protestant, 800, 0.9)
province:add_nucleus(denmark)
province:add_nucleus(scandinavia)
province:give_to(denmark)

province = Province:new{ ref_name = "hedensted", color = 0xdcb2ff }
province.name = _("Hedensted")
province:register()
province:add_pop(artisan, danish, protestant, 5000, 0.9)
province:add_pop(farmer, danish, protestant, 40000, 0.8)
province:add_pop(soldier, danish, protestant, 8000, 0.8)
province:add_pop(craftsmen, danish, protestant, 5000, 0.9)
province:add_pop(bureaucrat, danish, protestant, 5000, 0.9)
province:add_pop(aristocrat, danish, protestant, 5000, 0.9)
province:add_pop(clergymen, danish, protestant, 5000, 0.9)
province:add_pop(laborer, danish, protestant, 50000, 0.8)
province:add_pop(entrepreneur, danish, protestant, 800, 0.9)
province:add_nucleus(denmark)
province:add_nucleus(scandinavia)
province:give_to(denmark)

province = Province:new{ ref_name = "syddanmark", color = 0xa3ddff }
province.name = _("Syddanmark")
province:register()
province:add_pop(artisan, danish, protestant, 5000, 0.9)
province:add_pop(farmer, danish, protestant, 40000, 0.8)
province:add_pop(soldier, danish, protestant, 8000, 0.8)
province:add_pop(craftsmen, danish, protestant, 5000, 0.9)
province:add_pop(bureaucrat, danish, protestant, 5000, 0.9)
province:add_pop(aristocrat, danish, protestant, 5000, 0.9)
province:add_pop(clergymen, danish, protestant, 5000, 0.9)
province:add_pop(laborer, danish, protestant, 50000, 0.8)
province:add_pop(entrepreneur, danish, protestant, 800, 0.9)
province:add_nucleus(denmark)
province:add_nucleus(scandinavia)
province:give_to(denmark)

province = Province:new{ ref_name = "odense", color = 0x84eeff }
province.name = _("Odense")
province:register()
province:add_pop(artisan, danish, protestant, 5000, 0.9)
province:add_pop(farmer, danish, protestant, 40000, 0.8)
province:add_pop(soldier, danish, protestant, 8000, 0.8)
province:add_pop(craftsmen, danish, protestant, 5000, 0.9)
province:add_pop(bureaucrat, danish, protestant, 5000, 0.9)
province:add_pop(aristocrat, danish, protestant, 5000, 0.9)
province:add_pop(clergymen, danish, protestant, 5000, 0.9)
province:add_pop(laborer, danish, protestant, 50000, 0.8)
province:add_pop(entrepreneur, danish, protestant, 800, 0.9)
province:add_nucleus(denmark)
province:add_nucleus(scandinavia)
province:give_to(denmark)

province = Province:new{ ref_name = "frederiksborg", color = 0x00d0ff }
province.name = _("Frederiksborg")
province:register()
province:add_pop(artisan, danish, protestant, 5000, 0.9)
province:add_pop(farmer, danish, protestant, 40000, 0.8)
province:add_pop(soldier, danish, protestant, 8000, 0.8)
province:add_pop(craftsmen, danish, protestant, 5000, 0.9)
province:add_pop(bureaucrat, danish, protestant, 5000, 0.9)
province:add_pop(aristocrat, danish, protestant, 5000, 0.9)
province:add_pop(clergymen, danish, protestant, 5000, 0.9)
province:add_pop(laborer, danish, protestant, 50000, 0.8)
province:add_pop(entrepreneur, danish, protestant, 800, 0.9)
province:add_nucleus(denmark)
province:add_nucleus(scandinavia)
province:give_to(denmark)
denmark:set_capital(province)