--------------------------------------------------------------
-- Continent: Europe
-- Subcontinent: Middle Europe
-- Country: France

province = Province:new{ ref_name = "finistere", color = 0x979939 }
province.name = _("Finistère")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(brittany)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "cotes_d_armor", color = 0xcf3be0 }
province.name = _("Côtes d' Armor")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(brittany)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "morbihan", color = 0x592dc0 }
province.name = _("Morbihan")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(brittany)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "ille_et_vilaine", color = 0x487f80 }
province.name = _("Ille et Vilaine")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(brittany)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "manche", color = 0x9f1da0 }
province.name = _("Manche")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(normandy)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "calvados", color = 0x301ec0 }
province.name = _("Calvados")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(normandy)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "orne", color = 0x994be1 }
province.name = _("Orne")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(normandy)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "eure", color = 0xca19c0 }
province.name = _("Eure")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(normandy)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "seine_maritime", color = 0x349ba0 }
province.name = _("Seine Maritime")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(normandy)
province:add_nucleus(france)
province:give_to(france)

--------------------------------------------------------------
-- Region: Southern France

province = Province:new{ ref_name = "alpes_maritimes", color = 0x469360 }
province.name = _("Alpes Maritimes")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(occitania)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "alpes_de_haute_provence", color = 0xa39b00 }
province.name = _("Alpes de Haute Provence")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(occitania)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "hautes_alpes", color = 0x2349a0 }
province.name = _("Hautes Alpes")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(occitania)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "var", color = 0xa8bcc0 }
province.name = _("Var")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(occitania)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "cannes", color = 0x372d00 }
province.name = _("Cannes")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(occitania)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "bouches_du_rhone", color = 0x3493e0 }
province.name = _("Bouches du Rhône")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(occitania)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "vaucluse", color = 0x1905a0 }
province.name = _("Vaucluse")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(occitania)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "gard", color = 0xb300c0 }
province.name = _("Gard")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(occitania)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "heraut", color = 0x2722c0 }
province.name = _("Hérault")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(occitania)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "lozere", color = 0xc6e420 }
province.name = _("Lozère")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(occitania)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "aveyron", color = 0x1a61cc }
province.name = _("Aveyron")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(occitania)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "tarn", color = 0x3c4f20 }
province.name = _("Tarn")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(occitania)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "lot", color = 0x8a95a0 }
province.name = _("Lot")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(occitania)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "tarn_et_garonne", color = 0x20b880 }
province.name = _("Tarn et Garonne")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(occitania)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "gers", color = 0xb59200 }
province.name = _("Gers")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(occitania)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "hautes_pyrenees", color = 0xdc10a0 }
province.name = _("Hautes Pyrénées")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(occitania)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "haute_garonne", color = 0x391a00 }
province.name = _("Haute_Garonne")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(occitania)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "ariege", color = 0x69dd20 }
province.name = _("Ariège")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(occitania)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "aude", color = 0xe50ba0 }
province.name = _("Aude")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(occitania)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "pyrenees_orientales", color = 0x4f8e40 }
province.name = _("Pyrénées Orientales")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "savoie", color = 0x4e45e0 }
province.name = _("Savoie")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(france)
province:give_to(france)

province = Province:new{ ref_name = "haute_savoie", color = 0xb96b20 }
province.name = _("Haute Savoie")
province:register()
province:add_pop(artisan, french, catholic, 5000, 0.9)
province:add_pop(farmer, french, catholic, 40000, 0.8)
province:add_pop(soldier, french, catholic, 8000, 0.8)
province:add_pop(craftsmen, french, catholic, 5000, 0.9)
province:add_pop(bureaucrat, french, catholic, 5000, 0.9)
province:add_pop(aristocrat, french, catholic, 5000, 0.9)
province:add_pop(clergymen, french, catholic, 5000, 0.9)
province:add_pop(laborer, french, catholic, 50000, 0.8)
province:add_pop(entrepreneur, french, catholic, 800, 0.9)
province:add_nucleus(france)
province:give_to(france)

-- TODO: Rest of france, we just have done brittany, southern france and normandy