--------------------------------------------------------------
-- Continent: Europe
-- Subcontinent: Balkan
-- Country: Greece
province = Province:new{ ref_name = "cyclades", color = 0xef42ff }
province.name = _("Cyclades")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "evia", color = 0x3fff62 }
province.name = _("Evia")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "dodecanese", color = 0xff3a5e }
province.name = _("Dodecanese")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "skopelos", color = 0xff7a83 }
province.name = _("Skopelos")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "plomari", color = 0x4cffff }
province.name = _("Plomari")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "attika", color = 0x5842ff }
province.name = _("Attika")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "korinthia", color = 0xeff400 }
province.name = _("Korinthia")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "thives", color = 0xc58cff }
province.name = _("Thives")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "valtos", color = 0xff2b7c }
province.name = _("Valtos")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "zakynthos", color = 0xeeff56 }
province.name = _("Zakynthos")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "korfu", color = 0xf882ff }
province.name = _("Korfu")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "sami", color = 0xff8572 }
province.name = _("Sami")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "chalkidi", color = 0x554cff }
province.name = _("Chalkidi")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "tyrnavos", color = 0xff4261 }
province.name = _("Tyrnavos")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "pieria", color = 0xcdff87 }
province.name = _("Pieria")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "kythira", color = 0x7cbbff }
province.name = _("Kythira")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(greece)

province = Province:new{ ref_name = "kalymnos", color = 0xbdff7f }
province.name = _("Kalymnos")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "ikaria", color = 0x9763ff }
province.name = _("Ikaria")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "samos", color = 0xff5f56 }
province.name = _("Samos")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "thasos", color = 0xff30b6 }
province.name = _("Thasos")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "lakedemona", color = 0x70ff9d }
province.name = _("Lakedemona")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(greece)

province = Province:new{ ref_name = "patras", color = 0xff42c9 }
province.name = _("Patras")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(greece)

province = Province:new{ ref_name = "thessaly", color = 0xd5ffb7 }
province.name = _("Thessaly")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "lefkada", color = 0xff7587 }
province.name = _("Lefkada")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "dodoni", color = 0xad6bff }
province.name = _("Dodoni")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "thessalonki", color = 0xfffdce }
province.name = _("Thessalonki")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "drama", color = 0xffad7a }
province.name = _("Drama")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "grevena", color = 0xffe0f4 }
province.name = _("Grevena")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

province = Province:new{ ref_name = "florina", color = 0x7fffee }
province.name = _("Florina")
province:register()
province:add_pop(artisan, greek, orthodox, 1000, 0.6)
province:add_pop(farmer, greek, orthodox, 5000, 0.2)
province:add_pop(soldier, greek, orthodox, 1000, 0.6)
province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
province:add_pop(laborer, greek, orthodox, 1000, 0.4)
province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
province:add_pop(artisan, greek, catholic, 100, 0.6)
province:add_pop(farmer, greek, catholic, 5000, 0.2)
province:add_pop(soldier, greek, catholic, 100, 0.6)
province:add_pop(craftsmen, greek, catholic, 100, 0.4)
province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
province:add_pop(aristocrat, greek, catholic, 100, 0.7)
province:add_pop(clergymen, greek, catholic, 100, 0.6)
province:add_pop(laborer, greek, catholic, 100, 0.4)
province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
province:add_pop(artisan, turkish, islamic, 50, 0.6)
province:add_pop(farmer, turkish, islamic, 500, 0.2)
province:add_pop(soldier, turkish, islamic, 50, 0.6)
province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
province:add_pop(clergymen, turkish, islamic, 50, 0.6)
province:add_pop(laborer, turkish, islamic, 50, 0.4)
province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
province:add_nucleus(turkey)
province:add_nucleus(greece)
province:give_to(turkey)

-- province = Province:new{ ref_name = "agio_oros", color = 0x9bd3ff }
-- province.name = _("Agio Oros")
-- province:register()
-- province:add_pop(artisan, greek, orthodox, 1000, 0.6)
-- province:add_pop(farmer, greek, orthodox, 5000, 0.2)
-- province:add_pop(soldier, greek, orthodox, 1000, 0.6)
-- province:add_pop(craftsmen, greek, orthodox, 1000, 0.4)
-- province:add_pop(bureaucrat, greek, orthodox, 1000, 0.8)
-- province:add_pop(aristocrat, greek, orthodox, 1000, 0.7)
-- province:add_pop(clergymen, greek, orthodox, 1000, 0.6)
-- province:add_pop(laborer, greek, orthodox, 1000, 0.4)
-- province:add_pop(entrepreneur, greek, orthodox, 1000, 0.9)
-- province:add_pop(artisan, greek, catholic, 100, 0.6)
-- province:add_pop(farmer, greek, catholic, 5000, 0.2)
-- province:add_pop(soldier, greek, catholic, 100, 0.6)
-- province:add_pop(craftsmen, greek, catholic, 100, 0.4)
-- province:add_pop(bureaucrat, greek, catholic, 100, 0.8)
-- province:add_pop(aristocrat, greek, catholic, 100, 0.7)
-- province:add_pop(clergymen, greek, catholic, 100, 0.6)
-- province:add_pop(laborer, greek, catholic, 100, 0.4)
-- province:add_pop(entrepreneur, greek, catholic, 100, 0.9)
-- province:add_pop(artisan, turkish, islamic, 50, 0.6)
-- province:add_pop(farmer, turkish, islamic, 500, 0.2)
-- province:add_pop(soldier, turkish, islamic, 50, 0.6)
-- province:add_pop(craftsmen, turkish, islamic, 50, 0.4)
-- province:add_pop(bureaucrat, turkish, islamic, 50, 0.8)
-- province:add_pop(aristocrat, turkish, islamic, 50, 0.7)
-- province:add_pop(clergymen, turkish, islamic, 50, 0.6)
-- province:add_pop(laborer, turkish, islamic, 50, 0.4)
-- province:add_pop(entrepreneur, turkish, islamic, 10, 0.9)
-- province:add_nucleus(turkey)
-- province:add_nucleus(greece)
-- province:give_to(turkey)