--------------------------------------------------------------
-- Continent: Europe
-- Subcontinent: Iberia
-- Country: Portugal
--Porto
province = Province:new{ ref_name = "porto", color = 0xae4da1 }
province.name = _("Porto")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, portuguese, catholic, 5000, 0.9)
province:add_pop(farmer, portuguese, catholic, 40000, 0.8)
province:add_pop(soldier, portuguese, catholic, 8000, 0.8)
province:add_pop(craftsmen, portuguese, catholic, 5000, 0.9)
province:add_pop(bureaucrat, portuguese, catholic, 5000, 0.9)
province:add_pop(aristocrat, portuguese, catholic, 5000, 0.9)
province:add_pop(clergymen, portuguese, catholic, 5000, 0.9)
province:add_pop(laborer, portuguese, catholic, 50000, 0.8)
province:add_pop(entrepreneur, portuguese, catholic, 800, 0.9)
province:add_nucleus(portugal)
province:add_nucleus(iberia)
province:give_to(portugal)

--Villa Real
province = Province:new{ ref_name = "villa_real", color = 0xae7ea1 }
province.name = _("Villa Real")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, portuguese, catholic, 5000, 0.9)
province:add_pop(farmer, portuguese, catholic, 40000, 0.8)
province:add_pop(soldier, portuguese, catholic, 8000, 0.8)
province:add_pop(craftsmen, portuguese, catholic, 5000, 0.9)
province:add_pop(bureaucrat, portuguese, catholic, 5000, 0.9)
province:add_pop(aristocrat, portuguese, catholic, 5000, 0.9)
province:add_pop(clergymen, portuguese, catholic, 5000, 0.9)
province:add_pop(laborer, portuguese, catholic, 50000, 0.8)
province:add_pop(entrepreneur, portuguese, catholic, 800, 0.9)
province:add_nucleus(portugal)
province:add_nucleus(iberia)
province:give_to(portugal)

--Aveiro
province = Province:new{ ref_name = "aveiro", color = 0x9d7a79 }
province.name = _("Aveiro")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, portuguese, catholic, 5000, 0.9)
province:add_pop(farmer, portuguese, catholic, 40000, 0.8)
province:add_pop(soldier, portuguese, catholic, 8000, 0.8)
province:add_pop(craftsmen, portuguese, catholic, 5000, 0.9)
province:add_pop(bureaucrat, portuguese, catholic, 5000, 0.9)
province:add_pop(aristocrat, portuguese, catholic, 5000, 0.9)
province:add_pop(clergymen, portuguese, catholic, 5000, 0.9)
province:add_pop(laborer, portuguese, catholic, 50000, 0.8)
province:add_pop(entrepreneur, portuguese, catholic, 800, 0.9)
province:add_nucleus(portugal)
province:add_nucleus(iberia)
province:give_to(portugal)

--Guarda
province = Province:new{ ref_name = "guarda", color = 0x9d6b9f }
province.name = _("Guarda")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, portuguese, catholic, 5000, 0.9)
province:add_pop(farmer, portuguese, catholic, 40000, 0.8)
province:add_pop(soldier, portuguese, catholic, 8000, 0.8)
province:add_pop(craftsmen, portuguese, catholic, 5000, 0.9)
province:add_pop(bureaucrat, portuguese, catholic, 5000, 0.9)
province:add_pop(aristocrat, portuguese, catholic, 5000, 0.9)
province:add_pop(clergymen, portuguese, catholic, 5000, 0.9)
province:add_pop(laborer, portuguese, catholic, 50000, 0.8)
province:add_pop(entrepreneur, portuguese, catholic, 800, 0.9)
province:add_nucleus(portugal)
province:add_nucleus(iberia)
province:give_to(portugal)

--Lisbon
province = Province:new{ ref_name = "lisbon", color = 0x86549f }
province.name = _("Lisbon")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, portuguese, catholic, 5000, 0.9)
province:add_pop(farmer, portuguese, catholic, 40000, 0.8)
province:add_pop(soldier, portuguese, catholic, 8000, 0.8)
province:add_pop(craftsmen, portuguese, catholic, 5000, 0.9)
province:add_pop(bureaucrat, portuguese, catholic, 5000, 0.9)
province:add_pop(aristocrat, portuguese, catholic, 5000, 0.9)
province:add_pop(clergymen, portuguese, catholic, 5000, 0.9)
province:add_pop(laborer, portuguese, catholic, 50000, 0.8)
province:add_pop(entrepreneur, portuguese, catholic, 800, 0.9)
province:add_nucleus(portugal)
province:add_nucleus(iberia)
province:give_to(portugal)

--Évora
province = Province:new{ ref_name = "evora", color = 0x9d6c90 }
province.name = _("Évora")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, portuguese, catholic, 5000, 0.9)
province:add_pop(farmer, portuguese, catholic, 40000, 0.8)
province:add_pop(soldier, portuguese, catholic, 8000, 0.8)
province:add_pop(craftsmen, portuguese, catholic, 5000, 0.9)
province:add_pop(bureaucrat, portuguese, catholic, 5000, 0.9)
province:add_pop(aristocrat, portuguese, catholic, 5000, 0.9)
province:add_pop(clergymen, portuguese, catholic, 5000, 0.9)
province:add_pop(laborer, portuguese, catholic, 50000, 0.8)
province:add_pop(entrepreneur, portuguese, catholic, 800, 0.9)
province:add_nucleus(portugal)
province:add_nucleus(iberia)
province:give_to(portugal)

--Faro
province = Province:new{ ref_name = "faro", color = 0x9d3c90 }
province.name = _("Faro")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, portuguese, catholic, 5000, 0.9)
province:add_pop(farmer, portuguese, catholic, 40000, 0.8)
province:add_pop(soldier, portuguese, catholic, 8000, 0.8)
province:add_pop(craftsmen, portuguese, catholic, 5000, 0.9)
province:add_pop(bureaucrat, portuguese, catholic, 5000, 0.9)
province:add_pop(aristocrat, portuguese, catholic, 5000, 0.9)
province:add_pop(clergymen, portuguese, catholic, 5000, 0.9)
province:add_pop(laborer, portuguese, catholic, 50000, 0.8)
province:add_pop(entrepreneur, portuguese, catholic, 800, 0.9)
province:add_nucleus(portugal)
province:add_nucleus(iberia)
province:give_to(portugal)