--------------------------------------------------------------
-- Continent: Americas
-- Subcontinent: North America
-- Country: Denmark (Greenland)
province = Province:new{ ref_name = "nuuk", color = 0xff8efd }
province.name = _("Nuuk")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(bureaucrat, danish, protestant, 2, 0.8)
province:add_pop(clergymen, danish, protestant, 5, 0.8)
province:add_pop(laborer, danish, protestant, 50, 0.5)
province:add_nucleus(denmark)
province:give_to(denmark)

province = Province:new{ ref_name = "qanaaq", color = 0x6bffb0 }
province.name = _("Qanaaq")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(bureaucrat, danish, protestant, 2, 0.8)
province:add_pop(clergymen, danish, protestant, 5, 0.8)
province:add_pop(laborer, danish, protestant, 50, 0.5)
province:add_nucleus(denmark)
province:give_to(denmark)

province = Province:new{ ref_name = "tasiilaq", color = 0xffbcbd }
province.name = _("Tasiilaq")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(bureaucrat, danish, protestant, 2, 0.8)
province:add_pop(clergymen, danish, protestant, 5, 0.8)
province:add_pop(laborer, danish, protestant, 50, 0.5)
province:add_nucleus(denmark)
province:give_to(denmark)

province = Province:new{ ref_name = "artic_greenland", color = 0x568eff }
province.name = _("Artic Greenland")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(bureaucrat, danish, protestant, 2, 0.8)
province:add_pop(clergymen, danish, protestant, 5, 0.8)
province:add_pop(laborer, danish, protestant, 50, 0.5)
province:add_nucleus(denmark)
province:give_to(denmark)

--------------------------------------------------------------
-- Continent: Europe
-- Subcontinent: Scandinavia
-- Country: Iceland
province = Province:new{ ref_name = "austurland", color = 0x9effae }
province.name = _("Austurland")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(bureaucrat, icelandic, protestant, 2, 0.8)
province:add_pop(clergymen, icelandic, protestant, 5, 0.8)
province:add_pop(laborer, icelandic, protestant, 50, 0.5)
province:add_nucleus(iceland)
province:add_nucleus(denmark)
province:give_to(denmark)
province = Province:new{ ref_name = "norourland_eystra", color = 0x2723ff }
province.name = _("Norðurland eystra")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(bureaucrat, icelandic, protestant, 2, 0.8)
province:add_pop(clergymen, icelandic, protestant, 5, 0.8)
province:add_pop(laborer, icelandic, protestant, 50, 0.5)
province:add_nucleus(iceland)
province:add_nucleus(denmark)
province:give_to(denmark)
province = Province:new{ ref_name = "hofouborgarsvaeoio", color = 0xff0720 }
province.name = _("Höfuðborgarsvæðið")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(bureaucrat, icelandic, protestant, 2, 0.8)
province:add_pop(clergymen, icelandic, protestant, 5, 0.8)
province:add_pop(laborer, icelandic, protestant, 50, 0.5)
province:add_nucleus(iceland)
province:add_nucleus(denmark)
province:give_to(denmark)
province = Province:new{ ref_name = "suorland", color = 0xffb2d6 }
province.name = _("Suðurland")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(bureaucrat, icelandic, protestant, 2, 0.8)
province:add_pop(clergymen, icelandic, protestant, 5, 0.8)
province:add_pop(laborer, icelandic, protestant, 50, 0.5)
province:add_nucleus(iceland)
province:add_nucleus(denmark)
province:give_to(denmark)
province = Province:new{ ref_name = "vestfiroir", color = 0x87ffda }
province.name = _("Vestfirðir")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(bureaucrat, icelandic, protestant, 2, 0.8)
province:add_pop(clergymen, icelandic, protestant, 5, 0.8)
province:add_pop(laborer, icelandic, protestant, 50, 0.5)
province:add_nucleus(iceland)
province:add_nucleus(denmark)
province:give_to(denmark)
province = Province:new{ ref_name = "vesturland", color = 0xba75ff }
province.name = _("Vesturland")
province:register()
province:add_industry(wheat_farm, russia, andes_transport)
province:add_pop(bureaucrat, icelandic, protestant, 2, 0.8)
province:add_pop(clergymen, icelandic, protestant, 5, 0.8)
province:add_pop(laborer, icelandic, protestant, 50, 0.5)
province:add_nucleus(iceland)
province:add_nucleus(denmark)
province:give_to(denmark)

--------------------------------------------------------------
-- Continent: Europe
-- Subcontinent: Scandinavia
-- Country: Sweden
province = Province:new{ ref_name = "lappland", color = 0x0cdaff }
province.name = _("Lappland")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, swedish, protestant, 5000, 0.9)
province:add_pop(farmer, swedish, protestant, 40000, 0.8)
province:add_pop(soldier, swedish, protestant, 8000, 0.8)
province:add_pop(craftsmen, swedish, protestant, 5000, 0.9)
province:add_pop(bureaucrat, swedish, protestant, 5000, 0.9)
province:add_pop(burgeoise, swedish, protestant, 5000, 0.9)
province:add_pop(clergymen, swedish, protestant, 5000, 0.9)
province:add_pop(laborer, swedish, protestant, 50000, 0.8)
province:add_pop(burgeoise, swedish, protestant, 800, 0.9)
province:add_nucleus(sweden)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "vasterbotten", color = 0xff6bc3 }
province.name = _("Västerbotten")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, swedish, protestant, 5000, 0.9)
province:add_pop(farmer, swedish, protestant, 40000, 0.8)
province:add_pop(soldier, swedish, protestant, 8000, 0.8)
province:add_pop(craftsmen, swedish, protestant, 5000, 0.9)
province:add_pop(bureaucrat, swedish, protestant, 5000, 0.9)
province:add_pop(burgeoise, swedish, protestant, 5000, 0.9)
province:add_pop(clergymen, swedish, protestant, 5000, 0.9)
province:add_pop(laborer, swedish, protestant, 50000, 0.8)
province:add_pop(burgeoise, swedish, protestant, 800, 0.9)
province:add_nucleus(sweden)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "halsingland", color = 0xecffaf }
province.name = _("Hälsingland")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, swedish, protestant, 5000, 0.9)
province:add_pop(farmer, swedish, protestant, 40000, 0.8)
province:add_pop(soldier, swedish, protestant, 8000, 0.8)
province:add_pop(craftsmen, swedish, protestant, 5000, 0.9)
province:add_pop(bureaucrat, swedish, protestant, 5000, 0.9)
province:add_pop(burgeoise, swedish, protestant, 5000, 0.9)
province:add_pop(clergymen, swedish, protestant, 5000, 0.9)
province:add_pop(laborer, swedish, protestant, 50000, 0.8)
province:add_pop(burgeoise, swedish, protestant, 800, 0.9)
province:add_nucleus(sweden)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "uppland", color = 0xea82ff }
province.name = _("Uppland")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, swedish, protestant, 5000, 0.9)
province:add_pop(farmer, swedish, protestant, 40000, 0.8)
province:add_pop(soldier, swedish, protestant, 8000, 0.8)
province:add_pop(craftsmen, swedish, protestant, 5000, 0.9)
province:add_pop(bureaucrat, swedish, protestant, 5000, 0.9)
province:add_pop(burgeoise, swedish, protestant, 5000, 0.9)
province:add_pop(clergymen, swedish, protestant, 5000, 0.9)
province:add_pop(laborer, swedish, protestant, 50000, 0.8)
province:add_pop(burgeoise, swedish, protestant, 800, 0.9)
province:add_nucleus(sweden)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "gotland", color = 0x00ff26 }
province.name = _("Gotland")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, swedish, protestant, 5000, 0.9)
province:add_pop(farmer, swedish, protestant, 40000, 0.8)
province:add_pop(soldier, swedish, protestant, 8000, 0.8)
province:add_pop(craftsmen, swedish, protestant, 5000, 0.9)
province:add_pop(bureaucrat, swedish, protestant, 5000, 0.9)
province:add_pop(burgeoise, swedish, protestant, 5000, 0.9)
province:add_pop(clergymen, swedish, protestant, 5000, 0.9)
province:add_pop(laborer, swedish, protestant, 50000, 0.8)
province:add_pop(burgeoise, swedish, protestant, 800, 0.9)
province:add_nucleus(sweden)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "oland", color = 0x622dff }
province.name = _("Öland")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, swedish, protestant, 5000, 0.9)
province:add_pop(farmer, swedish, protestant, 40000, 0.8)
province:add_pop(soldier, swedish, protestant, 8000, 0.8)
province:add_pop(craftsmen, swedish, protestant, 5000, 0.9)
province:add_pop(bureaucrat, swedish, protestant, 5000, 0.9)
province:add_pop(burgeoise, swedish, protestant, 5000, 0.9)
province:add_pop(clergymen, swedish, protestant, 5000, 0.9)
province:add_pop(laborer, swedish, protestant, 50000, 0.8)
province:add_pop(burgeoise, swedish, protestant, 800, 0.9)
province:add_nucleus(sweden)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "smaland", color = 0xa3fff4 }
province.name = _("Småland")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, swedish, protestant, 5000, 0.9)
province:add_pop(farmer, swedish, protestant, 40000, 0.8)
province:add_pop(soldier, swedish, protestant, 8000, 0.8)
province:add_pop(craftsmen, swedish, protestant, 5000, 0.9)
province:add_pop(bureaucrat, swedish, protestant, 5000, 0.9)
province:add_pop(burgeoise, swedish, protestant, 5000, 0.9)
province:add_pop(clergymen, swedish, protestant, 5000, 0.9)
province:add_pop(laborer, swedish, protestant, 50000, 0.8)
province:add_pop(burgeoise, swedish, protestant, 800, 0.9)
province:add_nucleus(sweden)
province:add_nucleus(scandinavia)
province:give_to(sweden)
sweden:set_capital(province)
scandinavia:set_capital(province)

province = Province:new{ ref_name = "vastersmaland", color = 0xd400ff }
province.name = _("Västersmåland")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, swedish, protestant, 5000, 0.9)
province:add_pop(farmer, swedish, protestant, 40000, 0.8)
province:add_pop(soldier, swedish, protestant, 8000, 0.8)
province:add_pop(craftsmen, swedish, protestant, 5000, 0.9)
province:add_pop(bureaucrat, swedish, protestant, 5000, 0.9)
province:add_pop(burgeoise, swedish, protestant, 5000, 0.9)
province:add_pop(clergymen, swedish, protestant, 5000, 0.9)
province:add_pop(laborer, swedish, protestant, 50000, 0.8)
province:add_pop(burgeoise, swedish, protestant, 800, 0.9)
province:add_nucleus(sweden)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "bohusland", color = 0xceb2ff }
province.name = _("Bohuslän")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, swedish, protestant, 5000, 0.9)
province:add_pop(farmer, swedish, protestant, 40000, 0.8)
province:add_pop(soldier, swedish, protestant, 8000, 0.8)
province:add_pop(craftsmen, swedish, protestant, 5000, 0.9)
province:add_pop(bureaucrat, swedish, protestant, 5000, 0.9)
province:add_pop(burgeoise, swedish, protestant, 5000, 0.9)
province:add_pop(clergymen, swedish, protestant, 5000, 0.9)
province:add_pop(laborer, swedish, protestant, 50000, 0.8)
province:add_pop(burgeoise, swedish, protestant, 800, 0.9)
province:add_nucleus(sweden)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "vastergotland", color = 0x1000ff }
province.name = _("Västergötland")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, swedish, protestant, 5000, 0.9)
province:add_pop(farmer, swedish, protestant, 40000, 0.8)
province:add_pop(soldier, swedish, protestant, 8000, 0.8)
province:add_pop(craftsmen, swedish, protestant, 5000, 0.9)
province:add_pop(bureaucrat, swedish, protestant, 5000, 0.9)
province:add_pop(burgeoise, swedish, protestant, 5000, 0.9)
province:add_pop(clergymen, swedish, protestant, 5000, 0.9)
province:add_pop(laborer, swedish, protestant, 50000, 0.8)
province:add_pop(burgeoise, swedish, protestant, 800, 0.9)
province:add_nucleus(sweden)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "varmland", color = 0xff7fdd }
province.name = _("Värmland")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, swedish, protestant, 5000, 0.9)
province:add_pop(farmer, swedish, protestant, 40000, 0.8)
province:add_pop(soldier, swedish, protestant, 8000, 0.8)
province:add_pop(craftsmen, swedish, protestant, 5000, 0.9)
province:add_pop(bureaucrat, swedish, protestant, 5000, 0.9)
province:add_pop(burgeoise, swedish, protestant, 5000, 0.9)
province:add_pop(clergymen, swedish, protestant, 5000, 0.9)
province:add_pop(laborer, swedish, protestant, 50000, 0.8)
province:add_pop(burgeoise, swedish, protestant, 800, 0.9)
province:add_nucleus(sweden)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "dalarna", color = 0x7ae6ff }
province.name = _("Dalarna")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, swedish, protestant, 5000, 0.9)
province:add_pop(farmer, swedish, protestant, 40000, 0.8)
province:add_pop(soldier, swedish, protestant, 8000, 0.8)
province:add_pop(craftsmen, swedish, protestant, 5000, 0.9)
province:add_pop(bureaucrat, swedish, protestant, 5000, 0.9)
province:add_pop(burgeoise, swedish, protestant, 5000, 0.9)
province:add_pop(clergymen, swedish, protestant, 5000, 0.9)
province:add_pop(laborer, swedish, protestant, 50000, 0.8)
province:add_pop(burgeoise, swedish, protestant, 800, 0.9)
province:add_nucleus(sweden)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "jamtland", color = 0x82abff }
province.name = _("Jämtland")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, swedish, protestant, 5000, 0.9)
province:add_pop(farmer, swedish, protestant, 40000, 0.8)
province:add_pop(soldier, swedish, protestant, 8000, 0.8)
province:add_pop(craftsmen, swedish, protestant, 5000, 0.9)
province:add_pop(bureaucrat, swedish, protestant, 5000, 0.9)
province:add_pop(burgeoise, swedish, protestant, 5000, 0.9)
province:add_pop(clergymen, swedish, protestant, 5000, 0.9)
province:add_pop(laborer, swedish, protestant, 50000, 0.8)
province:add_pop(burgeoise, swedish, protestant, 800, 0.9)
province:add_nucleus(sweden)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "skane", color = 0xff5b84 }
province.name = _("Skåne")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, swedish, protestant, 5000, 0.9)
province:add_pop(farmer, swedish, protestant, 40000, 0.8)
province:add_pop(soldier, swedish, protestant, 8000, 0.8)
province:add_pop(craftsmen, swedish, protestant, 5000, 0.9)
province:add_pop(bureaucrat, swedish, protestant, 5000, 0.9)
province:add_pop(burgeoise, swedish, protestant, 5000, 0.9)
province:add_pop(clergymen, swedish, protestant, 5000, 0.9)
province:add_pop(laborer, swedish, protestant, 50000, 0.8)
province:add_pop(burgeoise, swedish, protestant, 800, 0.9)
province:add_nucleus(denmark)
province:add_nucleus(sweden)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "blekinge", color = 0x84ff92 }
province.name = _("Blekinge")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, swedish, protestant, 5000, 0.9)
province:add_pop(farmer, swedish, protestant, 40000, 0.8)
province:add_pop(soldier, swedish, protestant, 8000, 0.8)
province:add_pop(craftsmen, swedish, protestant, 5000, 0.9)
province:add_pop(bureaucrat, swedish, protestant, 5000, 0.9)
province:add_pop(burgeoise, swedish, protestant, 5000, 0.9)
province:add_pop(clergymen, swedish, protestant, 5000, 0.9)
province:add_pop(laborer, swedish, protestant, 50000, 0.8)
province:add_pop(burgeoise, swedish, protestant, 800, 0.9)
province:add_nucleus(denmark)
province:add_nucleus(sweden)
province:add_nucleus(scandinavia)
province:give_to(sweden)

--------------------------------------------------------------
-- Continent: Europe
-- Subcontinent: Scandinavia
-- Country: Finland (Russia)
province = Province:new{ ref_name = "uusimaa", color = 0x70d1ff }
province.name = _("Uusimaa")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, russian, orthodox, 5000, 0.9)
province:add_pop(farmer, russian, orthodox, 40000, 0.8)
province:add_pop(soldier, russian, orthodox, 8000, 0.8)
province:add_pop(craftsmen, russian, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, russian, orthodox, 5000, 0.9)
province:add_pop(burgeoise, russian, orthodox, 5000, 0.9)
province:add_pop(clergymen, russian, orthodox, 5000, 0.9)
province:add_pop(laborer, russian, orthodox, 50000, 0.8)
province:add_pop(burgeoise, russian, orthodox, 800, 0.9)
province:add_pop(artisan, finnish, orthodox, 5000, 0.9)
province:add_pop(farmer, finnish, orthodox, 40000, 0.8)
province:add_pop(soldier, finnish, orthodox, 8000, 0.8)
province:add_pop(craftsmen, finnish, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, finnish, orthodox, 5000, 0.9)
province:add_pop(burgeoise, finnish, orthodox, 5000, 0.9)
province:add_pop(clergymen, finnish, orthodox, 5000, 0.9)
province:add_pop(laborer, finnish, orthodox, 50000, 0.8)
province:add_pop(burgeoise, finnish, orthodox, 800, 0.9)
province:add_nucleus(finland)
province:add_nucleus(russia)
province:add_nucleus(scandinavia)
province:give_to(russia)

province = Province:new{ ref_name = "kymi", color = 0x00ffb2 }
province.name = _("Kymi")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, russian, orthodox, 5000, 0.9)
province:add_pop(farmer, russian, orthodox, 40000, 0.8)
province:add_pop(soldier, russian, orthodox, 8000, 0.8)
province:add_pop(craftsmen, russian, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, russian, orthodox, 5000, 0.9)
province:add_pop(burgeoise, russian, orthodox, 5000, 0.9)
province:add_pop(clergymen, russian, orthodox, 5000, 0.9)
province:add_pop(laborer, russian, orthodox, 50000, 0.8)
province:add_pop(burgeoise, russian, orthodox, 800, 0.9)
province:add_pop(artisan, finnish, orthodox, 5000, 0.9)
province:add_pop(farmer, finnish, orthodox, 40000, 0.8)
province:add_pop(soldier, finnish, orthodox, 8000, 0.8)
province:add_pop(craftsmen, finnish, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, finnish, orthodox, 5000, 0.9)
province:add_pop(burgeoise, finnish, orthodox, 5000, 0.9)
province:add_pop(clergymen, finnish, orthodox, 5000, 0.9)
province:add_pop(laborer, finnish, orthodox, 50000, 0.8)
province:add_pop(burgeoise, finnish, orthodox, 800, 0.9)
province:add_nucleus(finland)
province:add_nucleus(russia)
province:add_nucleus(scandinavia)
province:give_to(russia)

province = Province:new{ ref_name = "north_karelia", color = 0xe5ff75 }
province.name = _("North Karelia")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, russian, orthodox, 5000, 0.9)
province:add_pop(farmer, russian, orthodox, 40000, 0.8)
province:add_pop(soldier, russian, orthodox, 8000, 0.8)
province:add_pop(craftsmen, russian, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, russian, orthodox, 5000, 0.9)
province:add_pop(burgeoise, russian, orthodox, 5000, 0.9)
province:add_pop(clergymen, russian, orthodox, 5000, 0.9)
province:add_pop(laborer, russian, orthodox, 50000, 0.8)
province:add_pop(burgeoise, russian, orthodox, 800, 0.9)
province:add_pop(artisan, finnish, orthodox, 5000, 0.9)
province:add_pop(farmer, finnish, orthodox, 40000, 0.8)
province:add_pop(soldier, finnish, orthodox, 8000, 0.8)
province:add_pop(craftsmen, finnish, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, finnish, orthodox, 5000, 0.9)
province:add_pop(burgeoise, finnish, orthodox, 5000, 0.9)
province:add_pop(clergymen, finnish, orthodox, 5000, 0.9)
province:add_pop(laborer, finnish, orthodox, 50000, 0.8)
province:add_pop(burgeoise, finnish, orthodox, 800, 0.9)
province:add_nucleus(finland)
province:add_nucleus(russia)
province:add_nucleus(scandinavia)
province:give_to(russia)

province = Province:new{ ref_name = "mikkeli", color = 0xf95bff }
province.name = _("Mikkeli")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, russian, orthodox, 5000, 0.9)
province:add_pop(farmer, russian, orthodox, 40000, 0.8)
province:add_pop(soldier, russian, orthodox, 8000, 0.8)
province:add_pop(craftsmen, russian, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, russian, orthodox, 5000, 0.9)
province:add_pop(burgeoise, russian, orthodox, 5000, 0.9)
province:add_pop(clergymen, russian, orthodox, 5000, 0.9)
province:add_pop(laborer, russian, orthodox, 50000, 0.8)
province:add_pop(burgeoise, russian, orthodox, 800, 0.9)
province:add_pop(artisan, finnish, orthodox, 5000, 0.9)
province:add_pop(farmer, finnish, orthodox, 40000, 0.8)
province:add_pop(soldier, finnish, orthodox, 8000, 0.8)
province:add_pop(craftsmen, finnish, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, finnish, orthodox, 5000, 0.9)
province:add_pop(burgeoise, finnish, orthodox, 5000, 0.9)
province:add_pop(clergymen, finnish, orthodox, 5000, 0.9)
province:add_pop(laborer, finnish, orthodox, 50000, 0.8)
province:add_pop(burgeoise, finnish, orthodox, 800, 0.9)
province:add_nucleus(finland)
province:add_nucleus(russia)
province:add_nucleus(scandinavia)
province:give_to(russia)

province = Province:new{ ref_name = "kuopio", color = 0x91ffc6 }
province.name = _("Kuopio")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, russian, orthodox, 5000, 0.9)
province:add_pop(farmer, russian, orthodox, 40000, 0.8)
province:add_pop(soldier, russian, orthodox, 8000, 0.8)
province:add_pop(craftsmen, russian, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, russian, orthodox, 5000, 0.9)
province:add_pop(burgeoise, russian, orthodox, 5000, 0.9)
province:add_pop(clergymen, russian, orthodox, 5000, 0.9)
province:add_pop(laborer, russian, orthodox, 50000, 0.8)
province:add_pop(burgeoise, russian, orthodox, 800, 0.9)
province:add_pop(artisan, finnish, orthodox, 5000, 0.9)
province:add_pop(farmer, finnish, orthodox, 40000, 0.8)
province:add_pop(soldier, finnish, orthodox, 8000, 0.8)
province:add_pop(craftsmen, finnish, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, finnish, orthodox, 5000, 0.9)
province:add_pop(burgeoise, finnish, orthodox, 5000, 0.9)
province:add_pop(clergymen, finnish, orthodox, 5000, 0.9)
province:add_pop(laborer, finnish, orthodox, 50000, 0.8)
province:add_pop(burgeoise, finnish, orthodox, 800, 0.9)
province:add_nucleus(finland)
province:add_nucleus(russia)
province:add_nucleus(scandinavia)
province:give_to(russia)

province = Province:new{ ref_name = "hame", color = 0xa3fff1 }
province.name = _("Häme")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, russian, orthodox, 5000, 0.9)
province:add_pop(farmer, russian, orthodox, 40000, 0.8)
province:add_pop(soldier, russian, orthodox, 8000, 0.8)
province:add_pop(craftsmen, russian, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, russian, orthodox, 5000, 0.9)
province:add_pop(burgeoise, russian, orthodox, 5000, 0.9)
province:add_pop(clergymen, russian, orthodox, 5000, 0.9)
province:add_pop(laborer, russian, orthodox, 50000, 0.8)
province:add_pop(burgeoise, russian, orthodox, 800, 0.9)
province:add_pop(artisan, finnish, orthodox, 5000, 0.9)
province:add_pop(farmer, finnish, orthodox, 40000, 0.8)
province:add_pop(soldier, finnish, orthodox, 8000, 0.8)
province:add_pop(craftsmen, finnish, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, finnish, orthodox, 5000, 0.9)
province:add_pop(burgeoise, finnish, orthodox, 5000, 0.9)
province:add_pop(clergymen, finnish, orthodox, 5000, 0.9)
province:add_pop(laborer, finnish, orthodox, 50000, 0.8)
province:add_pop(burgeoise, finnish, orthodox, 800, 0.9)
province:add_nucleus(finland)
province:add_nucleus(russia)
province:add_nucleus(scandinavia)
province:give_to(russia)

province = Province:new{ ref_name = "central finland", color = 0x8c49ff }
province.name = _("Central Finland")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, russian, orthodox, 5000, 0.9)
province:add_pop(farmer, russian, orthodox, 40000, 0.8)
province:add_pop(soldier, russian, orthodox, 8000, 0.8)
province:add_pop(craftsmen, russian, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, russian, orthodox, 5000, 0.9)
province:add_pop(burgeoise, russian, orthodox, 5000, 0.9)
province:add_pop(clergymen, russian, orthodox, 5000, 0.9)
province:add_pop(laborer, russian, orthodox, 50000, 0.8)
province:add_pop(burgeoise, russian, orthodox, 800, 0.9)
province:add_pop(artisan, finnish, orthodox, 5000, 0.9)
province:add_pop(farmer, finnish, orthodox, 40000, 0.8)
province:add_pop(soldier, finnish, orthodox, 8000, 0.8)
province:add_pop(craftsmen, finnish, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, finnish, orthodox, 5000, 0.9)
province:add_pop(burgeoise, finnish, orthodox, 5000, 0.9)
province:add_pop(clergymen, finnish, orthodox, 5000, 0.9)
province:add_pop(laborer, finnish, orthodox, 50000, 0.8)
province:add_pop(burgeoise, finnish, orthodox, 800, 0.9)
province:add_nucleus(finland)
province:add_nucleus(russia)
province:add_nucleus(scandinavia)
province:give_to(russia)

province = Province:new{ ref_name = "turku", color = 0x3aff5e }
province.name = _("Turku")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, russian, orthodox, 5000, 0.9)
province:add_pop(farmer, russian, orthodox, 40000, 0.8)
province:add_pop(soldier, russian, orthodox, 8000, 0.8)
province:add_pop(craftsmen, russian, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, russian, orthodox, 5000, 0.9)
province:add_pop(burgeoise, russian, orthodox, 5000, 0.9)
province:add_pop(clergymen, russian, orthodox, 5000, 0.9)
province:add_pop(laborer, russian, orthodox, 50000, 0.8)
province:add_pop(burgeoise, russian, orthodox, 800, 0.9)
province:add_pop(artisan, finnish, orthodox, 5000, 0.9)
province:add_pop(farmer, finnish, orthodox, 40000, 0.8)
province:add_pop(soldier, finnish, orthodox, 8000, 0.8)
province:add_pop(craftsmen, finnish, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, finnish, orthodox, 5000, 0.9)
province:add_pop(burgeoise, finnish, orthodox, 5000, 0.9)
province:add_pop(clergymen, finnish, orthodox, 5000, 0.9)
province:add_pop(laborer, finnish, orthodox, 50000, 0.8)
province:add_pop(burgeoise, finnish, orthodox, 800, 0.9)
province:add_nucleus(finland)
province:add_nucleus(russia)
province:add_nucleus(scandinavia)
province:give_to(russia)

province = Province:new{ ref_name = "helsinki", color = 0xffc942 }
province.name = _("Helsinki")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, russian, orthodox, 5000, 0.9)
province:add_pop(farmer, russian, orthodox, 40000, 0.8)
province:add_pop(soldier, russian, orthodox, 8000, 0.8)
province:add_pop(craftsmen, russian, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, russian, orthodox, 5000, 0.9)
province:add_pop(burgeoise, russian, orthodox, 5000, 0.9)
province:add_pop(clergymen, russian, orthodox, 5000, 0.9)
province:add_pop(laborer, russian, orthodox, 50000, 0.8)
province:add_pop(burgeoise, russian, orthodox, 800, 0.9)
province:add_pop(artisan, finnish, orthodox, 5000, 0.9)
province:add_pop(farmer, finnish, orthodox, 40000, 0.8)
province:add_pop(soldier, finnish, orthodox, 8000, 0.8)
province:add_pop(craftsmen, finnish, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, finnish, orthodox, 5000, 0.9)
province:add_pop(burgeoise, finnish, orthodox, 5000, 0.9)
province:add_pop(clergymen, finnish, orthodox, 5000, 0.9)
province:add_pop(laborer, finnish, orthodox, 50000, 0.8)
province:add_pop(burgeoise, finnish, orthodox, 800, 0.9)
province:add_nucleus(finland)
province:add_nucleus(russia)
province:add_nucleus(scandinavia)
province:give_to(russia)
finland:set_capital(province)

province = Province:new{ ref_name = "vaasa", color = 0x1cff91 }
province.name = _("Vaasa")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, russian, orthodox, 5000, 0.9)
province:add_pop(farmer, russian, orthodox, 40000, 0.8)
province:add_pop(soldier, russian, orthodox, 8000, 0.8)
province:add_pop(craftsmen, russian, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, russian, orthodox, 5000, 0.9)
province:add_pop(burgeoise, russian, orthodox, 5000, 0.9)
province:add_pop(clergymen, russian, orthodox, 5000, 0.9)
province:add_pop(laborer, russian, orthodox, 50000, 0.8)
province:add_pop(burgeoise, russian, orthodox, 800, 0.9)
province:add_pop(artisan, finnish, orthodox, 5000, 0.9)
province:add_pop(farmer, finnish, orthodox, 40000, 0.8)
province:add_pop(soldier, finnish, orthodox, 8000, 0.8)
province:add_pop(craftsmen, finnish, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, finnish, orthodox, 5000, 0.9)
province:add_pop(burgeoise, finnish, orthodox, 5000, 0.9)
province:add_pop(clergymen, finnish, orthodox, 5000, 0.9)
province:add_pop(laborer, finnish, orthodox, 50000, 0.8)
province:add_pop(burgeoise, finnish, orthodox, 800, 0.9)
province:add_nucleus(finland)
province:add_nucleus(russia)
province:add_nucleus(scandinavia)
province:give_to(russia)

province = Province:new{ ref_name = "oulu", color = 0xff42e8 }
province.name = _("Oulu")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, russian, orthodox, 5000, 0.9)
province:add_pop(farmer, russian, orthodox, 40000, 0.8)
province:add_pop(soldier, russian, orthodox, 8000, 0.8)
province:add_pop(craftsmen, russian, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, russian, orthodox, 5000, 0.9)
province:add_pop(burgeoise, russian, orthodox, 5000, 0.9)
province:add_pop(clergymen, russian, orthodox, 5000, 0.9)
province:add_pop(laborer, russian, orthodox, 50000, 0.8)
province:add_pop(burgeoise, russian, orthodox, 800, 0.9)
province:add_pop(artisan, finnish, orthodox, 5000, 0.9)
province:add_pop(farmer, finnish, orthodox, 40000, 0.8)
province:add_pop(soldier, finnish, orthodox, 8000, 0.8)
province:add_pop(craftsmen, finnish, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, finnish, orthodox, 5000, 0.9)
province:add_pop(burgeoise, finnish, orthodox, 5000, 0.9)
province:add_pop(clergymen, finnish, orthodox, 5000, 0.9)
province:add_pop(laborer, finnish, orthodox, 50000, 0.8)
province:add_pop(burgeoise, finnish, orthodox, 800, 0.9)
province:add_nucleus(finland)
province:add_nucleus(russia)
province:add_nucleus(scandinavia)
province:give_to(russia)

province = Province:new{ ref_name = "east_oulu", color = 0xe6d8ff }
province.name = _("East Oulu")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, russian, orthodox, 5000, 0.9)
province:add_pop(farmer, russian, orthodox, 40000, 0.8)
province:add_pop(soldier, russian, orthodox, 8000, 0.8)
province:add_pop(craftsmen, russian, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, russian, orthodox, 5000, 0.9)
province:add_pop(burgeoise, russian, orthodox, 5000, 0.9)
province:add_pop(clergymen, russian, orthodox, 5000, 0.9)
province:add_pop(laborer, russian, orthodox, 50000, 0.8)
province:add_pop(burgeoise, russian, orthodox, 800, 0.9)
province:add_pop(artisan, finnish, orthodox, 5000, 0.9)
province:add_pop(farmer, finnish, orthodox, 40000, 0.8)
province:add_pop(soldier, finnish, orthodox, 8000, 0.8)
province:add_pop(craftsmen, finnish, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, finnish, orthodox, 5000, 0.9)
province:add_pop(burgeoise, finnish, orthodox, 5000, 0.9)
province:add_pop(clergymen, finnish, orthodox, 5000, 0.9)
province:add_pop(laborer, finnish, orthodox, 50000, 0.8)
province:add_pop(burgeoise, finnish, orthodox, 800, 0.9)
province:add_nucleus(finland)
province:add_nucleus(russia)
province:add_nucleus(scandinavia)
province:give_to(russia)

province = Province:new{ ref_name = "lapland", color = 0xcd91ff }
province.name = _("Lapland")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, russian, orthodox, 5000, 0.9)
province:add_pop(farmer, russian, orthodox, 40000, 0.8)
province:add_pop(soldier, russian, orthodox, 8000, 0.8)
province:add_pop(craftsmen, russian, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, russian, orthodox, 5000, 0.9)
province:add_pop(burgeoise, russian, orthodox, 5000, 0.9)
province:add_pop(clergymen, russian, orthodox, 5000, 0.9)
province:add_pop(laborer, russian, orthodox, 50000, 0.8)
province:add_pop(burgeoise, russian, orthodox, 800, 0.9)
province:add_pop(artisan, finnish, orthodox, 5000, 0.9)
province:add_pop(farmer, finnish, orthodox, 40000, 0.8)
province:add_pop(soldier, finnish, orthodox, 8000, 0.8)
province:add_pop(craftsmen, finnish, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, finnish, orthodox, 5000, 0.9)
province:add_pop(burgeoise, finnish, orthodox, 5000, 0.9)
province:add_pop(clergymen, finnish, orthodox, 5000, 0.9)
province:add_pop(laborer, finnish, orthodox, 50000, 0.8)
province:add_pop(burgeoise, finnish, orthodox, 800, 0.9)
province:add_nucleus(finland)
province:add_nucleus(russia)
province:add_nucleus(scandinavia)
province:give_to(russia)

province = Province:new{ ref_name = "aland", color = 0x2dffd1 }
province.name = _("Åland")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, russian, orthodox, 5000, 0.9)
province:add_pop(farmer, russian, orthodox, 40000, 0.8)
province:add_pop(soldier, russian, orthodox, 8000, 0.8)
province:add_pop(craftsmen, russian, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, russian, orthodox, 5000, 0.9)
province:add_pop(burgeoise, russian, orthodox, 5000, 0.9)
province:add_pop(clergymen, russian, orthodox, 5000, 0.9)
province:add_pop(laborer, russian, orthodox, 50000, 0.8)
province:add_pop(burgeoise, russian, orthodox, 800, 0.9)
province:add_pop(artisan, finnish, orthodox, 5000, 0.9)
province:add_pop(farmer, finnish, orthodox, 40000, 0.8)
province:add_pop(soldier, finnish, orthodox, 8000, 0.8)
province:add_pop(craftsmen, finnish, orthodox, 5000, 0.9)
province:add_pop(bureaucrat, finnish, orthodox, 5000, 0.9)
province:add_pop(burgeoise, finnish, orthodox, 5000, 0.9)
province:add_pop(clergymen, finnish, orthodox, 5000, 0.9)
province:add_pop(laborer, finnish, orthodox, 50000, 0.8)
province:add_pop(burgeoise, finnish, orthodox, 800, 0.9)
province:add_nucleus(aland)
province:add_nucleus(sweden)
province:add_nucleus(finland)
province:add_nucleus(russia)
province:add_nucleus(scandinavia)
province:give_to(russia)

--------------------------------------------------------------
-- Continent: Europe
-- Subcontinent: Scandinavia
-- Country: Norway
province = Province:new{ ref_name = "oslo", color = 0x2bffb4 }
province.name = _("Oslo")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, norwegian, protestant, 5000, 0.9)
province:add_pop(farmer, norwegian, protestant, 40000, 0.8)
province:add_pop(soldier, norwegian, protestant, 8000, 0.8)
province:add_pop(craftsmen, norwegian, protestant, 5000, 0.9)
province:add_pop(bureaucrat, norwegian, protestant, 5000, 0.9)
province:add_pop(burgeoise, norwegian, protestant, 5000, 0.9)
province:add_pop(clergymen, norwegian, protestant, 5000, 0.9)
province:add_pop(laborer, norwegian, protestant, 50000, 0.8)
province:add_pop(burgeoise, norwegian, protestant, 800, 0.9)
province:add_nucleus(norway)
province:add_nucleus(scandinavia)
province:give_to(sweden)
norway:set_capital(province)

province = Province:new{ ref_name = "agder", color = 0xff5bfc }
province.name = _("Agder")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, norwegian, protestant, 5000, 0.9)
province:add_pop(farmer, norwegian, protestant, 40000, 0.8)
province:add_pop(soldier, norwegian, protestant, 8000, 0.8)
province:add_pop(craftsmen, norwegian, protestant, 5000, 0.9)
province:add_pop(bureaucrat, norwegian, protestant, 5000, 0.9)
province:add_pop(burgeoise, norwegian, protestant, 5000, 0.9)
province:add_pop(clergymen, norwegian, protestant, 5000, 0.9)
province:add_pop(laborer, norwegian, protestant, 50000, 0.8)
province:add_pop(burgeoise, norwegian, protestant, 800, 0.9)
province:add_nucleus(norway)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "vestfold_og_telemark", color = 0x729fff }
province.name = _("Vestfold og telemark")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, norwegian, protestant, 5000, 0.9)
province:add_pop(farmer, norwegian, protestant, 40000, 0.8)
province:add_pop(soldier, norwegian, protestant, 8000, 0.8)
province:add_pop(craftsmen, norwegian, protestant, 5000, 0.9)
province:add_pop(bureaucrat, norwegian, protestant, 5000, 0.9)
province:add_pop(burgeoise, norwegian, protestant, 5000, 0.9)
province:add_pop(clergymen, norwegian, protestant, 5000, 0.9)
province:add_pop(laborer, norwegian, protestant, 50000, 0.8)
province:add_pop(burgeoise, norwegian, protestant, 800, 0.9)
province:add_nucleus(norway)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "rogaland", color = 0xd154ff }
province.name = _("Rogaland")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, norwegian, protestant, 5000, 0.9)
province:add_pop(farmer, norwegian, protestant, 40000, 0.8)
province:add_pop(soldier, norwegian, protestant, 8000, 0.8)
province:add_pop(craftsmen, norwegian, protestant, 5000, 0.9)
province:add_pop(bureaucrat, norwegian, protestant, 5000, 0.9)
province:add_pop(burgeoise, norwegian, protestant, 5000, 0.9)
province:add_pop(clergymen, norwegian, protestant, 5000, 0.9)
province:add_pop(laborer, norwegian, protestant, 50000, 0.8)
province:add_pop(burgeoise, norwegian, protestant, 800, 0.9)
province:add_nucleus(norway)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "nordland", color = 0x5005ff }
province.name = _("Nordland")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, norwegian, protestant, 5000, 0.9)
province:add_pop(farmer, norwegian, protestant, 40000, 0.8)
province:add_pop(soldier, norwegian, protestant, 8000, 0.8)
province:add_pop(craftsmen, norwegian, protestant, 5000, 0.9)
province:add_pop(bureaucrat, norwegian, protestant, 5000, 0.9)
province:add_pop(burgeoise, norwegian, protestant, 5000, 0.9)
province:add_pop(clergymen, norwegian, protestant, 5000, 0.9)
province:add_pop(laborer, norwegian, protestant, 50000, 0.8)
province:add_pop(burgeoise, norwegian, protestant, 800, 0.9)
province:add_nucleus(norway)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "trondelag", color = 0x947fff }
province.name = _("Trøndelag")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, norwegian, protestant, 5000, 0.9)
province:add_pop(farmer, norwegian, protestant, 40000, 0.8)
province:add_pop(soldier, norwegian, protestant, 8000, 0.8)
province:add_pop(craftsmen, norwegian, protestant, 5000, 0.9)
province:add_pop(bureaucrat, norwegian, protestant, 5000, 0.9)
province:add_pop(burgeoise, norwegian, protestant, 5000, 0.9)
province:add_pop(clergymen, norwegian, protestant, 5000, 0.9)
province:add_pop(laborer, norwegian, protestant, 50000, 0.8)
province:add_pop(burgeoise, norwegian, protestant, 800, 0.9)
province:add_nucleus(norway)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "vestland", color = 0x9000ff }
province.name = _("Vestland")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, norwegian, protestant, 5000, 0.9)
province:add_pop(farmer, norwegian, protestant, 40000, 0.8)
province:add_pop(soldier, norwegian, protestant, 8000, 0.8)
province:add_pop(craftsmen, norwegian, protestant, 5000, 0.9)
province:add_pop(bureaucrat, norwegian, protestant, 5000, 0.9)
province:add_pop(burgeoise, norwegian, protestant, 5000, 0.9)
province:add_pop(clergymen, norwegian, protestant, 5000, 0.9)
province:add_pop(laborer, norwegian, protestant, 50000, 0.8)
province:add_pop(burgeoise, norwegian, protestant, 800, 0.9)
province:add_nucleus(norway)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "hedmark", color = 0xff001d }
province.name = _("Hedmark")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, norwegian, protestant, 5000, 0.9)
province:add_pop(farmer, norwegian, protestant, 40000, 0.8)
province:add_pop(soldier, norwegian, protestant, 8000, 0.8)
province:add_pop(craftsmen, norwegian, protestant, 5000, 0.9)
province:add_pop(bureaucrat, norwegian, protestant, 5000, 0.9)
province:add_pop(burgeoise, norwegian, protestant, 5000, 0.9)
province:add_pop(clergymen, norwegian, protestant, 5000, 0.9)
province:add_pop(laborer, norwegian, protestant, 50000, 0.8)
province:add_pop(burgeoise, norwegian, protestant, 800, 0.9)
province:add_nucleus(norway)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "oppland", color = 0xb5ffc6 }
province.name = _("Oppland")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, norwegian, protestant, 5000, 0.9)
province:add_pop(farmer, norwegian, protestant, 40000, 0.8)
province:add_pop(soldier, norwegian, protestant, 8000, 0.8)
province:add_pop(craftsmen, norwegian, protestant, 5000, 0.9)
province:add_pop(bureaucrat, norwegian, protestant, 5000, 0.9)
province:add_pop(burgeoise, norwegian, protestant, 5000, 0.9)
province:add_pop(clergymen, norwegian, protestant, 5000, 0.9)
province:add_pop(laborer, norwegian, protestant, 50000, 0.8)
province:add_pop(burgeoise, norwegian, protestant, 800, 0.9)
province:add_nucleus(norway)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "troms", color = 0x00ffbf }
province.name = _("Troms")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, norwegian, protestant, 5000, 0.9)
province:add_pop(farmer, norwegian, protestant, 40000, 0.8)
province:add_pop(soldier, norwegian, protestant, 8000, 0.8)
province:add_pop(craftsmen, norwegian, protestant, 5000, 0.9)
province:add_pop(bureaucrat, norwegian, protestant, 5000, 0.9)
province:add_pop(burgeoise, norwegian, protestant, 5000, 0.9)
province:add_pop(clergymen, norwegian, protestant, 5000, 0.9)
province:add_pop(laborer, norwegian, protestant, 50000, 0.8)
province:add_pop(burgeoise, norwegian, protestant, 800, 0.9)
province:add_nucleus(norway)
province:add_nucleus(scandinavia)
province:give_to(sweden)

province = Province:new{ ref_name = "ostfold", color = 0x8cfbff }
province.name = _("Østfold")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, norwegian, protestant, 5000, 0.9)
province:add_pop(farmer, norwegian, protestant, 40000, 0.8)
province:add_pop(soldier, norwegian, protestant, 8000, 0.8)
province:add_pop(craftsmen, norwegian, protestant, 5000, 0.9)
province:add_pop(bureaucrat, norwegian, protestant, 5000, 0.9)
province:add_pop(burgeoise, norwegian, protestant, 5000, 0.9)
province:add_pop(clergymen, norwegian, protestant, 5000, 0.9)
province:add_pop(laborer, norwegian, protestant, 50000, 0.8)
province:add_pop(burgeoise, norwegian, protestant, 800, 0.9)
province:add_nucleus(norway)
province:add_nucleus(scandinavia)
province:give_to(sweden)
