--------------------------------------------------------------
-- Continent: Europe
-- Subcontinent: Iberia
-- Country: Spain
--A Coruña
province = Province:new{ ref_name = "a_coruna", color = 0x9b9dcb }
province.name = _("A Coruña")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Lugo
province = Province:new{ ref_name = "lugo", color = 0xbe8d60 }
province.name = _("Lugo")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Pontevedra
province = Province:new{ ref_name = "pontevedra", color = 0x37d160 }
province.name = _("Pontevedra")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Ourense
province = Province:new{ ref_name = "ourense", color = 0x6a8080 }
province.name = _("Ourense")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Asturias
province = Province:new{ ref_name = "asturias", color = 0xbbe160 }
province.name = _("Asturias")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Ávila
province = Province:new{ ref_name = "avila", color = 0x569da0 }
province.name = _("Ávila")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Burgos
province = Province:new{ ref_name = "burgos", color = 0xbdeb40 }
province.name = _("Burgos")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--León
province = Province:new{ ref_name = "leon", color = 0x469340 }
province.name = _("León")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Palencia
province = Province:new{ ref_name = "palencia", color = 0xc99d9d }
province.name = _("Palencia")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Salamanca
province = Province:new{ ref_name = "salamanca", color = 0xe13220 }
province.name = _("Salamanca")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Soria
province = Province:new{ ref_name = "soria", color = 0xf7a720 }
province.name = _("Soria")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Valladolid
province = Province:new{ ref_name = "valladolid", color = 0x5b1960 }
province.name = _("Valladolid")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Zamora
province = Province:new{ ref_name = "zamora", color = 0x44a620 }
province.name = _("Zamora")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Cantabria
province = Province:new{ ref_name = "cantabria", color = 0xc9cb9d }
province.name = _("Cantabria")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Badajoz
province = Province:new{ ref_name = "badajoz", color = 0xf7a700 }
province.name = _("Badajoz")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Cáceres
province = Province:new{ ref_name = "caceres", color = 0x9b9d95 }
province.name = _("Cáceres")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Almería
province = Province:new{ ref_name = "almeria", color = 0x4cfdc0 }
province.name = _("Almería")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Cádiz
province = Province:new{ ref_name = "cadiz", color = 0x723340 }
province.name = _("Cádiz")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Córdoba
province = Province:new{ ref_name = "cordoba_spain", color = 0xc30b00 }
province.name = _("Córdoba")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Granada
province = Province:new{ ref_name = "granada", color = 0xc11de0 }
province.name = _("Granada")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Huelva
province = Province:new{ ref_name = "huelva", color = 0x4bb4e0 }
province.name = _("Huelva")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Jaén
province = Province:new{ ref_name = "jaen", color = 0x555500 }
province.name = _("Jaén")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Málaga
province = Province:new{ ref_name = "malaga", color = 0xce9760 }
province.name = _("Málaga")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Seville
province = Province:new{ ref_name = "Seville", color = 0x5c9d91 }
province.name = _("Seville")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Madrid
province = Province:new{ ref_name = "madrid", color = 0x6e72d1 }
province.name = _("Madrid")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Albacete
province = Province:new{ ref_name = "albacete", color = 0x674b00 }
province.name = _("Albacete")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Ciudad Real
province = Province:new{ ref_name = "ciudad_real", color = 0x9bcbd2 }
province.name = _("Ciudad Real")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Cuenca
province = Province:new{ ref_name = "cuenca", color = 0xd1cc80 }
province.name = _("Cuenca")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Guadalajara
province = Province:new{ ref_name = "guadalajara", color = 0xe08e40 }
province.name = _("Guadalajara")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Toledo
province = Province:new{ ref_name = "toledo", color = 0x4736e0 }
province.name = _("Toledo")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Murcia
province = Province:new{ ref_name = "murcia", color = 0xffee9d }
province.name = _("Murcia")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Mallorca
province = Province:new{ ref_name = "mallorca", color = 0x86557f }
province.name = _("Mallorca")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Menorca
province = Province:new{ ref_name = "Menorca", color = 0x865596 }
province.name = _("Menorca")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Ibiza
province = Province:new{ ref_name = "ibiza", color = 0x9d557f }
province.name = _("Ibiza")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Barcelona
province = Province:new{ ref_name = "barcelona", color = 0xebe36c }
province.name = _("Barcelona")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Girona
province = Province:new{ ref_name = "girona", color = 0x220180 }
province.name = _("Girona")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Lleida
province = Province:new{ ref_name = "lleida", color = 0x69dc00 }
province.name = _("Lleida")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Tarragona
province = Province:new{ ref_name = "tarragona", color = 0xcd4ea0 }
province.name = _("Tarragona")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Alicante
province = Province:new{ ref_name = "alicante", color = 0xd270a0 }
province.name = _("Alicante")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Castellón
province = Province:new{ ref_name = "castellon", color = 0xffe36c }
province.name = _("Castellón")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Valencia
province = Province:new{ ref_name = "valencia", color = 0xd501c0 }
province.name = _("Valencia")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Segovia
province = Province:new{ ref_name = "segovia", color = 0xc11e20 }
province.name = _("Segovia")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Pequeñotereul
province = Province:new{ ref_name = "pequenotereul", color = 0xce9740 }
province.name = _("Pequeñotereul")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Huesca
province = Province:new{ ref_name = "huesca", color = 0xd8c776 }
province.name = _("Huesca")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Zaragoza
province = Province:new{ ref_name = "zaragoza", color = 0x2afd40 }
province.name = _("Zaragoza")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Teruel
province = Province:new{ ref_name = "teruel", color = 0x59d220 }
province.name = _("Teruel")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Álava
province = Province:new{ ref_name = "alava", color = 0x7dbbbb }
province.name = _("Álava")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Biscay
province = Province:new{ ref_name = "biscay", color = 0xb6dea0 }
province.name = _("Biscay")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Gipuzkoa
province = Province:new{ ref_name = "gipuzkoa", color = 0x57e5a0 }
province.name = _("Gipuzkoa")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)
--Navarre
province = Province:new{ ref_name = "navarre", color = 0x976478 }
province.name = _("Navarre")
province:register()
province:add_pop(artisan, spanish, catholic, 5000, 0.9)
province:add_pop(farmer, spanish, catholic, 40000, 0.8)
province:add_pop(soldier, spanish, catholic, 8000, 0.8)
province:add_pop(craftsmen, spanish, catholic, 5000, 0.9)
province:add_pop(bureaucrat, spanish, catholic, 5000, 0.9)
province:add_pop(aristocrat, spanish, catholic, 5000, 0.9)
province:add_pop(clergymen, spanish, catholic, 5000, 0.9)
province:add_pop(laborer, spanish, catholic, 50000, 0.8)
province:add_pop(entrepreneur, spanish, catholic, 800, 0.9)
province:add_nucleus(spain)
province:add_nucleus(iberia)
province:give_to(spain)