--------------------------------------------------------------
-- Continent: Africa
-- Subcontinent: Northern Africa
-- Country: Tunis/Tunisia/French North Africa
province = Province:new{ ref_name = "nabeul", color = 0x7d7140 }
province.name = _("Nabeul")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, arabic, islamic, 10, 0.6)
province:add_pop(farmer, arabic, islamic, 8000, 0.4)
province:add_pop(soldier, arabic, islamic, 10, 0.6)
province:add_pop(craftsmen, arabic, islamic, 10, 0.4)
province:add_pop(bureaucrat, arabic, islamic, 10, 0.8)
province:add_pop(aristocrat, arabic, islamic, 25, 0.5)
province:add_pop(clergymen, arabic, islamic, 10, 0.6)
province:add_pop(laborer, arabic, islamic, 1000, 0.5)
province:add_pop(entrepreneur, arabic, islamic, 5, 0.9)
province:add_nucleus(arabia)
province:add_nucleus(tunis)
province:give_to(tunis)

province = Province:new{ ref_name = "monastir", color = 0x32cd60 }
province.name = _("Monastir")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, arabic, islamic, 10, 0.6)
province:add_pop(farmer, arabic, islamic, 8000, 0.4)
province:add_pop(soldier, arabic, islamic, 10, 0.6)
province:add_pop(craftsmen, arabic, islamic, 10, 0.4)
province:add_pop(bureaucrat, arabic, islamic, 10, 0.8)
province:add_pop(aristocrat, arabic, islamic, 25, 0.5)
province:add_pop(clergymen, arabic, islamic, 10, 0.6)
province:add_pop(laborer, arabic, islamic, 1000, 0.5)
province:add_pop(entrepreneur, arabic, islamic, 5, 0.9)
province:add_nucleus(arabia)
province:add_nucleus(tunis)
province:give_to(tunis)

province = Province:new{ ref_name = "sfax", color = 0xee1d00 }
province.name = _("Sfax")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, arabic, islamic, 10, 0.6)
province:add_pop(farmer, arabic, islamic, 8000, 0.4)
province:add_pop(soldier, arabic, islamic, 10, 0.6)
province:add_pop(craftsmen, arabic, islamic, 10, 0.4)
province:add_pop(bureaucrat, arabic, islamic, 10, 0.8)
province:add_pop(aristocrat, arabic, islamic, 25, 0.5)
province:add_pop(clergymen, arabic, islamic, 10, 0.6)
province:add_pop(laborer, arabic, islamic, 1000, 0.5)
province:add_pop(entrepreneur, arabic, islamic, 5, 0.9)
province:add_nucleus(arabia)
province:add_nucleus(tunis)
province:give_to(tunis)

province = Province:new{ ref_name = "soghuan", color = 0x46aac0 }
province.name = _("Soghuan")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, arabic, islamic, 10, 0.6)
province:add_pop(farmer, arabic, islamic, 8000, 0.4)
province:add_pop(soldier, arabic, islamic, 10, 0.6)
province:add_pop(craftsmen, arabic, islamic, 10, 0.4)
province:add_pop(bureaucrat, arabic, islamic, 10, 0.8)
province:add_pop(aristocrat, arabic, islamic, 25, 0.5)
province:add_pop(clergymen, arabic, islamic, 10, 0.6)
province:add_pop(laborer, arabic, islamic, 1000, 0.5)
province:add_pop(entrepreneur, arabic, islamic, 5, 0.9)
province:add_nucleus(arabia)
province:add_nucleus(tunis)
province:give_to(tunis)

province = Province:new{ ref_name = "kasserine", color = 0xfb3dff }
province.name = _("Kasserine")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, arabic, islamic, 10, 0.6)
province:add_pop(farmer, arabic, islamic, 8000, 0.4)
province:add_pop(soldier, arabic, islamic, 10, 0.6)
province:add_pop(craftsmen, arabic, islamic, 10, 0.4)
province:add_pop(bureaucrat, arabic, islamic, 10, 0.8)
province:add_pop(aristocrat, arabic, islamic, 25, 0.5)
province:add_pop(clergymen, arabic, islamic, 10, 0.6)
province:add_pop(laborer, arabic, islamic, 1000, 0.5)
province:add_pop(entrepreneur, arabic, islamic, 5, 0.9)
province:add_nucleus(arabia)
province:add_nucleus(tunis)
province:give_to(tunis)

province = Province:new{ ref_name = "bizerte", color = 0x083bc0 }
province.name = _("Bizerte")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, arabic, islamic, 10, 0.6)
province:add_pop(farmer, arabic, islamic, 8000, 0.4)
province:add_pop(soldier, arabic, islamic, 10, 0.6)
province:add_pop(craftsmen, arabic, islamic, 10, 0.4)
province:add_pop(bureaucrat, arabic, islamic, 10, 0.8)
province:add_pop(aristocrat, arabic, islamic, 25, 0.5)
province:add_pop(clergymen, arabic, islamic, 10, 0.6)
province:add_pop(laborer, arabic, islamic, 1000, 0.5)
province:add_pop(entrepreneur, arabic, islamic, 5, 0.9)
province:add_nucleus(arabia)
province:add_nucleus(tunis)
province:give_to(tunis)

province = Province:new{ ref_name = "gabes", color = 0x7930c0 }
province.name = _("Gabès")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, arabic, islamic, 10, 0.6)
province:add_pop(farmer, arabic, islamic, 8000, 0.4)
province:add_pop(soldier, arabic, islamic, 10, 0.6)
province:add_pop(craftsmen, arabic, islamic, 10, 0.4)
province:add_pop(bureaucrat, arabic, islamic, 10, 0.8)
province:add_pop(aristocrat, arabic, islamic, 25, 0.5)
province:add_pop(clergymen, arabic, islamic, 10, 0.6)
province:add_pop(laborer, arabic, islamic, 1000, 0.5)
province:add_pop(entrepreneur, arabic, islamic, 5, 0.9)
province:add_nucleus(arabia)
province:add_nucleus(tunis)
province:give_to(tunis)

province = Province:new{ ref_name = "tatouine", color = 0xa45260 }
province.name = _("Tatouine")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, arabic, islamic, 10, 0.6)
province:add_pop(farmer, arabic, islamic, 8000, 0.4)
province:add_pop(soldier, arabic, islamic, 10, 0.6)
province:add_pop(craftsmen, arabic, islamic, 10, 0.4)
province:add_pop(bureaucrat, arabic, islamic, 10, 0.8)
province:add_pop(aristocrat, arabic, islamic, 25, 0.5)
province:add_pop(clergymen, arabic, islamic, 10, 0.6)
province:add_pop(laborer, arabic, islamic, 1000, 0.5)
province:add_pop(entrepreneur, arabic, islamic, 5, 0.9)
province:add_nucleus(arabia)
province:add_nucleus(tunis)
province:give_to(tunis)

province = Province:new{ ref_name = "tozeur", color = 0xe27980 }
province.name = _("Tozeur")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, arabic, islamic, 10, 0.6)
province:add_pop(farmer, arabic, islamic, 8000, 0.4)
province:add_pop(soldier, arabic, islamic, 10, 0.6)
province:add_pop(craftsmen, arabic, islamic, 10, 0.4)
province:add_pop(bureaucrat, arabic, islamic, 10, 0.8)
province:add_pop(aristocrat, arabic, islamic, 25, 0.5)
province:add_pop(clergymen, arabic, islamic, 10, 0.6)
province:add_pop(laborer, arabic, islamic, 1000, 0.5)
province:add_pop(entrepreneur, arabic, islamic, 5, 0.9)
province:add_nucleus(arabia)
province:add_nucleus(tunis)
province:give_to(tunis)

province = Province:new{ ref_name = "sidi_bouzid", color = 0x39e5c0 }
province.name = _("Sidi Bouzid")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, arabic, islamic, 10, 0.6)
province:add_pop(farmer, arabic, islamic, 8000, 0.4)
province:add_pop(soldier, arabic, islamic, 10, 0.6)
province:add_pop(craftsmen, arabic, islamic, 10, 0.4)
province:add_pop(bureaucrat, arabic, islamic, 10, 0.8)
province:add_pop(aristocrat, arabic, islamic, 25, 0.5)
province:add_pop(clergymen, arabic, islamic, 10, 0.6)
province:add_pop(laborer, arabic, islamic, 1000, 0.5)
province:add_pop(entrepreneur, arabic, islamic, 5, 0.9)
province:add_nucleus(arabia)
province:add_nucleus(tunis)
province:give_to(tunis)

province = Province:new{ ref_name = "beja", color = 0xa9b7a0 }
province.name = _("Béja")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, arabic, islamic, 10, 0.6)
province:add_pop(farmer, arabic, islamic, 8000, 0.4)
province:add_pop(soldier, arabic, islamic, 10, 0.6)
province:add_pop(craftsmen, arabic, islamic, 10, 0.4)
province:add_pop(bureaucrat, arabic, islamic, 10, 0.8)
province:add_pop(aristocrat, arabic, islamic, 25, 0.5)
province:add_pop(clergymen, arabic, islamic, 10, 0.6)
province:add_pop(laborer, arabic, islamic, 1000, 0.5)
province:add_pop(entrepreneur, arabic, islamic, 5, 0.9)
province:add_nucleus(arabia)
province:add_nucleus(tunis)
province:give_to(tunis)

province = Province:new{ ref_name = "kairouan", color = 0xa772c0 }
province.name = _("Kairouan")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, arabic, islamic, 10, 0.6)
province:add_pop(farmer, arabic, islamic, 8000, 0.4)
province:add_pop(soldier, arabic, islamic, 10, 0.6)
province:add_pop(craftsmen, arabic, islamic, 10, 0.4)
province:add_pop(bureaucrat, arabic, islamic, 10, 0.8)
province:add_pop(aristocrat, arabic, islamic, 25, 0.5)
province:add_pop(clergymen, arabic, islamic, 10, 0.6)
province:add_pop(laborer, arabic, islamic, 1000, 0.5)
province:add_pop(entrepreneur, arabic, islamic, 5, 0.9)
province:add_nucleus(arabia)
province:add_nucleus(tunis)
province:give_to(tunis)

province = Province:new{ ref_name = "kebili", color = 0x9f7e20 }
province.name = _("Kebili")
province:register()
province:add_industry(wheat_farm, united_states, andes_transport)
province:add_pop(artisan, arabic, islamic, 10, 0.6)
province:add_pop(farmer, arabic, islamic, 8000, 0.4)
province:add_pop(soldier, arabic, islamic, 10, 0.6)
province:add_pop(craftsmen, arabic, islamic, 10, 0.4)
province:add_pop(bureaucrat, arabic, islamic, 10, 0.8)
province:add_pop(aristocrat, arabic, islamic, 25, 0.5)
province:add_pop(clergymen, arabic, islamic, 10, 0.6)
province:add_pop(laborer, arabic, islamic, 1000, 0.5)
province:add_pop(entrepreneur, arabic, islamic, 5, 0.9)
province:add_nucleus(arabia)
province:add_nucleus(tunis)
province:give_to(tunis)